# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  python: circleci/python@2.0.3

jobs:
  build:
    docker:
      - image: cimg/python:3.11.6

    steps:
      - checkout

      - run:
          name: Run counterparty-lib setup and install
          command: |
            pip install --upgrade pip
            pip install hatch

      - persist_to_workspace:
          root: ~/
          paths:
            - .

  test:
    docker:
      - image: cimg/python:3.11.6

    steps:
      - attach_workspace:
          at: ~/
      
      - run:
          name: "Run tests"
          command: |
            mkdir test-results
            hatch run pytest --junitxml=test-results/junit.xml --verbose --skiptestbook=all --cov-config=.coveragerc --cov-report=term-missing --cov=./ counterpartylib

      - store_test_results:
          path: test-results

  test-reparse-testnet:
    docker:
        - image: cimg/python:3.11.6

    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: "Get latest testnet db file"
          command: |
            mkdir -p ~/.local/share/counterparty
            wget https://counterparty.io/bootstrap/counterparty-db-testnet-7.latest.tar.gz -O ~/.local/share/counterparty/counterparty-db-testnet.latest.tar.gz
            tar -C ~/.local/share/counterparty -xvzf ~/.local/share/counterparty/counterparty-db-testnet.latest.tar.gz

      - run:
          name: "Run testnet reparse test"
          command: |
            mkdir test-results
            hatch run pytest --junitxml=test-results/junit.xml --log-cli-level=INFO --show-capture=no --testbook=testnet -k test_book counterpartylib/test/reparse_test.py

      - store_test_results:
          path: test-results

  test-reparse-mainnet:
    docker:
        - image: cimg/python:3.11.6

    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: "Get latest mainnet db file"
          command: |
            mkdir -p ~/.local/share/counterparty
            wget https://counterparty.io/bootstrap/counterparty-db.latest.tar.gz -O ~/.local/share/counterparty/counterparty-db.latest.tar.gz
            tar -C ~/.local/share/counterparty -xvzf ~/.local/share/counterparty/counterparty-db.latest.tar.gz

      - run:
          name: "Run testnet reparse test"
          command: |
            mkdir test-results
            hatch run pytest --junitxml=test-results/junit.xml --log-cli-level=INFO --show-capture=no --testbook=mainnet -k test_book counterpartylib/test/reparse_test.py
      
      - store_test_results:
          path: test-results


workflows:
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - test-reparse-testnet:
          requires:
            - build