# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  python: circleci/python@2.0.3

jobs:

  test-book-testnet:
    docker:
        - image: cimg/python:3.11.6

    steps:
      - run:
          name: "TODO"
          command: |
              echo "Success"

workflows:
  build-and-test:
    jobs:
      - test-book-testnet