x-bitcoind-common: &bitcoind-common
  image: kylemanna/bitcoind:latest
  stop_grace_period: 1m
  volumes:
    - data:/bitcoin/.bitcoin
  restart: unless-stopped

x-counterparty-common: &counterparty-common
  image: counterparty/counterparty:v10.9.1
  stop_grace_period: 1m
  volumes:
    - data:/root/.bitcoin
    - data:/data
  environment:
    - XDG_DATA_HOME=/data/
    - XDG_LOG_HOME=/data/
  restart: unless-stopped

services:

  ####################
  # Mainnet Services #
  ####################

  bitcoind:
    <<: *bitcoind-common
    profiles:
      - mainnet
    ports: 
      - "8332:8332"
      - "9332:9332"
      - "9333:9333"
    command: 
      - "-chain=main"
      - "-rpcallowip=0.0.0.0/0"
      - "-rpcbind=0.0.0.0"
      - "-rpcuser=rpc"
      - "-rpcpassword=rpc"
      - "-listen=1"
      - "-server=1"
      - "-printtoconsole=1"
      - "-addresstype=legacy"
      - "-txindex=1"
      - "-prune=0"
      - "-dbcache=4000"
      - "-mempoolfullrbf=1"
      - "-zmqpubrawtx=tcp://0.0.0.0:9332"
      - "-zmqpubhashtx=tcp://0.0.0.0:9332"
      - "-zmqpubsequence=tcp://0.0.0.0:9332"
      - "-zmqpubrawblock=tcp://0.0.0.0:9333"

  counterparty-core:
    <<: *counterparty-common
    profiles:
      - mainnet
    links:
      - bitcoind
    ports:
      - "4000:4000"                                        # API v2
      - "4100:4100"                                        # API v1
    command:
      - start
      - "--backend-connect=bitcoind"
      - "--rpc-host=0.0.0.0"
      - "--api-host=0.0.0.0"
      - "--catch-up=bootstrap"
      #- "--verbose"

  #####################
  # Testnet3 Services #
  #####################

  bitcoind-testnet3:
    <<: *bitcoind-common
    profiles:
      - testnet3
    ports: 
      - "18332:18332"
      - "19332:19332"
      - "19333:19333"
    command: 
      - "-chain=test"
      - "-rpcallowip=0.0.0.0/0"
      - "-rpcbind=0.0.0.0"
      - "-rpcuser=rpc"
      - "-rpcpassword=rpc"
      - "-listen=1"
      - "-server=1"
      - "-printtoconsole=1"
      - "-addresstype=legacy"
      - "-txindex=1"
      - "-prune=0"
      - "-dbcache=4000"
      - "-mempoolfullrbf=1"
      - "-zmqpubrawtx=tcp://0.0.0.0:19332"
      - "-zmqpubhashtx=tcp://0.0.0.0:19332"
      - "-zmqpubsequence=tcp://0.0.0.0:19332"
      - "-zmqpubrawblock=tcp://0.0.0.0:19333"

  counterparty-core-testne3:
    <<: *counterparty-common
    profiles:
      - testnet3
    links:
      - bitcoind-testnet3
    ports:
      - "14000:14000"                                      # API v2
      - "14100:14100"                                      # API v1
    command:
      - start
      - "--testnet3"
      - "--backend-connect=bitcoind-testnet3"
      - "--rpc-host=0.0.0.0"
      - "--api-host=0.0.0.0"
      - "--catch-up=bootstrap"
      #- "--verbose"

  #####################
  # Testnet4 Services #
  #####################

  bitcoind-testnet4:
    <<: *bitcoind-common
    profiles:
      - testnet4
    ports: 
      - "48332:48332"
      - "49332:49332"
      - "49333:49333"
    command: 
      - "-chain=testnet4"
      - "-rpcallowip=0.0.0.0/0"
      - "-rpcbind=0.0.0.0"
      - "-rpcuser=rpc"
      - "-rpcpassword=rpc"
      - "-listen=1"
      - "-server=1"
      - "-printtoconsole=1"
      - "-addresstype=legacy"
      - "-txindex=1"
      - "-prune=0"
      - "-dbcache=4000"
      - "-mempoolfullrbf=1"
      - "-zmqpubrawtx=tcp://0.0.0.0:49332"
      - "-zmqpubhashtx=tcp://0.0.0.0:49332"
      - "-zmqpubsequence=tcp://0.0.0.0:49332"
      - "-zmqpubrawblock=tcp://0.0.0.0:49333"

  counterparty-core-testne4:
    <<: *counterparty-common
    profiles:
      - testnet4
    links:
      - bitcoind-testnet4
    ports:
      - "44000:44000"                                      # API v2
      - "44100:44100"                                      # API v1
    command:
      - start
      - "--testnet4"
      - "--backend-connect=bitcoind-testnet4"
      - "--rpc-host=0.0.0.0"
      - "--api-host=0.0.0.0"
      - "--catch-up=bootstrap"



  #####################
  # Regtest Services #
  #####################

  bitcoind-regtest:
    <<: *bitcoind-common
    profiles:
      - regtest
    ports: 
      - "18443:18443"
      - "29332:29332"
      - "29333:29333"
    command: 
      - "-chain=regtest"
      - "-rpcallowip=0.0.0.0/0"
      - "-rpcbind=0.0.0.0"
      - "-rpcuser=rpc"
      - "-rpcpassword=rpc"
      - "-listen=1"
      - "-server=1"
      - "-printtoconsole=1"
      - "-addresstype=legacy"
      - "-txindex=1"
      - "-prune=0"
      - "-dbcache=4000"
      - "-mempoolfullrbf=1"
      - "-zmqpubrawtx=tcp://0.0.0.0:29332"
      - "-zmqpubhashtx=tcp://0.0.0.0:29332"
      - "-zmqpubsequence=tcp://0.0.0.0:29332"
      - "-zmqpubrawblock=tcp://0.0.0.0:29333"

  counterparty-core-regtest:
    <<: *counterparty-common
    profiles:
      - regtest
    links:
      - bitcoind-regtest
    ports:
      - "24000:24000"                                      # API v2
      - "24100:24100"                                      # API v1
    command:
      - start
      - "--regtest"
      - "--backend-connect=bitcoind-regtest"
      - "--rpc-host=0.0.0.0"
      - "--api-host=0.0.0.0"


volumes: 
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${COUNTERPARTY_DOCKER_DATA:-${XDG_DATA_HOME:-~/.local/share}}/counterparty-docker-data
