x-bitcoind-common: &bitcoind-common
  image: kylemanna/bitcoind:latest
  stop_grace_period: 1m
  volumes:
    - data:/bitcoin/.bitcoin
  restart: unless-stopped

x-addrindexrs-common: &addrindexrs-common
  image: counterparty/addrindexrs:v0.4.6
  volumes:
    - data:/root/.bitcoin
    - data:/data
  environment:
    - ADDRINDEXRS_JSONRPC_IMPORT=${ADDRINDEXRS_JSONRPC_IMPORT:-false}
  restart: unless-stopped

x-counterparty-common: &counterparty-common
  image: counterparty/counterparty:v10.7.2-alpha.1
  stop_grace_period: 1m
  volumes:
    - data:/root/.bitcoin
    - data:/data
  environment:
    - XDG_DATA_HOME=/data/
    - XDG_LOG_HOME=/data/
  restart: unless-stopped

services:

  ####################
  # Mainnet Services #
  ####################

  bitcoind:
    <<: *bitcoind-common
    profiles:
      - mainnet
    ports: 
      - "8332:8332"
      - "9332:9332"
      - "9333:9333"
    command: 
      - "-chain=main"
      - "-rpcallowip=0.0.0.0/0"
      - "-rpcbind=0.0.0.0"
      - "-rpcuser=rpc"
      - "-rpcpassword=rpc"
      - "-listen=1"
      - "-server=1"
      - "-printtoconsole=1"
      - "-addresstype=legacy"
      - "-txindex=1"
      - "-prune=0"
      - "-dbcache=4000"
      - "-mempoolfullrbf=1"
      - "-zmqpubrawtx=tcp://0.0.0.0:9332"
      - "-zmqpubhashtx=tcp://0.0.0.0:9332"
      - "-zmqpubsequence=tcp://0.0.0.0:9332"
      - "-zmqpubrawblock=tcp://0.0.0.0:9333"

  addrindexrs:
    <<: *addrindexrs-common
    profiles:
      - mainnet
    links:
      - bitcoind
    ports:
      - "8432:8432"
    command:
      - "--indexer-rpc-host=0.0.0.0"
      - "--daemon-rpc-host=bitcoind"
      - "--cookie=rpc:rpc"
      - "-vvv"
      - "--db-dir=/data/"

  counterparty-core:
    <<: *counterparty-common
    profiles:
      - mainnet
    links:
      - bitcoind
      - addrindexrs
    ports:
      - "4000:4000"                                        # API v2
      - "4100:4100"                                        # API v1
    command:
      - start
      - "--backend-connect=bitcoind"
      - "--indexd-connect=addrindexrs"
      - "--rpc-host=0.0.0.0"
      - "--api-host=0.0.0.0"
      - "--catch-up=bootstrap"
      #- "--verbose"

  ###################
  # Testnet Services #
  ###################

  bitcoind-testnet:
    <<: *bitcoind-common
    profiles:
      - testnet
    ports: 
      - "18332:18332"
      - "19332:19332"
      - "19333:19333"
    command: 
      - "-chain=test"
      - "-rpcallowip=0.0.0.0/0"
      - "-rpcbind=0.0.0.0"
      - "-rpcuser=rpc"
      - "-rpcpassword=rpc"
      - "-listen=1"
      - "-server=1"
      - "-printtoconsole=1"
      - "-addresstype=legacy"
      - "-txindex=1"
      - "-prune=0"
      - "-dbcache=4000"
      - "-mempoolfullrbf=1"
      - "-zmqpubrawtx=tcp://0.0.0.0:19332"
      - "-zmqpubhashtx=tcp://0.0.0.0:19332"
      - "-zmqpubsequence=tcp://0.0.0.0:19332"
      - "-zmqpubrawblock=tcp://0.0.0.0:19333"

  addrindexrs-testnet:
    <<: *addrindexrs-common
    profiles:
      - testnet
    links:
      - bitcoind-testnet
    ports:
      - "18432:18432"
    command:
      - "--network=testnet"
      - "--indexer-rpc-host=0.0.0.0"
      - "--daemon-rpc-host=bitcoind-testnet"
      - "--cookie=rpc:rpc"
      - "-vvv"
      - "--db-dir=/data/"

  counterparty-core-testnet:
    <<: *counterparty-common
    profiles:
      - testnet
    links:
      - bitcoind-testnet
      - addrindexrs-testnet
    ports:
      - "14000:14000"                                      # API v2
      - "14100:14100"                                      # API v1
    command:
      - start
      - "--testnet"
      - "--backend-connect=bitcoind-testnet"
      - "--indexd-connect=addrindexrs-testnet"
      - "--rpc-host=0.0.0.0"
      - "--api-host=0.0.0.0"
      - "--catch-up=bootstrap"
      #- "--verbose"

volumes: 
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${COUNTERPARTY_DOCKER_DATA:-${XDG_DATA_HOME:-~/.local/share}}/counterparty-docker-data
