blueprint: apiary.apib
endpoint: http://127.0.0.1:4200
loglevel: error
only:
- Blocks > Get Blocks > Get Blocks
- Blocks > Get Block > Get Block
- Blocks > Get Transactions By Block > Get Transactions By Block
- Blocks > Get Events By Block > Get Events By Block
- Blocks > Get Event Counts By Block > Get Event Counts By Block
- Blocks > Get Events By Block And Event > Get Events By Block And Event
- Blocks > Get Credits By Block > Get Credits By Block
- Blocks > Get Debits By Block > Get Debits By Block
- Blocks > Get Expirations > Get Expirations
- Blocks > Get Cancels > Get Cancels
- Blocks > Get Destructions > Get Destructions
- Blocks > Get Issuances By Block > Get Issuances By Block
- Blocks > Get Sends By Block > Get Sends By Block
- Blocks > Get Dispenses By Block > Get Dispenses By Block
- Blocks > Get Sweeps By Block > Get Sweeps By Block
- Transactions > Info > Info
- Transactions > Unpack > Unpack
- Transactions > Get Transaction By Hash > Get Transaction By Hash
- Addresses > Get Address Balances > Get Address Balances
- Addresses > Get Balance By Address And Asset > Get Balance By Address And Asset
- Addresses > Get Credits By Address > Get Credits By Address
- Addresses > Get Debits By Address > Get Debits By Address
- Addresses > Get Bet By Feed > Get Bet By Feed
- Addresses > Get Broadcasts By Source > Get Broadcasts By Source
- Addresses > Get Burns By Address > Get Burns By Address
- Addresses > Get Send By Address > Get Send By Address
- Addresses > Get Receive By Address > Get Receive By Address
- Addresses > Get Send By Address And Asset > Get Send By Address And Asset
- Addresses > Get Receive By Address And Asset > Get Receive By Address And Asset
- Addresses > Get Dispensers By Address > Get Dispensers By Address
- Addresses > Get Dispensers By Address And Asset > Get Dispensers By Address And
  Asset
- Addresses > Get Sweeps By Address > Get Sweeps By Address
- Assets > Get Valid Assets > Get Valid Assets
- Assets > Get Asset Info > Get Asset Info
- Assets > Get Asset Balances > Get Asset Balances
- Assets > Get Balance By Address And Asset > Get Balance By Address And Asset
- Assets > Get Orders By Asset > Get Orders By Asset
- Assets > Get Credits By Asset > Get Credits By Asset
- Assets > Get Debits By Asset > Get Debits By Asset
- Assets > Get Dividends > Get Dividends
- Assets > Get Issuances By Asset > Get Issuances By Asset
- Assets > Get Sends By Asset > Get Sends By Asset
- Assets > Get Dispensers By Asset > Get Dispensers By Asset
- Assets > Get Dispensers By Address And Asset > Get Dispensers By Address And Asset
- Assets > Get Asset Holders > Get Asset Holders
- Orders > Get Order > Get Order
- Orders > Get Order Matches By Order > Get Order Matches By Order
- Orders > Get BTCPays By Order > Get BTCPays By Order
- Orders > Get Orders By Two Assets > Get Orders By Two Assets
- Bets > Get Bet > Get Bet
- Bets > Get Bet Matches By Bet > Get Bet Matches By Bet
- Bets > Get Resolutions By Bet > Get Resolutions By Bet
- Burns > Get All Burns > Get All Burns
- Dispensers > Get Dispenser Info By Hash > Get Dispenser Info By Hash
- Dispensers > Get Dispenses By Dispenser > Get Dispenses By Dispenser
- Events > Get All Events > Get All Events
- Events > Get Event By Index > Get Event By Index
- Events > Get All Events Counts > Get All Events Counts
- Events > Get Events By Name > Get Events By Name
- Z-pages > Check Server Health > Check Server Health
- V1 > Redirect To Api V1 > Redirect To Api V1
- V1 > Redirect To Api V1 > Redirect To Api V1
- V1 > Redirect To Api V1 > Redirect To Api V1
- V1 > Redirect To Api V1 > Redirect To Api V1
- V1 > Redirect To Api V1 > Redirect To Api V1
path: []
user: api:api
