


line-length = 100


[lint]
select = [
    "E4", # pycode style
    "E7",
    "E9",
    "F", # pyflakes
    # "S",  # flake8-bandit
    # "B",  # flake8-bugbear
    "I", # isort
    # "PLC",  # pylint conventions
    # "PLE", # pylint error
    # "PLE", # pylint refactor
    # "PLW" # pylint warning
]
ignore = [
  "E501" # line too long
]
