SCENARIO = [
    {
        "title": "Create numeric sub asset fairminter",
        "transaction": "fairminter",
        "source": "$ADDRESS_1",
        "params": {
            "asset": "SUBMYASSETA",
            "asset_parent": "MYASSETA",
            "price": 1,
            "quantity_by_price": 5,
        },
        "controls": [
            {
                "url": "blocks/$BLOCK_INDEX/events?event_name=ASSET_ISSUANCE,ASSET_CREATION,NEW_FAIRMINTER",
                "result": [
                    {
                        "event": "ASSET_ISSUANCE",
                        "event_index": "$EVENT_INDEX_5",
                        "params": {
                            "asset": "A95428958968845068",
                            "asset_events": "open_fairminter",
                            "asset_longname": "MYASSETA.SUBMYASSETA",
                            "block_index": "$BLOCK_INDEX",
                            "call_date": 0,
                            "call_price": 0,
                            "callable": False,
                            "description": "",
                            "divisible": True,
                            "fair_minting": True,
                            "fee_paid": 0,
                            "issuer": "$ADDRESS_1",
                            "locked": False,
                            "quantity": 0,
                            "reset": False,
                            "source": "$ADDRESS_1",
                            "status": "valid",
                            "transfer": False,
                            "tx_hash": "$TX_HASH",
                            "tx_index": 42,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "ASSET_CREATION",
                        "event_index": "$EVENT_INDEX_4",
                        "params": {
                            "asset_id": "95428958968845068",
                            "asset_longname": "MYASSETA.SUBMYASSETA",
                            "asset_name": "A95428958968845068",
                            "block_index": "$BLOCK_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "NEW_FAIRMINTER",
                        "event_index": "$EVENT_INDEX_3",
                        "params": {
                            "asset": "A95428958968845068",
                            "asset_longname": "MYASSETA.SUBMYASSETA",
                            "asset_parent": "MYASSETA",
                            "block_index": "$BLOCK_INDEX",
                            "burn_payment": False,
                            "description": "",
                            "divisible": True,
                            "end_block": 0,
                            "hard_cap": 0,
                            "lock_description": False,
                            "lock_quantity": False,
                            "max_mint_per_tx": 0,
                            "minted_asset_commission_int": 0,
                            "pre_minted": False,
                            "premint_quantity": 0,
                            "price": 1,
                            "quantity_by_price": 5,
                            "soft_cap": 0,
                            "soft_cap_deadline_block": 0,
                            "source": "$ADDRESS_1",
                            "start_block": 0,
                            "status": "open",
                            "tx_hash": "$TX_HASH",
                            "tx_index": 42,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            },
        ],
    },
]
