SCENARIO = [
    {
        "title": "Send XCP",
        "transaction": "send",
        "source": "$ADDRESS_3",
        "params": {
            "asset": "XCP",
            "quantity": 10000,
            "destination": "$ADDRESS_4",
        },
        "set_variables": {
            "SEND_1_HASH": "$TX_HASH",
        },
        "controls": [
            {
                "url": "blocks/181/events?event_name=ENHANCED_SEND,CREDIT,DEBIT",
                "result": [
                    {
                        "event": "ENHANCED_SEND",
                        "event_index": 444,
                        "params": {
                            "asset": "XCP",
                            "block_index": 181,
                            "destination": "$ADDRESS_4",
                            "memo": None,
                            "quantity": 10000,
                            "source": "$ADDRESS_3",
                            "status": "valid",
                            "tx_hash": "$TX_HASH",
                            "tx_index": 47,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": 443,
                        "params": {
                            "address": "$ADDRESS_4",
                            "asset": "XCP",
                            "block_index": 181,
                            "calling_function": "send",
                            "event": "$TX_HASH",
                            "quantity": 10000,
                            "tx_index": 47,
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": 442,
                        "params": {
                            "action": "send",
                            "address": "$ADDRESS_3",
                            "asset": "XCP",
                            "block_index": 181,
                            "event": "$TX_HASH",
                            "quantity": 10000,
                            "tx_index": 47,
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            },
        ],
    },
    {
        "title": "Send MPMA",
        "transaction": "mpma",
        "source": "$ADDRESS_1",
        "params": {
            "assets": "XCP,MYASSETA,MYASSETA",
            "quantities": "10,10,10",
            "destinations": "$ADDRESS_2,$ADDRESS_3,$ADDRESS_4",
        },
        "set_variables": {
            "SEND_2_HASH": "$TX_HASH",
        },
        "controls": [
            {
                "url": "blocks/182/events?event_name=MPMA_SEND,CREDIT,DEBIT",
                "result": [
                    {
                        "event": "MPMA_SEND",
                        "event_index": 456,
                        "params": {
                            "asset": "XCP",
                            "block_index": 182,
                            "destination": "$ADDRESS_2",
                            "memo": None,
                            "msg_index": 2,
                            "quantity": 10,
                            "source": "$ADDRESS_1",
                            "status": "valid",
                            "tx_hash": "$TX_HASH",
                            "tx_index": 48,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "MPMA_SEND",
                        "event_index": 455,
                        "params": {
                            "asset": "MYASSETA",
                            "block_index": 182,
                            "destination": "$ADDRESS_4",
                            "memo": None,
                            "msg_index": 1,
                            "quantity": 10,
                            "source": "$ADDRESS_1",
                            "status": "valid",
                            "tx_hash": "$TX_HASH",
                            "tx_index": 48,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "MPMA_SEND",
                        "event_index": 454,
                        "params": {
                            "asset": "MYASSETA",
                            "block_index": 182,
                            "destination": "$ADDRESS_3",
                            "memo": None,
                            "msg_index": 0,
                            "quantity": 10,
                            "source": "$ADDRESS_1",
                            "status": "valid",
                            "tx_hash": "$TX_HASH",
                            "tx_index": 48,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": 453,
                        "params": {
                            "action": "mpma send",
                            "address": "$ADDRESS_1",
                            "asset": "XCP",
                            "block_index": 182,
                            "event": "$TX_HASH",
                            "quantity": 10,
                            "tx_index": 48,
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": 452,
                        "params": {
                            "action": "mpma send",
                            "address": "$ADDRESS_1",
                            "asset": "MYASSETA",
                            "block_index": 182,
                            "event": "$TX_HASH",
                            "quantity": 20,
                            "tx_index": 48,
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": 451,
                        "params": {
                            "address": "$ADDRESS_2",
                            "asset": "XCP",
                            "block_index": 182,
                            "calling_function": "mpma send",
                            "event": "$TX_HASH",
                            "quantity": 10,
                            "tx_index": 48,
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": 450,
                        "params": {
                            "address": "$ADDRESS_4",
                            "asset": "MYASSETA",
                            "block_index": 182,
                            "calling_function": "mpma send",
                            "event": "$TX_HASH",
                            "quantity": 10,
                            "tx_index": 48,
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": 449,
                        "params": {
                            "address": "$ADDRESS_3",
                            "asset": "MYASSETA",
                            "block_index": 182,
                            "calling_function": "mpma send",
                            "event": "$TX_HASH",
                            "quantity": 10,
                            "tx_index": 48,
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            },
        ],
    },
]
