SCENARIO = [
    {
        "title": "Open Sell XCP for BTC order 3",
        "transaction": "order",
        "source": "$ADDRESS_1",
        "params": {
            "give_asset": "XCP",
            "give_quantity": 1000,
            "get_asset": "BTC",
            "get_quantity": 1000,
            "expiration": 21,
            "fee_required": 0,
        },
        "set_variables": {
            "ORDER_6_HASH": "$TX_HASH",
        },
        "controls": [
            {
                "url": "blocks/184/events?event_name=OPEN_ORDER,DEBIT,CREDIT",
                "result": [
                    {
                        "event": "OPEN_ORDER",
                        "event_index": 474,
                        "params": {
                            "block_index": 184,
                            "expiration": 21,
                            "expire_index": 205,
                            "fee_provided": 22902,
                            "fee_provided_remaining": 22902,
                            "fee_required": 0,
                            "fee_required_remaining": 0,
                            "get_asset": "BTC",
                            "get_quantity": 1000,
                            "get_remaining": 1000,
                            "give_asset": "XCP",
                            "give_quantity": 1000,
                            "give_remaining": 1000,
                            "source": "$ADDRESS_1",
                            "status": "open",
                            "tx_hash": "$TX_HASH",
                            "tx_index": 50,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": 473,
                        "params": {
                            "action": "open order",
                            "address": "$ADDRESS_1",
                            "asset": "XCP",
                            "block_index": 184,
                            "event": "$TX_HASH",
                            "quantity": 1000,
                            "tx_index": 50,
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            },
        ],
    },
    {
        "title": "Cancel order 3",
        "transaction": "cancel",
        "source": "$ADDRESS_1",
        "params": {
            "offer_hash": "$ORDER_6_HASH",
        },
        "controls": [
            {
                "url": "blocks/185/events?event_name=CANCEL_ORDER,CREDIT",
                "result": [
                    {
                        "event": "CANCEL_ORDER",
                        "event_index": 481,
                        "params": {
                            "block_index": 185,
                            "offer_hash": "$ORDER_6_HASH",
                            "source": "$ADDRESS_1",
                            "status": "valid",
                            "tx_hash": "$TX_HASH",
                            "tx_index": 51,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": 480,
                        "params": {
                            "address": "$ADDRESS_1",
                            "asset": "XCP",
                            "block_index": 185,
                            "calling_function": "cancel order",
                            "event": "$ORDER_6_HASH",
                            "quantity": 1000,
                            "tx_index": 51,
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            },
        ],
    },
    {
        "title": "Open Sell XCP for BTC order 4",
        "transaction": "order",
        "source": "$ADDRESS_1",
        "params": {
            "give_asset": "XCP",
            "give_quantity": 1000,
            "get_asset": "BTC",
            "get_quantity": 1000,
            "expiration": 21,
            "fee_required": 0,
        },
        "set_variables": {
            "ORDER_7_HASH": "$TX_HASH",
        },
        "controls": [
            {
                "url": "blocks/186/events?event_name=OPEN_ORDER,DEBIT,CREDIT",
                "result": [
                    {
                        "event": "OPEN_ORDER",
                        "event_index": 487,
                        "params": {
                            "block_index": 186,
                            "expiration": 21,
                            "expire_index": 207,
                            "fee_provided": 24931,
                            "fee_provided_remaining": 24931,
                            "fee_required": 0,
                            "fee_required_remaining": 0,
                            "get_asset": "BTC",
                            "get_quantity": 1000,
                            "get_remaining": 1000,
                            "give_asset": "XCP",
                            "give_quantity": 1000,
                            "give_remaining": 1000,
                            "source": "$ADDRESS_1",
                            "status": "open",
                            "tx_hash": "$TX_HASH",
                            "tx_index": 52,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": 486,
                        "params": {
                            "action": "open order",
                            "address": "$ADDRESS_1",
                            "asset": "XCP",
                            "block_index": 186,
                            "event": "$TX_HASH",
                            "quantity": 1000,
                            "tx_index": 52,
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            },
        ],
    },
]
