SCENARIO = [
    {
        "title": "Create asset MYASSETA",
        "transaction": "issuance",
        "source": "$ADDRESS_1",
        "params": {
            "asset": "MYASSETA",
            "quantity": 1000 * 10**8,
            "divisible": True,
            "description": "My super asset A",
        },
        "controls": [
            {
                "url": "blocks/134/events?event_name=CREDIT,ASSET_ISSUANCE,ASSET_CREATION,DEBIT",
                "result": [
                    {
                        "event": "CREDIT",
                        "event_index": 186,
                        "params": {
                            "address": "$ADDRESS_1",
                            "asset": "MYASSETA",
                            "block_index": 134,
                            "calling_function": "issuance",
                            "event": "$TX_HASH",
                            "quantity": 100000000000,
                            "tx_index": 21,
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "ASSET_ISSUANCE",
                        "event_index": 185,
                        "params": {
                            "asset": "MYASSETA",
                            "asset_longname": None,
                            "asset_events": "",
                            "block_index": 134,
                            "call_date": 0,
                            "call_price": 0.0,
                            "callable": False,
                            "description": "My super asset A",
                            "description_locked": False,
                            "divisible": True,
                            "fee_paid": 50000000,
                            "issuer": "$ADDRESS_1",
                            "locked": False,
                            "quantity": 100000000000,
                            "reset": False,
                            "source": "$ADDRESS_1",
                            "status": "valid",
                            "transfer": False,
                            "tx_hash": "$TX_HASH",
                            "tx_index": 21,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "ASSET_CREATION",
                        "event_index": 184,
                        "params": {
                            "asset_id": "103804245870",
                            "asset_longname": None,
                            "asset_name": "MYASSETA",
                            "block_index": 134,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": 183,
                        "params": {
                            "action": "issuance fee",
                            "address": "$ADDRESS_1",
                            "asset": "XCP",
                            "block_index": 134,
                            "event": "$TX_HASH",
                            "quantity": 50000000,
                            "tx_index": 21,
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            }
        ],
    },
    {
        "title": "Attach asset to UTXO",
        "transaction": "attach",
        "source": "$ADDRESS_1",
        "params": {
            "asset": "MYASSETA",
            "quantity": 10 * 10**8,
            "destination": "$FAIRMINTB_WITH_ADDRESS_3_TX_HASH:1",
        },
        "controls": [
            {
                "url": "blocks/135/events?event_name=ATTACH_TO_UTXO,INCREMENT_TRANSACTION_COUNT,CREDIT,DEBIT",
                "result": [
                    {
                        "event": "ATTACH_TO_UTXO",
                        "event_index": 194,
                        "params": {
                            "asset": "MYASSETA",
                            "block_index": 135,
                            "destination": "$FAIRMINTB_WITH_ADDRESS_3_TX_HASH:1",
                            "fee_paid": 0,
                            "msg_index": 0,
                            "quantity": 1000000000,
                            "source": "$ADDRESS_1",
                            "status": "valid",
                            "tx_hash": "$TX_HASH",
                            "tx_index": 22,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "INCREMENT_TRANSACTION_COUNT",
                        "event_index": 193,
                        "params": {
                            "block_index": 135,
                            "count": 1,
                            "transaction_id": 100,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": 192,
                        "params": {
                            "address": None,
                            "asset": "MYASSETA",
                            "block_index": 135,
                            "calling_function": "attach to utxo",
                            "event": "$TX_HASH",
                            "quantity": 1000000000,
                            "tx_index": 22,
                            "utxo": "$FAIRMINTB_WITH_ADDRESS_3_TX_HASH:1",
                            "utxo_address": "$ADDRESS_3",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": 191,
                        "params": {
                            "action": "attach to utxo",
                            "address": "$ADDRESS_1",
                            "asset": "MYASSETA",
                            "block_index": 135,
                            "event": "$TX_HASH",
                            "quantity": 1000000000,
                            "tx_index": 22,
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            }
        ],
    },
    {
        "title": "Move assets from UTXO to UTXO",
        "transaction": "movetoutxo",
        "source": "$FAIRMINTB_WITH_ADDRESS_3_TX_HASH:1",
        "params": {
            "destination": "$ADDRESS_4",
        },
        "set_variables": {
            "UTXO_MOVE_1_TX_HASH": "$TX_HASH",
        },
        "controls": [
            {
                "url": "blocks/136/events?event_name=UTXO_MOVE,CREDIT,DEBIT,NEW_TRANSACTION",
                "result": [
                    {
                        "event": "UTXO_MOVE",
                        "event_index": 201,
                        "params": {
                            "asset": "MYASSETA",
                            "block_index": 136,
                            "destination": "$TX_HASH:0",
                            "msg_index": 0,
                            "quantity": 1000000000,
                            "source": "$FAIRMINTB_WITH_ADDRESS_3_TX_HASH:1",
                            "status": "valid",
                            "tx_hash": "$TX_HASH",
                            "tx_index": 23,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": 200,
                        "params": {
                            "address": None,
                            "asset": "MYASSETA",
                            "block_index": 136,
                            "calling_function": "utxo move",
                            "event": "$TX_HASH",
                            "quantity": 1000000000,
                            "tx_index": 23,
                            "utxo": "$TX_HASH:0",
                            "utxo_address": "$ADDRESS_4",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": 199,
                        "params": {
                            "action": "utxo move",
                            "address": None,
                            "asset": "MYASSETA",
                            "block_index": 136,
                            "event": "$TX_HASH",
                            "quantity": 1000000000,
                            "tx_index": 23,
                            "utxo": "$FAIRMINTB_WITH_ADDRESS_3_TX_HASH:1",
                            "utxo_address": "$ADDRESS_3",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "NEW_TRANSACTION",
                        "event_index": 198,
                        "params": {
                            "block_hash": "$BLOCK_HASH",
                            "block_index": 136,
                            "block_time": "$BLOCK_TIME",
                            "btc_amount": None,
                            "data": None,
                            "destination": None,
                            "fee": None,
                            "source": "",
                            "tx_hash": "$TX_HASH",
                            "tx_index": 23,
                            "utxos_info": "$FAIRMINTB_WITH_ADDRESS_3_TX_HASH:1 $TX_HASH:0",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            }
        ],
    },
    {
        "title": "Detach assets from UTXO",
        "transaction": "detach",
        "source": "$UTXO_MOVE_1_TX_HASH:0",
        "params": {
            "destination": "$ADDRESS_5",
            "asset": "MYASSETA",
            "quantity": 5 * 10**8,
            "exclude_utxos": "$UTXO_MOVE_1_TX_HASH:0",
        },
        "controls": [
            {
                "url": "blocks/137/events?event_name=DETACH_FROM_UTXO,INCREMENT_TRANSACTION_COUNT,CREDIT,DEBIT",
                "result": [
                    {
                        "event": "DETACH_FROM_UTXO",
                        "event_index": 207,
                        "params": {
                            "asset": "MYASSETA",
                            "block_index": 137,
                            "destination": "$ADDRESS_5",
                            "fee_paid": 0,
                            "msg_index": 0,
                            "quantity": 500000000,
                            "source": "$UTXO_MOVE_1_TX_HASH:0",
                            "status": "valid",
                            "tx_hash": "$TX_HASH",
                            "tx_index": 24,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": 206,
                        "params": {
                            "address": "$ADDRESS_5",
                            "asset": "MYASSETA",
                            "block_index": 137,
                            "calling_function": "detach from utxo",
                            "event": "$TX_HASH",
                            "quantity": 500000000,
                            "tx_index": 24,
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": 205,
                        "params": {
                            "action": "detach from utxo",
                            "address": None,
                            "asset": "MYASSETA",
                            "block_index": 137,
                            "event": "$TX_HASH",
                            "quantity": 500000000,
                            "tx_index": 24,
                            "utxo": "$UTXO_MOVE_1_TX_HASH:0",
                            "utxo_address": "$ADDRESS_4",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            }
        ],
    },
    {
        "title": "Attach asset to new UTXO",
        "transaction": "attach",
        "source": "$ADDRESS_1",
        "params": {
            "asset": "MYASSETA",
            "quantity": 10 * 10**8,
        },
        "set_variables": {
            "UTXO_ATTACH_2_TX_HASH": "$TX_HASH",
        },
        "controls": [
            {
                "url": "blocks/138/events?event_name=ATTACH_TO_UTXO,INCREMENT_TRANSACTION_COUNT,CREDIT,DEBIT",
                "result": [
                    {
                        "event": "ATTACH_TO_UTXO",
                        "event_index": 215,
                        "params": {
                            "asset": "MYASSETA",
                            "block_index": 138,
                            "destination": "$TX_HASH:1",
                            "fee_paid": 0,
                            "msg_index": 0,
                            "quantity": 1000000000,
                            "source": "$ADDRESS_1",
                            "status": "valid",
                            "tx_hash": "$TX_HASH",
                            "tx_index": 25,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "INCREMENT_TRANSACTION_COUNT",
                        "event_index": 214,
                        "params": {
                            "block_index": 138,
                            "count": 2,
                            "transaction_id": 100,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": 213,
                        "params": {
                            "address": None,
                            "asset": "MYASSETA",
                            "block_index": 138,
                            "calling_function": "attach to utxo",
                            "event": "$TX_HASH",
                            "quantity": 1000000000,
                            "tx_index": 25,
                            "utxo": "$TX_HASH:1",
                            "utxo_address": "$ADDRESS_1",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": 212,
                        "params": {
                            "action": "attach to utxo",
                            "address": "$ADDRESS_1",
                            "asset": "MYASSETA",
                            "block_index": 138,
                            "event": "$TX_HASH",
                            "quantity": 1000000000,
                            "tx_index": 25,
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            }
        ],
    },
    {
        "title": "Move assets from 2 UTXOs to UTXO",
        "transaction": "movetoutxo",
        "source": "$UTXO_MOVE_1_TX_HASH:0",
        "params": {
            "destination": "$ADDRESS_6",
            "more_utxos": "$UTXO_ATTACH_2_TX_HASH:1",
        },
        "set_variables": {
            "UTXO_MOVE_2_TX_HASH": "$TX_HASH",
        },
        "controls": [
            {
                "url": "blocks/139/events?event_name=UTXO_MOVE,CREDIT,DEBIT,NEW_TRANSACTION",
                "result": [
                    {
                        "event": "UTXO_MOVE",
                        "event_index": 225,
                        "params": {
                            "asset": "MYASSETA",
                            "block_index": 139,
                            "destination": "$TX_HASH:0",
                            "msg_index": 1,
                            "quantity": 1000000000,
                            "source": "$UTXO_ATTACH_2_TX_HASH:1",
                            "status": "valid",
                            "tx_hash": "$TX_HASH",
                            "tx_index": 26,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": 224,
                        "params": {
                            "address": None,
                            "asset": "MYASSETA",
                            "block_index": 139,
                            "calling_function": "utxo move",
                            "event": "$TX_HASH",
                            "quantity": 1000000000,
                            "tx_index": 26,
                            "utxo": "$TX_HASH:0",
                            "utxo_address": "$ADDRESS_6",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": 223,
                        "params": {
                            "action": "utxo move",
                            "address": None,
                            "asset": "MYASSETA",
                            "block_index": 139,
                            "event": "$TX_HASH",
                            "quantity": 1000000000,
                            "tx_index": 26,
                            "utxo": "$UTXO_ATTACH_2_TX_HASH:1",
                            "utxo_address": "$ADDRESS_1",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "UTXO_MOVE",
                        "event_index": 222,
                        "params": {
                            "asset": "MYASSETA",
                            "block_index": 139,
                            "destination": "$TX_HASH:0",
                            "msg_index": 0,
                            "quantity": 500000000,
                            "source": "$UTXO_MOVE_1_TX_HASH:0",
                            "status": "valid",
                            "tx_hash": "$TX_HASH",
                            "tx_index": 26,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": 221,
                        "params": {
                            "address": None,
                            "asset": "MYASSETA",
                            "block_index": 139,
                            "calling_function": "utxo move",
                            "event": "$TX_HASH",
                            "quantity": 500000000,
                            "tx_index": 26,
                            "utxo": "$TX_HASH:0",
                            "utxo_address": "$ADDRESS_6",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": 220,
                        "params": {
                            "action": "utxo move",
                            "address": None,
                            "asset": "MYASSETA",
                            "block_index": 139,
                            "event": "$TX_HASH",
                            "quantity": 500000000,
                            "tx_index": 26,
                            "utxo": "$UTXO_MOVE_1_TX_HASH:0",
                            "utxo_address": "$ADDRESS_4",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "NEW_TRANSACTION",
                        "event_index": 219,
                        "params": {
                            "block_hash": "$BLOCK_HASH",
                            "block_index": 139,
                            "block_time": "$BLOCK_TIME",
                            "btc_amount": None,
                            "data": None,
                            "destination": None,
                            "fee": None,
                            "source": "",
                            "tx_hash": "$TX_HASH",
                            "tx_index": 26,
                            "utxos_info": "$UTXO_MOVE_1_TX_HASH:0 $UTXO_ATTACH_2_TX_HASH:1 $TX_HASH:0",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            },
            {
                "url": "assets/MYASSETA/balances",
                "result": [
                    {
                        "address": "$ADDRESS_1",
                        "asset": "MYASSETA",
                        "quantity": 98000000000,
                        "utxo": None,
                        "utxo_address": None,
                    },
                    {
                        "address": "$ADDRESS_5",
                        "asset": "MYASSETA",
                        "quantity": 500000000,
                        "utxo": None,
                        "utxo_address": None,
                    },
                    {
                        "address": None,
                        "asset": "MYASSETA",
                        "quantity": 1500000000,
                        "utxo": "$TX_HASH:0",
                        "utxo_address": "$ADDRESS_6",
                    },
                ],
            },
            {
                "url": "addresses/$ADDRESS_6/balances",
                "result": [
                    {
                        "address": None,
                        "asset": "MYASSETA",
                        "quantity": 1500000000,
                        "utxo": "$TX_HASH:0",
                        "utxo_address": "$ADDRESS_6",
                    },
                    {
                        "address": "$ADDRESS_6",
                        "asset": "XCP",
                        "quantity": 74999997333,
                        "utxo": None,
                        "utxo_address": None,
                    },
                ],
            },
            {
                "url": "addresses/balances?addresses=$ADDRESS_6,$ADDRESS_1,$ADDRESS_5",
                "result": [
                    {
                        "addresses": [
                            {
                                "address": "$ADDRESS_1",
                                "quantity": 98000000000,
                                "utxo": None,
                                "utxo_address": None,
                            },
                            {
                                "address": "$ADDRESS_5",
                                "quantity": 500000000,
                                "utxo": None,
                                "utxo_address": None,
                            },
                            {
                                "address": None,
                                "quantity": 1500000000,
                                "utxo": "$TX_HASH:0",
                                "utxo_address": "$ADDRESS_6",
                            },
                        ],
                        "asset": "MYASSETA",
                        "total": 100000000000,
                    },
                    {
                        "addresses": [
                            {
                                "address": "$ADDRESS_1",
                                "quantity": 84849988167,
                                "utxo": None,
                                "utxo_address": None,
                            },
                            {
                                "address": "$ADDRESS_5",
                                "quantity": 74999997500,
                                "utxo": None,
                                "utxo_address": None,
                            },
                            {
                                "address": "$ADDRESS_6",
                                "quantity": 74999997333,
                                "utxo": None,
                                "utxo_address": None,
                            },
                        ],
                        "asset": "XCP",
                        "total": 234849983000,
                    },
                ],
            },
            {
                "url": "addresses/$ADDRESS_6/balances/MYASSETA",
                "result": {
                    "address": None,
                    "asset": "MYASSETA",
                    "quantity": 1500000000,
                    "utxo": "$TX_HASH:0",
                    "utxo_address": "$ADDRESS_6",
                },
            },
        ],
    },
    {
        "title": "Test divident to UTXO",
        "transaction": "dividend",
        "source": "$ADDRESS_1",
        "params": {
            "asset": "MYASSETA",
            "quantity_per_unit": 1 * 10**8,
            "dividend_asset": "XCP",
        },
        "set_variables": {
            "DIVIDEND_1_TX_HASH": "$TX_HASH",
        },
        "controls": [
            {
                "url": "blocks/140/events?event_name=ASSET_DIVIDEND,CREDIT,DEBIT",
                "result": [
                    {
                        "event": "ASSET_DIVIDEND",
                        "event_index": 233,
                        "params": {
                            "asset": "MYASSETA",
                            "block_index": 140,
                            "dividend_asset": "XCP",
                            "fee_paid": 40000,
                            "quantity_per_unit": 100000000,
                            "source": "$ADDRESS_1",
                            "status": "valid",
                            "tx_hash": "$TX_HASH",
                            "tx_index": 27,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": 232,
                        "params": {
                            "address": None,
                            "asset": "XCP",
                            "block_index": 140,
                            "calling_function": "dividend",
                            "event": "$TX_HASH",
                            "quantity": 1500000000,
                            "tx_index": 27,
                            "utxo": "$UTXO_MOVE_2_TX_HASH:0",
                            "utxo_address": "$ADDRESS_6",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": 231,
                        "params": {
                            "address": "$ADDRESS_5",
                            "asset": "XCP",
                            "block_index": 140,
                            "calling_function": "dividend",
                            "event": "$TX_HASH",
                            "quantity": 500000000,
                            "tx_index": 27,
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": 230,
                        "params": {
                            "action": "dividend fee",
                            "address": "$ADDRESS_1",
                            "asset": "XCP",
                            "block_index": 140,
                            "event": "$TX_HASH",
                            "quantity": 40000,
                            "tx_index": 27,
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": 229,
                        "params": {
                            "action": "dividend",
                            "address": "$ADDRESS_1",
                            "asset": "XCP",
                            "block_index": 140,
                            "event": "$TX_HASH",
                            "quantity": 2000000000,
                            "tx_index": 27,
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            }
        ],
    },
]
