SCENARIO = [
    {
        "title": "Send XCP",
        "transaction": "send",
        "source": "$ADDRESS_3",
        "params": {
            "asset": "XCP",
            "quantity": 10000,
            "destination": "$ADDRESS_4",
        },
        "set_variables": {
            "SEND_1_HASH": "$TX_HASH",
        },
        "controls": [
            {
                "url": "blocks/$BLOCK_INDEX/events?event_name=ENHANCED_SEND,CREDIT,DEBIT",
                "result": [
                    {
                        "event": "ENHANCED_SEND",
                        "event_index": "$EVENT_INDEX_5",
                        "params": {
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "destination": "$ADDRESS_4",
                            "memo": None,
                            "quantity": 10000,
                            "source": "$ADDRESS_3",
                            "status": "valid",
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": "$EVENT_INDEX_4",
                        "params": {
                            "address": "$ADDRESS_4",
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "calling_function": "send",
                            "event": "$TX_HASH",
                            "quantity": 10000,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": "$EVENT_INDEX_3",
                        "params": {
                            "action": "send",
                            "address": "$ADDRESS_3",
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "event": "$TX_HASH",
                            "quantity": 10000,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            },
        ],
    },
    {
        "title": "Send MPMA",
        "transaction": "mpma",
        "source": "$ADDRESS_1",
        "params": {
            "assets": "XCP,MYASSETA,MYASSETA",
            "quantities": "10,10,10",
            "destinations": "$ADDRESS_2,$ADDRESS_3,$ADDRESS_4",
        },
        "set_variables": {
            "SEND_2_HASH": "$TX_HASH",
        },
        "controls": [
            {
                "url": "blocks/$BLOCK_INDEX/events?event_name=MPMA_SEND,CREDIT,DEBIT",
                "result": [
                    {
                        "event": "MPMA_SEND",
                        "event_index": "$EVENT_INDEX_10",
                        "params": {
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "destination": "$ADDRESS_2",
                            "memo": None,
                            "msg_index": 2,
                            "quantity": 10,
                            "source": "$ADDRESS_1",
                            "status": "valid",
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "MPMA_SEND",
                        "event_index": "$EVENT_INDEX_9",
                        "params": {
                            "asset": "MYASSETA",
                            "block_index": "$BLOCK_INDEX",
                            "destination": "$ADDRESS_4",
                            "memo": None,
                            "msg_index": 1,
                            "quantity": 10,
                            "source": "$ADDRESS_1",
                            "status": "valid",
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "MPMA_SEND",
                        "event_index": "$EVENT_INDEX_8",
                        "params": {
                            "asset": "MYASSETA",
                            "block_index": "$BLOCK_INDEX",
                            "destination": "$ADDRESS_3",
                            "memo": None,
                            "msg_index": 0,
                            "quantity": 10,
                            "source": "$ADDRESS_1",
                            "status": "valid",
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": "$EVENT_INDEX_7",
                        "params": {
                            "action": "mpma send",
                            "address": "$ADDRESS_1",
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "event": "$TX_HASH",
                            "quantity": 10,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": "$EVENT_INDEX_6",
                        "params": {
                            "action": "mpma send",
                            "address": "$ADDRESS_1",
                            "asset": "MYASSETA",
                            "block_index": "$BLOCK_INDEX",
                            "event": "$TX_HASH",
                            "quantity": 20,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": "$EVENT_INDEX_5",
                        "params": {
                            "address": "$ADDRESS_2",
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "calling_function": "mpma send",
                            "event": "$TX_HASH",
                            "quantity": 10,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": "$EVENT_INDEX_4",
                        "params": {
                            "address": "$ADDRESS_4",
                            "asset": "MYASSETA",
                            "block_index": "$BLOCK_INDEX",
                            "calling_function": "mpma send",
                            "event": "$TX_HASH",
                            "quantity": 10,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": "$EVENT_INDEX_3",
                        "params": {
                            "address": "$ADDRESS_3",
                            "asset": "MYASSETA",
                            "block_index": "$BLOCK_INDEX",
                            "calling_function": "mpma send",
                            "event": "$TX_HASH",
                            "quantity": 10,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            },
        ],
    },
]
