SCENARIO = [
    {
        "title": "Open Sell XCP for BTC order 3",
        "transaction": "order",
        "source": "$ADDRESS_1",
        "params": {
            "give_asset": "XCP",
            "give_quantity": 1000,
            "get_asset": "BTC",
            "get_quantity": 1000,
            "expiration": 21,
            "fee_required": 0,
        },
        "set_variables": {
            "ORDER_6_HASH": "$TX_HASH",
            "ORDER_6_EXPIRATION_BLOCK_INDEX": "$BLOCK_INDEX + 21",
        },
        "controls": [
            {
                "url": "blocks/$BLOCK_INDEX/events?event_name=OPEN_ORDER,DEBIT,CREDIT",
                "result": [
                    {
                        "event": "OPEN_ORDER",
                        "event_index": "$EVENT_INDEX_4",
                        "params": {
                            "block_index": "$BLOCK_INDEX",
                            "expiration": 21,
                            "expire_index": "$ORDER_6_EXPIRATION_BLOCK_INDEX",
                            "fee_provided": 22902,
                            "fee_provided_remaining": 22902,
                            "fee_required": 0,
                            "fee_required_remaining": 0,
                            "get_asset": "BTC",
                            "get_quantity": 1000,
                            "get_remaining": 1000,
                            "give_asset": "XCP",
                            "give_quantity": 1000,
                            "give_remaining": 1000,
                            "source": "$ADDRESS_1",
                            "status": "open",
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": "$EVENT_INDEX_3",
                        "params": {
                            "action": "open order",
                            "address": "$ADDRESS_1",
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "event": "$TX_HASH",
                            "quantity": 1000,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            },
        ],
    },
    {
        "title": "Cancel order 3",
        "transaction": "cancel",
        "source": "$ADDRESS_1",
        "params": {
            "offer_hash": "$ORDER_6_HASH",
        },
        "controls": [
            {
                "url": "blocks/$BLOCK_INDEX/events?event_name=CANCEL_ORDER,CREDIT,ORDER_UPDATE",
                "result": [
                    {
                        "event": "CANCEL_ORDER",
                        "event_index": "$EVENT_INDEX_5",
                        "params": {
                            "block_index": "$BLOCK_INDEX",
                            "offer_hash": "$ORDER_6_HASH",
                            "source": "$ADDRESS_1",
                            "status": "valid",
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": "$EVENT_INDEX_4",
                        "params": {
                            "address": "$ADDRESS_1",
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "calling_function": "cancel order",
                            "event": "$ORDER_6_HASH",
                            "quantity": 1000,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "ORDER_UPDATE",
                        "event_index": "$EVENT_INDEX_3",
                        "params": {"status": "cancelled", "tx_hash": "$ORDER_6_HASH"},
                        "tx_hash": "$TX_HASH",
                    },
                ],
            },
        ],
    },
    {
        "title": "Open Sell XCP for BTC order 4",
        "transaction": "order",
        "source": "$ADDRESS_1",
        "params": {
            "give_asset": "XCP",
            "give_quantity": 1000,
            "get_asset": "BTC",
            "get_quantity": 1000,
            "expiration": 21,
            "fee_required": 0,
        },
        "set_variables": {
            "ORDER_7_HASH": "$TX_HASH",
            "ORDER_7_EXPIRATION_BLOCK_INDEX": "$BLOCK_INDEX + 21",
        },
        "controls": [
            {
                "url": "blocks/$BLOCK_INDEX/events?event_name=OPEN_ORDER,DEBIT,CREDIT",
                "result": [
                    {
                        "event": "OPEN_ORDER",
                        "event_index": "$EVENT_INDEX_4",
                        "params": {
                            "block_index": "$BLOCK_INDEX",
                            "expiration": 21,
                            "expire_index": "$ORDER_7_EXPIRATION_BLOCK_INDEX",
                            "fee_provided": 24931,
                            "fee_provided_remaining": 24931,
                            "fee_required": 0,
                            "fee_required_remaining": 0,
                            "get_asset": "BTC",
                            "get_quantity": 1000,
                            "get_remaining": 1000,
                            "give_asset": "XCP",
                            "give_quantity": 1000,
                            "give_remaining": 1000,
                            "source": "$ADDRESS_1",
                            "status": "open",
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": "$EVENT_INDEX_3",
                        "params": {
                            "action": "open order",
                            "address": "$ADDRESS_1",
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "event": "$TX_HASH",
                            "quantity": 1000,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            },
        ],
    },
]
