SCENARIO = [
    {
        "title": "Create asset RESET",
        "transaction": "issuance",
        "source": "$ADDRESS_10",
        "params": {
            "asset": "RESET",
            "quantity": 12,
            "divisible": False,
            "exact_fee": 0,
        },
        "set_variables": {
            "CREATE_RESET_TX_HASH": "$TX_HASH",
            "CREATE_RESET_TX_INDEX": "$TX_INDEX",
        },
        "controls": [],
    },
    {
        "title": "reset asset RESET",
        "transaction": "issuance",
        "source": "$ADDRESS_10",
        "params": {
            "asset": "RESET",
            "quantity": int(12 * 10**8),
            "divisible": True,
            "reset": True,
            "exact_fee": 0,
        },
        "controls": [
            {
                "url": "blocks/$BLOCK_INDEX/events?event_name=CREDIT,RESET_ISSUANCE,ASSET_DESTRUCTION,DEBIT",
                "result": [
                    {
                        "event": "CREDIT",
                        "event_index": "$EVENT_INDEX_6",
                        "params": {
                            "address": "$ADDRESS_10",
                            "asset": "RESET",
                            "block_index": "$BLOCK_INDEX",
                            "calling_function": "reset issuance",
                            "event": "$TX_HASH",
                            "quantity": 1200000000,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "RESET_ISSUANCE",
                        "event_index": "$EVENT_INDEX_5",
                        "params": {
                            "asset": "RESET",
                            "asset_events": "reset",
                            "asset_longname": None,
                            "block_index": "$BLOCK_INDEX",
                            "call_date": 0,
                            "call_price": 0.0,
                            "callable": False,
                            "description": "",
                            "divisible": True,
                            "fee_paid": 0,
                            "issuer": "$ADDRESS_10",
                            "locked": False,
                            "quantity": 1200000000,
                            "reset": True,
                            "source": "$ADDRESS_10",
                            "status": "valid",
                            "transfer": False,
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "ASSET_DESTRUCTION",
                        "event_index": "$EVENT_INDEX_4",
                        "params": {
                            "asset": "RESET",
                            "block_index": "$BLOCK_INDEX",
                            "quantity": 12,
                            "source": "$ADDRESS_10",
                            "status": "valid",
                            "tag": "reset",
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": "$EVENT_INDEX_3",
                        "params": {
                            "action": "reset destroy",
                            "address": "$ADDRESS_10",
                            "asset": "RESET",
                            "block_index": "$BLOCK_INDEX",
                            "event": "$TX_HASH",
                            "quantity": 12,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            }
        ],
    },
]
