SCENARIO = [
    {
        "title": "Create asset LOCKDESC",
        "transaction": "issuance",
        "source": "$ADDRESS_9",
        "params": {
            "asset": "LOCKDESC",
            "quantity": 10 * 10**8,
            "divisible": True,
            "description": "My super asset LOCKDESC",
        },
        "controls": [],
    },
    {
        "title": "Lock description of LOCKDESC",
        "transaction": "issuance",
        "source": "$ADDRESS_9",
        "params": {
            "asset": "LOCKDESC",
            "quantity": 0,
            "description": "lock_description",
        },
        "controls": [],
    },
    {
        "title": "Create fairminter on LOCKDESC",
        "transaction": "fairminter",
        "source": "$ADDRESS_9",
        "params": {
            "asset": "LOCKDESC",
            "max_mint_per_tx": 10 * 10**8,
            "premint_quantity": 100 * 10**8,
            "minted_asset_commission": 0.2,
            "description": "My super fairminter",
        },
        "expected_error": ["Description of asset `LOCKDESC` is locked."],
    },
    {
        "title": "Create fairminter on LOCKDESC",
        "transaction": "fairminter",
        "source": "$ADDRESS_9",
        "params": {
            "asset": "LOCKDESC",
            "max_mint_per_tx": 11 * 10**8,
            "premint_quantity": 100 * 10**8,
            "minted_asset_commission": 0.2,
            "description": "My super asset LOCKDESC",
            "hard_cap": 120 * 10**8,  # 10 issuances, 100 premint, 10 for one mint
            "lock_quantity": True,
        },
        "set_variables": {
            "FAIRMINTER_LOCKDESC_HASH": "$TX_HASH",
        },
        "controls": [
            {
                "url": "blocks/$BLOCK_INDEX/events?event_name=NEW_FAIRMINTER,ASSET_ISSUANCE,CREDIT",
                "result": [
                    {
                        "event": "CREDIT",
                        "event_index": "$EVENT_INDEX_5",
                        "params": {
                            "address": "$ADDRESS_9",
                            "asset": "LOCKDESC",
                            "block_index": "$BLOCK_INDEX",
                            "calling_function": "premint",
                            "event": "$TX_HASH",
                            "quantity": 10000000000,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "ASSET_ISSUANCE",
                        "event_index": "$EVENT_INDEX_4",
                        "params": {
                            "asset": "LOCKDESC",
                            "asset_events": "open_fairminter",
                            "asset_longname": "",
                            "block_index": "$BLOCK_INDEX",
                            "call_date": 0,
                            "call_price": 0,
                            "callable": False,
                            "description": "My super asset LOCKDESC",
                            "divisible": True,
                            "fair_minting": True,
                            "fee_paid": 0,
                            "issuer": "$ADDRESS_9",
                            "locked": False,
                            "quantity": 10000000000,
                            "reset": False,
                            "source": "$ADDRESS_9",
                            "status": "valid",
                            "transfer": False,
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "NEW_FAIRMINTER",
                        "event_index": "$EVENT_INDEX_3",
                        "params": {
                            "asset": "LOCKDESC",
                            "asset_longname": "",
                            "asset_parent": "",
                            "block_index": "$BLOCK_INDEX",
                            "burn_payment": False,
                            "description": "My super asset LOCKDESC",
                            "divisible": True,
                            "end_block": 0,
                            "hard_cap": 12000000000,
                            "lock_description": False,
                            "lock_quantity": True,
                            "max_mint_per_tx": 1100000000,
                            "minted_asset_commission_int": 20000000,
                            "pre_minted": True,
                            "premint_quantity": 10000000000,
                            "price": 0,
                            "quantity_by_price": 1,
                            "soft_cap": 0,
                            "soft_cap_deadline_block": 0,
                            "source": "$ADDRESS_9",
                            "start_block": 0,
                            "status": "open",
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            }
        ],
    },
    {
        "title": "Mint LOCKDESC",
        "transaction": "fairmint",
        "source": "$ADDRESS_8",
        "params": {
            "asset": "LOCKDESC",
        },
        "controls": [
            {
                "url": "blocks/$BLOCK_INDEX/events?event_name=NEW_FAIRMINT,CREDIT,FAIRMINTER_UPDATE,ASSET_ISSUANCE",
                "result": [
                    {
                        "event": "ASSET_ISSUANCE",
                        "event_index": "$EVENT_INDEX_7",
                        "params": {
                            "asset": "LOCKDESC",
                            "asset_events": "fairmint",
                            "asset_longname": "",
                            "block_index": "$BLOCK_INDEX",
                            "call_date": 0,
                            "call_price": 0.0,
                            "callable": False,
                            "description": "My super asset LOCKDESC",
                            "description_locked": False,
                            "divisible": True,
                            "fair_minting": False,
                            "fee_paid": 0,
                            "issuer": "$ADDRESS_9",
                            "locked": True,
                            "msg_index": 0,
                            "quantity": 1000000000,
                            "reset": False,
                            "source": "$ADDRESS_8",
                            "status": "valid",
                            "transfer": False,
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "FAIRMINTER_UPDATE",
                        "event_index": "$EVENT_INDEX_6",
                        "params": {"status": "closed", "tx_hash": "$FAIRMINTER_LOCKDESC_HASH"},
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "NEW_FAIRMINT",
                        "event_index": "$EVENT_INDEX_5",
                        "params": {
                            "asset": "LOCKDESC",
                            "block_index": "$BLOCK_INDEX",
                            "commission": 200000000,
                            "earn_quantity": 800000000,
                            "fairminter_tx_hash": "$FAIRMINTER_LOCKDESC_HASH",
                            "paid_quantity": 0,
                            "source": "$ADDRESS_8",
                            "status": "valid",
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": "$EVENT_INDEX_4",
                        "params": {
                            "address": "$ADDRESS_9",
                            "asset": "LOCKDESC",
                            "block_index": "$BLOCK_INDEX",
                            "calling_function": "fairmint commission",
                            "event": "$TX_HASH",
                            "quantity": 200000000,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": "$EVENT_INDEX_3",
                        "params": {
                            "address": "$ADDRESS_8",
                            "asset": "LOCKDESC",
                            "block_index": "$BLOCK_INDEX",
                            "calling_function": "fairmint",
                            "event": "$TX_HASH",
                            "quantity": 800000000,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            }
        ],
    },
    {
        "title": "Create fairminter BURNER",
        "transaction": "fairminter",
        "source": "$ADDRESS_9",
        "params": {
            "asset": "BURNER",
            "price": 1,
            "minted_asset_commission": 0.2,
            "description": "let's burn it",
            "hard_cap": 1 * 10**8,
            "lock_description": True,
            "lock_quantity": True,
            "burn_payment": True,
        },
        "set_variables": {
            "FAIRMINTER_BURNER_HASH": "$TX_HASH",
        },
        "controls": [
            {
                "url": "blocks/$BLOCK_INDEX/events?event_name=NEW_FAIRMINTER,ASSET_CREATION,ASSET_ISSUANCE,DEBIT",
                "result": [
                    {
                        "event": "DEBIT",
                        "event_index": "$EVENT_INDEX_6",
                        "params": {
                            "action": "fairminter fee",
                            "address": "$ADDRESS_9",
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "event": "$TX_HASH",
                            "quantity": 50000000,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "ASSET_ISSUANCE",
                        "event_index": "$EVENT_INDEX_5",
                        "params": {
                            "asset": "BURNER",
                            "asset_events": "open_fairminter",
                            "asset_longname": "",
                            "block_index": "$BLOCK_INDEX",
                            "call_date": 0,
                            "call_price": 0,
                            "callable": False,
                            "description": "let's burn it",
                            "divisible": True,
                            "fair_minting": True,
                            "fee_paid": 50000000.0,
                            "issuer": "$ADDRESS_9",
                            "locked": False,
                            "quantity": 0,
                            "reset": False,
                            "source": "$ADDRESS_9",
                            "status": "valid",
                            "transfer": False,
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "ASSET_CREATION",
                        "event_index": "$EVENT_INDEX_4",
                        "params": {
                            "asset_id": "21328597",
                            "asset_longname": None,
                            "asset_name": "BURNER",
                            "block_index": "$BLOCK_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "NEW_FAIRMINTER",
                        "event_index": "$EVENT_INDEX_3",
                        "params": {
                            "asset": "BURNER",
                            "asset_longname": "",
                            "asset_parent": "",
                            "block_index": "$BLOCK_INDEX",
                            "burn_payment": True,
                            "description": "let's burn it",
                            "divisible": True,
                            "end_block": 0,
                            "hard_cap": 100000000,
                            "lock_description": True,
                            "lock_quantity": True,
                            "max_mint_per_tx": 0,
                            "minted_asset_commission_int": 20000000,
                            "pre_minted": False,
                            "premint_quantity": 0,
                            "price": 1,
                            "quantity_by_price": 1,
                            "soft_cap": 0,
                            "soft_cap_deadline_block": 0,
                            "source": "$ADDRESS_9",
                            "start_block": 0,
                            "status": "open",
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            }
        ],
    },
    {
        "title": "Mint BURNER",
        "transaction": "fairmint",
        "source": "$ADDRESS_8",
        "params": {
            "asset": "BURNER",
            "quantity": 1 * 10**8,
        },
        "controls": [
            {
                "url": "blocks/$BLOCK_INDEX/events?event_name=NEW_FAIRMINT,CREDIT,FAIRMINTER_UPDATE,ASSET_ISSUANCE,DEBIT,ASSET_DESTRUCTION",
                "result": [
                    {
                        "event": "ASSET_ISSUANCE",
                        "event_index": "$EVENT_INDEX_9",
                        "params": {
                            "asset": "BURNER",
                            "asset_events": "fairmint",
                            "asset_longname": "",
                            "block_index": "$BLOCK_INDEX",
                            "call_date": 0,
                            "call_price": 0.0,
                            "callable": False,
                            "description": "let's burn it",
                            "description_locked": True,
                            "divisible": True,
                            "fair_minting": False,
                            "fee_paid": 0,
                            "issuer": "$ADDRESS_9",
                            "locked": True,
                            "msg_index": 0,
                            "quantity": 100000000,
                            "reset": False,
                            "source": "$ADDRESS_8",
                            "status": "valid",
                            "transfer": False,
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "FAIRMINTER_UPDATE",
                        "event_index": "$EVENT_INDEX_8",
                        "params": {"status": "closed", "tx_hash": "$FAIRMINTER_BURNER_HASH"},
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "NEW_FAIRMINT",
                        "event_index": "$EVENT_INDEX_7",
                        "params": {
                            "asset": "BURNER",
                            "block_index": "$BLOCK_INDEX",
                            "commission": 20000000,
                            "earn_quantity": 80000000,
                            "fairminter_tx_hash": "$FAIRMINTER_BURNER_HASH",
                            "paid_quantity": 100000000,
                            "source": "$ADDRESS_8",
                            "status": "valid",
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": "$EVENT_INDEX_6",
                        "params": {
                            "address": "$ADDRESS_9",
                            "asset": "BURNER",
                            "block_index": "$BLOCK_INDEX",
                            "calling_function": "fairmint commission",
                            "event": "$TX_HASH",
                            "quantity": 20000000,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": "$EVENT_INDEX_5",
                        "params": {
                            "address": "$ADDRESS_8",
                            "asset": "BURNER",
                            "block_index": 118,
                            "calling_function": "fairmint",
                            "event": "$TX_HASH",
                            "quantity": 80000000,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "ASSET_DESTRUCTION",
                        "event_index": "$EVENT_INDEX_4",
                        "params": {
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "quantity": 100000000,
                            "source": "$ADDRESS_8",
                            "status": "valid",
                            "tag": "burn fairmint payment",
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": "$EVENT_INDEX_3",
                        "params": {
                            "action": "burn fairmint payment",
                            "address": "$ADDRESS_8",
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "event": "$TX_HASH",
                            "quantity": 100000000,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            }
        ],
    },
    {
        "title": "Create fairminter EXPANSIVE",
        "transaction": "fairminter",
        "source": "$ADDRESS_9",
        "params": {
            "asset": "EXPANSIVE",
            "price": 999 * 10**8,
            "description": "too expensive for you",
            "end_block": "$CURRENT_BLOCK + 2",
        },
        "set_variables": {
            "FAIRMINTER_EXPANSIVE_HASH": "$TX_HASH",
            "FAIRMINTER_EXPANSIVE_TX_INDEX": "$TX_INDEX",
        },
        "controls": [
            {
                "url": "blocks/$BLOCK_INDEX/events?event_name=NEW_FAIRMINTER,ASSET_CREATION,ASSET_ISSUANCE,DEBIT",
                "result": [
                    {
                        "event": "DEBIT",
                        "event_index": "$EVENT_INDEX_6",
                        "params": {
                            "action": "fairminter fee",
                            "address": "$ADDRESS_9",
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "event": "$TX_HASH",
                            "quantity": 50000000,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "ASSET_ISSUANCE",
                        "event_index": "$EVENT_INDEX_5",
                        "params": {
                            "asset": "EXPANSIVE",
                            "asset_events": "open_fairminter",
                            "asset_longname": "",
                            "block_index": "$BLOCK_INDEX",
                            "call_date": 0,
                            "call_price": 0,
                            "callable": False,
                            "description": "too expensive for you",
                            "divisible": True,
                            "fair_minting": True,
                            "fee_paid": 50000000.0,
                            "issuer": "$ADDRESS_9",
                            "locked": False,
                            "quantity": 0,
                            "reset": False,
                            "source": "$ADDRESS_9",
                            "status": "valid",
                            "transfer": False,
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "ASSET_CREATION",
                        "event_index": "$EVENT_INDEX_4",
                        "params": {
                            "asset_id": "1024679892006",
                            "asset_longname": None,
                            "asset_name": "EXPANSIVE",
                            "block_index": "$BLOCK_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "NEW_FAIRMINTER",
                        "event_index": "$EVENT_INDEX_3",
                        "params": {
                            "asset": "EXPANSIVE",
                            "asset_longname": "",
                            "asset_parent": "",
                            "block_index": "$BLOCK_INDEX",
                            "burn_payment": False,
                            "description": "too expensive for you",
                            "divisible": True,
                            "end_block": "$BLOCK_INDEX + 1",
                            "hard_cap": 0,
                            "lock_description": False,
                            "lock_quantity": False,
                            "max_mint_per_tx": 0,
                            "minted_asset_commission_int": 0,
                            "pre_minted": False,
                            "premint_quantity": 0,
                            "price": 99900000000,
                            "quantity_by_price": 1,
                            "soft_cap": 0,
                            "soft_cap_deadline_block": 0,
                            "source": "$ADDRESS_9",
                            "start_block": 0,
                            "status": "open",
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            }
        ],
    },
    {
        "title": "Mint EXPANSIVE",
        "transaction": "fairmint",
        "source": "$ADDRESS_8",
        "params": {
            "asset": "EXPANSIVE",
            "quantity": 1 * 10**8,
        },
        "expected_error": ["insufficient XCP balance"],
    },
    {
        "title": "mint empty block to trigger close of fairminters",
        "transaction": "mine_blocks",
        "params": {"blocks": 1},
        "controls": [
            {
                "url": "blocks/$BLOCK_INDEX/events?event_name=FAIRMINTER_UPDATE,ASSET_ISSUANCE",
                "result": [
                    {
                        "event": "ASSET_ISSUANCE",
                        "event_index": "$EVENT_INDEX_3",
                        "params": {
                            "asset": "EXPANSIVE",
                            "asset_events": "close_fairminter",
                            "asset_longname": "",
                            "block_index": "$BLOCK_INDEX",
                            "call_date": 0,
                            "call_price": 0.0,
                            "callable": False,
                            "description": "too expensive for you",
                            "description_locked": False,
                            "divisible": True,
                            "fair_minting": False,
                            "fee_paid": 50000000,
                            "issuer": "$ADDRESS_9",
                            "locked": False,
                            "msg_index": 1,
                            "quantity": 0,
                            "reset": False,
                            "source": "$ADDRESS_9",
                            "status": "valid",
                            "transfer": False,
                            "tx_hash": "$FAIRMINTER_EXPANSIVE_HASH",
                            "tx_index": "$FAIRMINTER_EXPANSIVE_TX_INDEX",
                        },
                        "tx_hash": None,
                    },
                    {
                        "event": "FAIRMINTER_UPDATE",
                        "event_index": "$EVENT_INDEX_2",
                        "params": {"status": "closed", "tx_hash": "$FAIRMINTER_EXPANSIVE_HASH"},
                        "tx_hash": None,
                    },
                ],
            }
        ],
    },
    {
        "title": "Mint EXPANSIVE",
        "transaction": "fairmint",
        "source": "$ADDRESS_8",
        "params": {
            "asset": "EXPANSIVE",
            "quantity": 1 * 10**8,
        },
        "expected_error": [
            "fairminter is not open for asset: `EXPANSIVE`",
            "insufficient XCP balance",
        ],
    },
]
