SCENARIO = [
    {
        "title": "Sweep assets",
        "transaction": "sweep",
        "source": "$ADDRESS_3",
        "params": {
            "destination": "$ADDRESS_4",
            "flags": 1,
            "memo": "sweep my assets",
        },
        "set_variables": {
            "SWEEP_HASH": "$TX_HASH",
        },
        "controls": [
            {
                "url": "blocks/183/events?event_name=SWEEP,CREDIT,DEBIT",
                "result": [
                    {
                        "event": "SWEEP",
                        "event_index": "$EVENT_INDEX_10",
                        "params": {
                            "block_index": "$BLOCK_INDEX",
                            "destination": "$ADDRESS_4",
                            "fee_paid": 600000,
                            "flags": 1,
                            "memo": "sweep my assets",
                            "source": "$ADDRESS_3",
                            "status": "valid",
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": "$EVENT_INDEX_9",
                        "params": {
                            "address": "$ADDRESS_4",
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "calling_function": "sweep",
                            "event": "$TX_HASH",
                            "quantity": 74499387833,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": "$EVENT_INDEX_8",
                        "params": {
                            "action": "sweep",
                            "address": "$ADDRESS_3",
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "event": "$TX_HASH",
                            "quantity": 74499387833,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": "$EVENT_INDEX_7",
                        "params": {
                            "address": "$ADDRESS_4",
                            "asset": "MYASSETA",
                            "block_index": "$BLOCK_INDEX",
                            "calling_function": "sweep",
                            "event": "$TX_HASH",
                            "quantity": 10,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": "$EVENT_INDEX_6",
                        "params": {
                            "action": "sweep",
                            "address": "$ADDRESS_3",
                            "asset": "MYASSETA",
                            "block_index": "$BLOCK_INDEX",
                            "event": "$TX_HASH",
                            "quantity": 10,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": "$EVENT_INDEX_5",
                        "params": {
                            "address": "$ADDRESS_4",
                            "asset": "FAIRMINTA",
                            "block_index": "$BLOCK_INDEX",
                            "calling_function": "sweep",
                            "event": "$TX_HASH",
                            "quantity": 500000000,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": "$EVENT_INDEX_4",
                        "params": {
                            "action": "sweep",
                            "address": "$ADDRESS_3",
                            "asset": "FAIRMINTA",
                            "block_index": "$BLOCK_INDEX",
                            "event": "$TX_HASH",
                            "quantity": 500000000,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": "$EVENT_INDEX_3",
                        "params": {
                            "action": "sweep fee",
                            "address": "$ADDRESS_3",
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "event": "$TX_HASH",
                            "quantity": 600000,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            },
        ],
    },
]
