SCENARIO = [
    {
        "title": "Test Atomic Swap",
        "transaction": "atomic_swap",
        "params": {
            "seller": "$ADDRESS_6",
            "utxo": "$UTXO_MOVE_2_TX_HASH:0",  # 15.00000000 MYASSETA and 15.00000000 XCP
            "price": 100000,  # for 100000 satoshis
            "buyer": "$ADDRESS_8",
        },
        "set_variables": {
            "ATOMICSWAP_1_TX_HASH": "$TX_HASH",
        },
        "controls": [
            {
                "url": "blocks/$BLOCK_INDEX/events?event_name=UTXO_MOVE,DEBIT,CREDIT",
                "result": [
                    {
                        "event": "UTXO_MOVE",
                        "event_index": "$EVENT_INDEX_8",
                        "params": {
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "destination": "$TX_HASH:0",
                            "destination_address": "$ADDRESS_8",
                            "msg_index": 1,
                            "quantity": 2000000000,
                            "source": "$UTXO_MOVE_2_TX_HASH:0",
                            "source_address": "$ADDRESS_6",
                            "status": "valid",
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                            "send_type": "move",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": "$EVENT_INDEX_7",
                        "params": {
                            "address": None,
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "calling_function": "utxo move",
                            "event": "$TX_HASH",
                            "quantity": 2000000000,
                            "tx_index": "$TX_INDEX",
                            "utxo": "$TX_HASH:0",
                            "utxo_address": "$ADDRESS_8",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": "$EVENT_INDEX_6",
                        "params": {
                            "action": "utxo move",
                            "address": None,
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "event": "$TX_HASH",
                            "quantity": 2000000000,
                            "tx_index": "$TX_INDEX",
                            "utxo": "$UTXO_MOVE_2_TX_HASH:0",
                            "utxo_address": "$ADDRESS_6",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "UTXO_MOVE",
                        "event_index": "$EVENT_INDEX_5",
                        "params": {
                            "asset": "MYASSETA",
                            "block_index": "$BLOCK_INDEX",
                            "destination": "$TX_HASH:0",
                            "destination_address": "$ADDRESS_8",
                            "msg_index": 0,
                            "quantity": 2000000000,
                            "source": "$UTXO_MOVE_2_TX_HASH:0",
                            "source_address": "$ADDRESS_6",
                            "status": "valid",
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                            "send_type": "move",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": "$EVENT_INDEX_4",
                        "params": {
                            "address": None,
                            "asset": "MYASSETA",
                            "block_index": "$BLOCK_INDEX",
                            "calling_function": "utxo move",
                            "event": "$TX_HASH",
                            "quantity": 2000000000,
                            "tx_index": "$TX_INDEX",
                            "utxo": "$TX_HASH:0",
                            "utxo_address": "$ADDRESS_8",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": "$EVENT_INDEX_3",
                        "params": {
                            "action": "utxo move",
                            "address": None,
                            "asset": "MYASSETA",
                            "block_index": "$BLOCK_INDEX",
                            "event": "$TX_HASH",
                            "quantity": 2000000000,
                            "tx_index": "$TX_INDEX",
                            "utxo": "$UTXO_MOVE_2_TX_HASH:0",
                            "utxo_address": "$ADDRESS_6",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            }
        ],
    },
    {
        "title": "Test Atomic Swap with Counterparty TX",
        "transaction": "atomic_swap",
        "params": {
            "seller": "$ADDRESS_8",
            "utxo": "$ATOMICSWAP_1_TX_HASH:0",  # 15.00000000 MYASSETA and 15.00000000 XCP
            "price": 100000,  # for 100000 satoshis
            "buyer": "$ADDRESS_9",
            "counterparty_tx": {
                "transaction": "issuance",
                "source": "$ADDRESS_9",
                "params": {
                    "asset": "MYASSETB",
                    "quantity": 1000 * 10**8,
                    "divisible": True,
                    "description": "My super asset B",
                },
            },
        },
        "set_variables": {
            "ATOMICSWAP_2_TX_HASH": "$TX_HASH",
        },
        "controls": [
            {
                "url": "blocks/$BLOCK_INDEX/events?event_name=UTXO_MOVE,DEBIT,CREDIT,ASSET_CREATION,ASSET_ISSUANCE",
                "result": [
                    {
                        "event": "CREDIT",
                        "event_index": "$EVENT_INDEX_12",
                        "params": {
                            "address": "$ADDRESS_9",
                            "asset": "MYASSETB",
                            "block_index": "$BLOCK_INDEX",
                            "calling_function": "issuance",
                            "event": "$TX_HASH",
                            "quantity": 100000000000,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "ASSET_ISSUANCE",
                        "event_index": "$EVENT_INDEX_11",
                        "params": {
                            "asset": "MYASSETB",
                            "asset_longname": None,
                            "asset_events": "creation",
                            "block_index": "$BLOCK_INDEX",
                            "call_date": 0,
                            "call_price": 0.0,
                            "callable": False,
                            "description": "My super asset B",
                            "description_locked": False,
                            "divisible": True,
                            "fee_paid": 50000000,
                            "issuer": "$ADDRESS_9",
                            "locked": False,
                            "quantity": 100000000000,
                            "reset": False,
                            "source": "$ADDRESS_9",
                            "status": "valid",
                            "transfer": False,
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "ASSET_CREATION",
                        "event_index": "$EVENT_INDEX_10",
                        "params": {
                            "asset_id": "103804245871",
                            "asset_longname": None,
                            "asset_name": "MYASSETB",
                            "block_index": "$BLOCK_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": "$EVENT_INDEX_9",
                        "params": {
                            "action": "issuance fee",
                            "address": "$ADDRESS_9",
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "event": "$TX_HASH",
                            "quantity": 50000000,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "UTXO_MOVE",
                        "event_index": "$EVENT_INDEX_8",
                        "params": {
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "destination": "$TX_HASH:1",
                            "destination_address": "$ADDRESS_9",
                            "msg_index": 1,
                            "quantity": 2000000000,
                            "source": "$ATOMICSWAP_1_TX_HASH:0",
                            "source_address": "$ADDRESS_8",
                            "status": "valid",
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                            "send_type": "move",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": "$EVENT_INDEX_7",
                        "params": {
                            "address": None,
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "calling_function": "utxo move",
                            "event": "$TX_HASH",
                            "quantity": 2000000000,
                            "tx_index": "$TX_INDEX",
                            "utxo": "$TX_HASH:1",
                            "utxo_address": "$ADDRESS_9",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": "$EVENT_INDEX_6",
                        "params": {
                            "action": "utxo move",
                            "address": None,
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "event": "$TX_HASH",
                            "quantity": 2000000000,
                            "tx_index": "$TX_INDEX",
                            "utxo": "$ATOMICSWAP_1_TX_HASH:0",
                            "utxo_address": "$ADDRESS_8",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "UTXO_MOVE",
                        "event_index": "$EVENT_INDEX_5",
                        "params": {
                            "asset": "MYASSETA",
                            "block_index": "$BLOCK_INDEX",
                            "destination": "$TX_HASH:1",
                            "destination_address": "$ADDRESS_9",
                            "msg_index": 0,
                            "quantity": 2000000000,
                            "source": "$ATOMICSWAP_1_TX_HASH:0",
                            "source_address": "$ADDRESS_8",
                            "status": "valid",
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                            "send_type": "move",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": "$EVENT_INDEX_4",
                        "params": {
                            "address": None,
                            "asset": "MYASSETA",
                            "block_index": "$BLOCK_INDEX",
                            "calling_function": "utxo move",
                            "event": "$TX_HASH",
                            "quantity": 2000000000,
                            "tx_index": "$TX_INDEX",
                            "utxo": "$TX_HASH:1",
                            "utxo_address": "$ADDRESS_9",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": "$EVENT_INDEX_3",
                        "params": {
                            "action": "utxo move",
                            "address": None,
                            "asset": "MYASSETA",
                            "block_index": "$BLOCK_INDEX",
                            "event": "$TX_HASH",
                            "quantity": 2000000000,
                            "tx_index": "$TX_INDEX",
                            "utxo": "$ATOMICSWAP_1_TX_HASH:0",
                            "utxo_address": "$ADDRESS_8",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            }
        ],
    },
]
