SCENARIO = [
    {
        "title": "Asset Issuance TESTLOCKDESC",
        "transaction": "issuance",
        "source": "$ADDRESS_1",
        "params": {
            "asset": "TESTLOCKDESC",
            "quantity": int(100 * 1e8),
            "description": "Test Locking Description",
        },
        "controls": [
            {
                "url": "blocks/143/events?event_name=ASSET_ISSUANCE,CREDIT,DEBIT,ASSET_CREATION",
                "result": [
                    {
                        "event": "CREDIT",
                        "event_index": 264,
                        "params": {
                            "address": "$ADDRESS_1",
                            "asset": "TESTLOCKDESC",
                            "block_index": 143,
                            "calling_function": "issuance",
                            "event": "$TX_HASH",
                            "quantity": 10000000000,
                            "tx_index": 30,
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "ASSET_ISSUANCE",
                        "event_index": 263,
                        "params": {
                            "asset": "TESTLOCKDESC",
                            "asset_longname": None,
                            "block_index": 143,
                            "call_date": 0,
                            "call_price": 0.0,
                            "callable": False,
                            "description": "Test Locking Description",
                            "description_locked": False,
                            "divisible": True,
                            "fee_paid": 50000000,
                            "issuer": "$ADDRESS_1",
                            "locked": False,
                            "quantity": 10000000000,
                            "reset": False,
                            "source": "$ADDRESS_1",
                            "status": "valid",
                            "transfer": False,
                            "tx_hash": "$TX_HASH",
                            "tx_index": 30,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "ASSET_CREATION",
                        "event_index": 262,
                        "params": {
                            "asset_id": "70403005118950974",
                            "asset_longname": None,
                            "asset_name": "TESTLOCKDESC",
                            "block_index": 143,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": 261,
                        "params": {
                            "action": "issuance fee",
                            "address": "$ADDRESS_1",
                            "asset": "XCP",
                            "block_index": 143,
                            "event": "$TX_HASH",
                            "quantity": 50000000,
                            "tx_index": 30,
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            }
        ],
    },
    {
        "title": "Test free subasset issuance",
        "transaction": "issuance",
        "source": "$ADDRESS_1",
        "params": {
            "asset": "TESTLOCKDESC.MYSUBASSET",
            "quantity": 0,
            "description": "Test Locking Description",
        },
        "controls": [
            {
                "url": "blocks/144/events?event_name=ASSET_ISSUANCE,ASSET_CREATION,CREDIT,DEBIT",
                "result": [
                    {
                        "event": "ASSET_ISSUANCE",
                        "event_index": 271,
                        "params": {
                            "asset": "A95428959745315388",
                            "asset_longname": "TESTLOCKDESC.MYSUBASSET",
                            "block_index": 144,
                            "call_date": 0,
                            "call_price": 0.0,
                            "callable": False,
                            "description": "Test Locking Description",
                            "description_locked": False,
                            "divisible": True,
                            "fee_paid": 0,
                            "issuer": "$ADDRESS_1",
                            "locked": False,
                            "quantity": 0,
                            "reset": False,
                            "source": "$ADDRESS_1",
                            "status": "valid",
                            "transfer": False,
                            "tx_hash": "$TX_HASH",
                            "tx_index": 31,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "ASSET_CREATION",
                        "event_index": 270,
                        "params": {
                            "asset_id": "95428959745315388",
                            "asset_longname": "TESTLOCKDESC.MYSUBASSET",
                            "asset_name": "A95428959745315388",
                            "block_index": 144,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": 269,
                        "params": {
                            "action": "issuance fee",
                            "address": "$ADDRESS_1",
                            "asset": "XCP",
                            "block_index": 144,
                            "event": "$TX_HASH",
                            "quantity": 0,
                            "tx_index": 31,
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            }
        ],
    },
    {
        "title": "Lock Asset Description",
        "transaction": "issuance",
        "source": "$ADDRESS_1",
        "params": {
            "asset": "TESTLOCKDESC",
            "quantity": 0,
            "description": "lock_description",
        },
        "controls": [
            {
                "url": "blocks/145/events?event_name=ASSET_ISSUANCE,ASSET_CREATION,CREDIT,DEBIT",
                "result": [
                    {
                        "event": "ASSET_ISSUANCE",
                        "event_index": 277,
                        "params": {
                            "asset": "TESTLOCKDESC",
                            "asset_longname": None,
                            "block_index": 145,
                            "call_date": 0,
                            "call_price": 0.0,
                            "callable": False,
                            "description": "Test Locking Description",
                            "description_locked": True,
                            "divisible": True,
                            "fee_paid": 0,
                            "issuer": "$ADDRESS_1",
                            "locked": False,
                            "quantity": 0,
                            "reset": False,
                            "source": "$ADDRESS_1",
                            "status": "valid",
                            "transfer": False,
                            "tx_hash": "$TX_HASH",
                            "tx_index": 32,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": 276,
                        "params": {
                            "action": "issuance fee",
                            "address": "$ADDRESS_1",
                            "asset": "XCP",
                            "block_index": 145,
                            "event": "$TX_HASH",
                            "quantity": 0,
                            "tx_index": 32,
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            }
        ],
    },
    {
        "title": "Test locked description",
        "transaction": "issuance",
        "source": "$ADDRESS_1",
        "params": {
            "asset": "TESTLOCKDESC",
            "quantity": 0,
            "description": "A new description",
        },
        "expected_error": ["Cannot update a locked description"],
    },
    {
        "title": "Test Subasset on numeric",
        "transaction": "issuance",
        "source": "$ADDRESS_1",
        "params": {
            "asset": "A95428959745315388.SUBNUMERIC",
            "quantity": int(100 * 10e8),
            "description": "A subnumeric asset",
        },
        "controls": [
            {
                "url": "blocks/146/events?event_name=ASSET_ISSUANCE,ASSET_CREATION,CREDIT,DEBIT",
                "result": [
                    {
                        "event": "CREDIT",
                        "event_index": 285,
                        "params": {
                            "address": "$ADDRESS_1",
                            "asset": "A95428956980101314",
                            "block_index": 146,
                            "calling_function": "issuance",
                            "event": "$TX_HASH",
                            "quantity": 100000000000,
                            "tx_index": 33,
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "ASSET_ISSUANCE",
                        "event_index": 284,
                        "params": {
                            "asset": "A95428956980101314",
                            "asset_longname": "A95428959745315388.SUBNUMERIC",
                            "block_index": 146,
                            "call_date": 0,
                            "call_price": 0.0,
                            "callable": False,
                            "description": "A subnumeric asset",
                            "description_locked": False,
                            "divisible": True,
                            "fee_paid": 0,
                            "issuer": "$ADDRESS_1",
                            "locked": False,
                            "quantity": 100000000000,
                            "reset": False,
                            "source": "$ADDRESS_1",
                            "status": "valid",
                            "transfer": False,
                            "tx_hash": "$TX_HASH",
                            "tx_index": 33,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "ASSET_CREATION",
                        "event_index": 283,
                        "params": {
                            "asset_id": "95428956980101314",
                            "asset_longname": "A95428959745315388.SUBNUMERIC",
                            "asset_name": "A95428956980101314",
                            "block_index": 146,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": 282,
                        "params": {
                            "action": "issuance fee",
                            "address": "$ADDRESS_1",
                            "asset": "XCP",
                            "block_index": 146,
                            "event": "$TX_HASH",
                            "quantity": 0,
                            "tx_index": 33,
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            },
        ],
    },
]
