# soft cap not reached
SCENARIO = [
    {
        "title": "Create FAIRMINTB fairminter",
        "transaction": "fairminter",
        "source": "$ADDRESS_1",
        "params": {
            "asset": "FAIRMINTB",
            "price": 1,
            "hard_cap": 100 * 10**8,
            "soft_cap": 10 * 10**8,
            "soft_cap_deadline_block": 130,
        },
        "set_variables": {
            "FAIRMINTB_TX_HASH": "$TX_HASH",
            "FAIRMINTB_TX_INDEX": "$TX_INDEX",
        },
        "controls": [
            {
                "url": "assets/FAIRMINTB/fairminters",
                "result": [
                    {
                        "tx_hash": "$TX_HASH",
                        "tx_index": "$TX_INDEX",
                        "block_index": "$BLOCK_INDEX",
                        "source": "$ADDRESS_1",
                        "asset": "FAIRMINTB",
                        "asset_parent": "",
                        "asset_longname": "",
                        "description": "",
                        "price": 1,
                        "quantity_by_price": 1,
                        "hard_cap": 100 * 10**8,
                        "burn_payment": False,
                        "max_mint_per_tx": 0,
                        "premint_quantity": 0,
                        "start_block": 0,
                        "end_block": 0,
                        "minted_asset_commission_int": 0,
                        "soft_cap": 10 * 10**8,
                        "soft_cap_deadline_block": 130,
                        "lock_description": False,
                        "lock_quantity": False,
                        "divisible": True,
                        "pre_minted": False,
                        "status": "open",
                        "earned_quantity": None,
                        "commission": None,
                        "paid_quantity": None,
                        "confirmed": True,
                    }
                ],
            }
        ],
    },
    {
        "title": "mint FAIRMINTB with ADDRESS_2",
        "transaction": "fairmint",
        "source": "$ADDRESS_2",
        "params": {
            "asset": "FAIRMINTB",
            "quantity": 1 * 10**8,
        },
        "set_variables": {
            "FAIRMINTB_WITH_ADDRESS_2_TX_HASH": "$TX_HASH",
            "FAIRMINTB_WITH_ADDRESS_2_TX_INDEX": "$TX_INDEX",
        },
        "controls": [
            {
                "url": "blocks/$BLOCK_INDEX/events?event_name=CREDIT,DEBIT,ASSET_ISSUANCE,NEW_FAIRMINT",
                "result": [
                    {
                        "event": "ASSET_ISSUANCE",
                        "event_index": "$EVENT_INDEX_7",
                        "params": {
                            "asset": "FAIRMINTB",
                            "asset_longname": "",
                            "asset_events": "fairmint",
                            "block_index": "$BLOCK_INDEX",
                            "call_date": 0,
                            "call_price": 0.0,
                            "callable": False,
                            "description": "",
                            "description_locked": False,
                            "divisible": True,
                            "fair_minting": True,
                            "fee_paid": 0,
                            "issuer": "$ADDRESS_1",
                            "locked": False,
                            "msg_index": 0,
                            "quantity": 100000000,
                            "reset": False,
                            "source": "$ADDRESS_2",
                            "status": "valid",
                            "transfer": False,
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "NEW_FAIRMINT",
                        "event_index": "$EVENT_INDEX_6",
                        "params": {
                            "asset": "FAIRMINTB",
                            "block_index": "$BLOCK_INDEX",
                            "commission": 0,
                            "earn_quantity": 100000000,
                            "fairminter_tx_hash": "$FAIRMINTB_TX_HASH",
                            "paid_quantity": 100000000,
                            "source": "$ADDRESS_2",
                            "status": "valid",
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": "$EVENT_INDEX_5",
                        "params": {
                            "address": "mvCounterpartyXXXXXXXXXXXXXXW24Hef",
                            "asset": "FAIRMINTB",
                            "block_index": "$BLOCK_INDEX",
                            "calling_function": "escrowed fairmint",
                            "event": "$TX_HASH",
                            "quantity": 100000000,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": "$EVENT_INDEX_4",
                        "params": {
                            "address": "mvCounterpartyXXXXXXXXXXXXXXW24Hef",
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "calling_function": "escrowed fairmint",
                            "event": "$TX_HASH",
                            "quantity": 100000000,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": "$EVENT_INDEX_3",
                        "params": {
                            "action": "escrowed fairmint",
                            "address": "$ADDRESS_2",
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "event": "$TX_HASH",
                            "quantity": 100000000,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            }
        ],
    },
    {
        "title": "mint FAIRMINTB with ADDRESS_3",
        "transaction": "fairmint",
        "source": "$ADDRESS_3",
        "params": {
            "asset": "FAIRMINTB",
            "quantity": 1 * 10**8,
        },
        "set_variables": {
            "FAIRMINTB_WITH_ADDRESS_3_TX_HASH": "$TX_HASH",
            "FAIRMINTB_WITH_ADDRESS_3_TX_INDEX": "$TX_INDEX",
        },
        "controls": [
            {
                "url": "blocks/$BLOCK_INDEX/events?event_name=CREDIT,DEBIT,ASSET_ISSUANCE,NEW_FAIRMINT,NEW_TRANSACTION",
                "result": [
                    {
                        "event": "ASSET_ISSUANCE",
                        "event_index": "$EVENT_INDEX_7",
                        "params": {
                            "asset": "FAIRMINTB",
                            "asset_longname": "",
                            "asset_events": "fairmint",
                            "block_index": "$BLOCK_INDEX",
                            "call_date": 0,
                            "call_price": 0.0,
                            "callable": False,
                            "description": "",
                            "description_locked": False,
                            "divisible": True,
                            "fair_minting": True,
                            "fee_paid": 0,
                            "issuer": "$ADDRESS_1",
                            "locked": False,
                            "msg_index": 0,
                            "quantity": 100000000,
                            "reset": False,
                            "source": "$ADDRESS_3",
                            "status": "valid",
                            "transfer": False,
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "NEW_FAIRMINT",
                        "event_index": "$EVENT_INDEX_6",
                        "params": {
                            "asset": "FAIRMINTB",
                            "block_index": "$BLOCK_INDEX",
                            "commission": 0,
                            "earn_quantity": 100000000,
                            "fairminter_tx_hash": "$FAIRMINTB_TX_HASH",
                            "paid_quantity": 100000000,
                            "source": "$ADDRESS_3",
                            "status": "valid",
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": "$EVENT_INDEX_5",
                        "params": {
                            "address": "mvCounterpartyXXXXXXXXXXXXXXW24Hef",
                            "asset": "FAIRMINTB",
                            "block_index": "$BLOCK_INDEX",
                            "calling_function": "escrowed fairmint",
                            "event": "$TX_HASH",
                            "quantity": 100000000,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": "$EVENT_INDEX_4",
                        "params": {
                            "address": "mvCounterpartyXXXXXXXXXXXXXXW24Hef",
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "calling_function": "escrowed fairmint",
                            "event": "$TX_HASH",
                            "quantity": 100000000,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": "$EVENT_INDEX_3",
                        "params": {
                            "action": "escrowed fairmint",
                            "address": "$ADDRESS_3",
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "event": "$TX_HASH",
                            "quantity": 100000000,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event_index": "$EVENT_INDEX_2",
                        "event": "NEW_TRANSACTION",
                        "params": {
                            "block_hash": "$BLOCK_HASH",
                            "block_index": "$BLOCK_INDEX",
                            "block_time": "$BLOCK_TIME",
                            "btc_amount": 0,
                            "data": "5b464149524d494e54427c313030303030303030",
                            "destination": "",
                            "fee": 10000,
                            "source": "$ADDRESS_3",
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                            "utxos_info": "$TX_HASH:1",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            }
        ],
    },
    {
        "title": "mint FAIRMINTB with ADDRESS_4",
        "transaction": "fairmint",
        "source": "$ADDRESS_4",
        "params": {
            "asset": "FAIRMINTB",
            "quantity": 1 * 10**8,
        },
        "set_variables": {
            "FAIRMINTB_WITH_ADDRESS_4_TX_HASH": "$TX_HASH",
            "FAIRMINTB_WITH_ADDRESS_4_TX_INDEX": "$TX_INDEX",
        },
        "controls": [
            {
                "url": "blocks/$BLOCK_INDEX/events?event_name=CREDIT,DEBIT,ASSET_ISSUANCE,NEW_FAIRMINT",
                "result": [
                    {
                        "event": "ASSET_ISSUANCE",
                        "event_index": "$EVENT_INDEX_7",
                        "params": {
                            "asset": "FAIRMINTB",
                            "asset_longname": "",
                            "asset_events": "fairmint",
                            "block_index": "$BLOCK_INDEX",
                            "call_date": 0,
                            "call_price": 0.0,
                            "callable": False,
                            "description": "",
                            "description_locked": False,
                            "divisible": True,
                            "fair_minting": True,
                            "fee_paid": 0,
                            "issuer": "$ADDRESS_1",
                            "locked": False,
                            "msg_index": 0,
                            "quantity": 100000000,
                            "reset": False,
                            "source": "$ADDRESS_4",
                            "status": "valid",
                            "transfer": False,
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "NEW_FAIRMINT",
                        "event_index": "$EVENT_INDEX_6",
                        "params": {
                            "asset": "FAIRMINTB",
                            "block_index": "$BLOCK_INDEX",
                            "commission": 0,
                            "earn_quantity": 100000000,
                            "fairminter_tx_hash": "$FAIRMINTB_TX_HASH",
                            "paid_quantity": 100000000,
                            "source": "$ADDRESS_4",
                            "status": "valid",
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": "$EVENT_INDEX_5",
                        "params": {
                            "address": "mvCounterpartyXXXXXXXXXXXXXXW24Hef",
                            "asset": "FAIRMINTB",
                            "block_index": "$BLOCK_INDEX",
                            "calling_function": "escrowed fairmint",
                            "event": "$TX_HASH",
                            "quantity": 100000000,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": "$EVENT_INDEX_4",
                        "params": {
                            "address": "mvCounterpartyXXXXXXXXXXXXXXW24Hef",
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "calling_function": "escrowed fairmint",
                            "event": "$TX_HASH",
                            "quantity": 100000000,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": "$EVENT_INDEX_3",
                        "params": {
                            "action": "escrowed fairmint",
                            "address": "$ADDRESS_4",
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "event": "$TX_HASH",
                            "quantity": 100000000,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            }
        ],
    },
    {
        "title": "mint empty block to trigger soft cap checking",
        "transaction": "mine_blocks",
        "params": {"blocks": 1},
        "controls": [
            {
                "url": "blocks/$BLOCK_INDEX/events?event_name=ASSET_DESTRUCTION,ASSET_ISSUANCE,FAIRMINTER_UPDATE,CREDIT,DEBIT",
                "result": [
                    {
                        "event": "ASSET_DESTRUCTION",
                        "event_index": "$EVENT_INDEX_9",
                        "params": {
                            "asset": "FAIRMINTB",
                            "block_index": "$BLOCK_INDEX",
                            "quantity": 300000000,
                            "source": "$ADDRESS_1",
                            "status": "valid",
                            "tag": "soft cap not reached",
                            "tx_hash": "$FAIRMINTB_TX_HASH",
                            "tx_index": "$FAIRMINTB_TX_INDEX",
                        },
                        "tx_hash": None,
                    },
                    {
                        "event": "ASSET_ISSUANCE",
                        "event_index": "$EVENT_INDEX_8",
                        "params": {
                            "asset": "FAIRMINTB",
                            "asset_longname": "",
                            "asset_events": "close_fairminter",
                            "block_index": "$BLOCK_INDEX",
                            "call_date": 0,
                            "call_price": 0.0,
                            "callable": False,
                            "description": "",
                            "description_locked": False,
                            "divisible": True,
                            "fair_minting": False,
                            "fee_paid": 0,
                            "issuer": "$ADDRESS_1",
                            "locked": False,
                            "msg_index": 1,
                            "quantity": 0,
                            "reset": False,
                            "source": "$ADDRESS_4",
                            "status": "valid",
                            "transfer": False,
                            "tx_hash": "$FAIRMINTB_WITH_ADDRESS_4_TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": None,
                    },
                    {
                        "event": "FAIRMINTER_UPDATE",
                        "event_index": "$EVENT_INDEX_7",
                        "params": {"status": "closed", "tx_hash": "$FAIRMINTB_TX_HASH"},
                        "tx_hash": None,
                    },
                    {
                        "event": "CREDIT",
                        "event_index": "$EVENT_INDEX_6",
                        "params": {
                            "address": "$ADDRESS_4",
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "calling_function": "fairmint refund",
                            "event": "$FAIRMINTB_WITH_ADDRESS_4_TX_HASH",
                            "quantity": 100000000,
                            "tx_index": "$FAIRMINTB_WITH_ADDRESS_4_TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": None,
                    },
                    {
                        "event": "CREDIT",
                        "event_index": "$EVENT_INDEX_5",
                        "params": {
                            "address": "$ADDRESS_3",
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "calling_function": "fairmint refund",
                            "event": "$FAIRMINTB_WITH_ADDRESS_3_TX_HASH",
                            "quantity": 100000000,
                            "tx_index": "$FAIRMINTB_WITH_ADDRESS_3_TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": None,
                    },
                    {
                        "event": "CREDIT",
                        "event_index": "$EVENT_INDEX_4",
                        "params": {
                            "address": "$ADDRESS_2",
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "calling_function": "fairmint refund",
                            "event": "$FAIRMINTB_WITH_ADDRESS_2_TX_HASH",
                            "quantity": 100000000,
                            "tx_index": "$FAIRMINTB_WITH_ADDRESS_2_TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": None,
                    },
                    {
                        "event": "DEBIT",
                        "event_index": "$EVENT_INDEX_3",
                        "params": {
                            "action": "unescrowed fairmint payment",
                            "address": "mvCounterpartyXXXXXXXXXXXXXXW24Hef",
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "event": "$FAIRMINTB_TX_HASH",
                            "quantity": 300000000,
                            "tx_index": 0,
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": None,
                    },
                    {
                        "event": "DEBIT",
                        "event_index": "$EVENT_INDEX_2",
                        "params": {
                            "action": "unescrowed fairmint",
                            "address": "mvCounterpartyXXXXXXXXXXXXXXW24Hef",
                            "asset": "FAIRMINTB",
                            "block_index": "$BLOCK_INDEX",
                            "event": "$FAIRMINTB_TX_HASH",
                            "quantity": 300000000,
                            "tx_index": 0,
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": None,
                    },
                ],
            }
        ],
    },
]
