SCENARIO = [
    {
        "title": "Create FAIRMINTC fairminter",
        "transaction": "fairminter",
        "source": "$ADDRESS_1",
        "params": {
            "asset": "FAIRMINTC",
            "price": 1,
            "quantity_by_price": 5,
        },
        "set_variables": {
            "FAIRMINTC_TX_HASH": "$TX_HASH",
        },
        "controls": [
            {
                "url": "blocks/170/events?event_name=DEBIT,ASSET_ISSUANCE,ASSET_CREATION,NEW_FAIRMINTER,CREDIT",
                "result": [
                    {
                        "event": "DEBIT",
                        "event_index": 358,
                        "params": {
                            "action": "fairminter fee",
                            "address": "$ADDRESS_1",
                            "asset": "XCP",
                            "block_index": 170,
                            "event": "$TX_HASH",
                            "quantity": 50000000,
                            "tx_index": 36,
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "ASSET_ISSUANCE",
                        "event_index": 357,
                        "params": {
                            "asset": "FAIRMINTC",
                            "asset_longname": "",
                            "block_index": 170,
                            "call_date": 0,
                            "call_price": 0,
                            "callable": False,
                            "description": "",
                            "divisible": True,
                            "fair_minting": True,
                            "fee_paid": 50000000.0,
                            "issuer": "$ADDRESS_1",
                            "locked": False,
                            "quantity": 0,
                            "reset": False,
                            "source": "$ADDRESS_1",
                            "status": "valid",
                            "transfer": False,
                            "tx_hash": "$TX_HASH",
                            "tx_index": 36,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "ASSET_CREATION",
                        "event_index": 356,
                        "params": {
                            "asset_id": "1046814266084",
                            "asset_longname": None,
                            "asset_name": "FAIRMINTC",
                            "block_index": 170,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "NEW_FAIRMINTER",
                        "event_index": 355,
                        "params": {
                            "asset": "FAIRMINTC",
                            "asset_longname": "",
                            "asset_parent": "",
                            "block_index": 170,
                            "burn_payment": False,
                            "description": "",
                            "divisible": True,
                            "end_block": 0,
                            "hard_cap": 0,
                            "lock_description": False,
                            "lock_quantity": False,
                            "max_mint_per_tx": 0,
                            "minted_asset_commission_int": 0,
                            "pre_minted": False,
                            "premint_quantity": 0,
                            "price": 1,
                            "quantity_by_price": 5,
                            "soft_cap": 0,
                            "soft_cap_deadline_block": 0,
                            "source": "$ADDRESS_1",
                            "start_block": 0,
                            "status": "open",
                            "tx_hash": "$TX_HASH",
                            "tx_index": 36,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            }
        ],
    },
    {
        "title": "Mint FAIRMINTC",
        "transaction": "fairmint",
        "source": "$ADDRESS_2",
        "params": {
            "asset": "FAIRMINTC",
            "quantity": 5,
        },
        "controls": [
            {
                "url": "blocks/171/events?event_name=DEBIT,CREDIT,NEW_FAIRMINT,ASSET_ISSUANCE",
                "result": [
                    {
                        "event": "ASSET_ISSUANCE",
                        "event_index": 367,
                        "params": {
                            "asset": "FAIRMINTC",
                            "asset_longname": "",
                            "block_index": 171,
                            "call_date": 0,
                            "call_price": 0.0,
                            "callable": False,
                            "description": "",
                            "description_locked": False,
                            "divisible": True,
                            "fair_minting": True,
                            "fee_paid": 0,
                            "issuer": "$ADDRESS_1",
                            "locked": False,
                            "msg_index": 0,
                            "quantity": 5,
                            "reset": False,
                            "source": "$ADDRESS_2",
                            "status": "valid",
                            "transfer": False,
                            "tx_hash": "$TX_HASH",
                            "tx_index": 37,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "NEW_FAIRMINT",
                        "event_index": 366,
                        "params": {
                            "asset": "FAIRMINTC",
                            "block_index": 171,
                            "commission": 0,
                            "earn_quantity": 5,
                            "fairminter_tx_hash": "$FAIRMINTC_TX_HASH",
                            "paid_quantity": 1,
                            "source": "$ADDRESS_2",
                            "status": "valid",
                            "tx_hash": "$TX_HASH",
                            "tx_index": 37,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": 365,
                        "params": {
                            "address": "$ADDRESS_2",
                            "asset": "FAIRMINTC",
                            "block_index": 171,
                            "calling_function": "fairmint",
                            "event": "$TX_HASH",
                            "quantity": 5,
                            "tx_index": 37,
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": 364,
                        "params": {
                            "address": "$ADDRESS_1",
                            "asset": "XCP",
                            "block_index": 171,
                            "calling_function": "fairmint payment",
                            "event": "$TX_HASH",
                            "quantity": 1,
                            "tx_index": 37,
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": 363,
                        "params": {
                            "action": "fairmint payment",
                            "address": "$ADDRESS_2",
                            "asset": "XCP",
                            "block_index": 171,
                            "event": "$TX_HASH",
                            "quantity": 1,
                            "tx_index": 37,
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            }
        ],
    },
    {
        "title": "Mint FAIRMINTC",
        "transaction": "fairmint",
        "source": "$ADDRESS_2",
        "params": {
            "asset": "FAIRMINTC",
            "quantity": 3,
        },
        "controls": [
            {
                "url": "blocks/172/events?event_name=DEBIT,CREDIT,NEW_FAIRMINT,ASSET_ISSUANCE",
                "result": [
                    {
                        "event": "ASSET_ISSUANCE",
                        "event_index": 376,
                        "params": {
                            "asset": "FAIRMINTC",
                            "asset_longname": "",
                            "block_index": 172,
                            "call_date": 0,
                            "call_price": 0.0,
                            "callable": False,
                            "description": "",
                            "description_locked": False,
                            "divisible": True,
                            "fair_minting": True,
                            "fee_paid": 0,
                            "issuer": "$ADDRESS_1",
                            "locked": False,
                            "msg_index": 0,
                            "quantity": 3,
                            "reset": False,
                            "source": "$ADDRESS_2",
                            "status": "valid",
                            "transfer": False,
                            "tx_hash": "$TX_HASH",
                            "tx_index": 38,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "NEW_FAIRMINT",
                        "event_index": 375,
                        "params": {
                            "asset": "FAIRMINTC",
                            "block_index": 172,
                            "commission": 0,
                            "earn_quantity": 3,
                            "fairminter_tx_hash": "$FAIRMINTC_TX_HASH",
                            "paid_quantity": 1,
                            "source": "$ADDRESS_2",
                            "status": "valid",
                            "tx_hash": "$TX_HASH",
                            "tx_index": 38,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": 374,
                        "params": {
                            "address": "$ADDRESS_2",
                            "asset": "FAIRMINTC",
                            "block_index": 172,
                            "calling_function": "fairmint",
                            "event": "$TX_HASH",
                            "quantity": 3,
                            "tx_index": 38,
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": 373,
                        "params": {
                            "address": "$ADDRESS_1",
                            "asset": "XCP",
                            "block_index": 172,
                            "calling_function": "fairmint payment",
                            "event": "$TX_HASH",
                            "quantity": 1,
                            "tx_index": 38,
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": 372,
                        "params": {
                            "action": "fairmint payment",
                            "address": "$ADDRESS_2",
                            "asset": "XCP",
                            "block_index": 172,
                            "event": "$TX_HASH",
                            "quantity": 1,
                            "tx_index": 38,
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            }
        ],
    },
    {
        "title": "Mint FAIRMINTC",
        "transaction": "fairmint",
        "source": "$ADDRESS_2",
        "params": {
            "asset": "FAIRMINTC",
            "quantity": 11,
        },
        "controls": [
            {
                "url": "blocks/173/events?event_name=DEBIT,CREDIT,NEW_FAIRMINT,ASSET_ISSUANCE",
                "result": [
                    {
                        "event": "ASSET_ISSUANCE",
                        "event_index": 385,
                        "params": {
                            "asset": "FAIRMINTC",
                            "asset_longname": "",
                            "block_index": 173,
                            "call_date": 0,
                            "call_price": 0.0,
                            "callable": False,
                            "description": "",
                            "description_locked": False,
                            "divisible": True,
                            "fair_minting": True,
                            "fee_paid": 0,
                            "issuer": "$ADDRESS_1",
                            "locked": False,
                            "msg_index": 0,
                            "quantity": 11,
                            "reset": False,
                            "source": "$ADDRESS_2",
                            "status": "valid",
                            "transfer": False,
                            "tx_hash": "$TX_HASH",
                            "tx_index": 39,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "NEW_FAIRMINT",
                        "event_index": 384,
                        "params": {
                            "asset": "FAIRMINTC",
                            "block_index": 173,
                            "commission": 0,
                            "earn_quantity": 11,
                            "fairminter_tx_hash": "$FAIRMINTC_TX_HASH",
                            "paid_quantity": 3,
                            "source": "$ADDRESS_2",
                            "status": "valid",
                            "tx_hash": "$TX_HASH",
                            "tx_index": 39,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": 383,
                        "params": {
                            "address": "$ADDRESS_2",
                            "asset": "FAIRMINTC",
                            "block_index": 173,
                            "calling_function": "fairmint",
                            "event": "$TX_HASH",
                            "quantity": 11,
                            "tx_index": 39,
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": 382,
                        "params": {
                            "address": "$ADDRESS_1",
                            "asset": "XCP",
                            "block_index": 173,
                            "calling_function": "fairmint payment",
                            "event": "$TX_HASH",
                            "quantity": 3,
                            "tx_index": 39,
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": 381,
                        "params": {
                            "action": "fairmint payment",
                            "address": "$ADDRESS_2",
                            "asset": "XCP",
                            "block_index": 173,
                            "event": "$TX_HASH",
                            "quantity": 3,
                            "tx_index": 39,
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            }
        ],
    },
    {
        "title": "Create FAIRMINTD fairminter",
        "transaction": "fairminter",
        "source": "$ADDRESS_1",
        "params": {
            "asset": "FAIRMINTD",
            "price": 50,
            "quantity_by_price": 60,
        },
        "set_variables": {
            "FAIRMINTD_TX_HASH": "$TX_HASH",
        },
        "controls": [
            {
                "url": "blocks/174/events?event_name=DEBIT,ASSET_ISSUANCE,ASSET_CREATION,NEW_FAIRMINTER",
                "result": [
                    {
                        "event": "DEBIT",
                        "event_index": 393,
                        "params": {
                            "action": "fairminter fee",
                            "address": "$ADDRESS_1",
                            "asset": "XCP",
                            "block_index": 174,
                            "event": "$TX_HASH",
                            "quantity": 50000000,
                            "tx_index": 40,
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "ASSET_ISSUANCE",
                        "event_index": 392,
                        "params": {
                            "asset": "FAIRMINTD",
                            "asset_longname": "",
                            "block_index": 174,
                            "call_date": 0,
                            "call_price": 0,
                            "callable": False,
                            "description": "",
                            "divisible": True,
                            "fair_minting": True,
                            "fee_paid": 50000000.0,
                            "issuer": "$ADDRESS_1",
                            "locked": False,
                            "quantity": 0,
                            "reset": False,
                            "source": "$ADDRESS_1",
                            "status": "valid",
                            "transfer": False,
                            "tx_hash": "$TX_HASH",
                            "tx_index": 40,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "ASSET_CREATION",
                        "event_index": 391,
                        "params": {
                            "asset_id": "1046814266085",
                            "asset_longname": None,
                            "asset_name": "FAIRMINTD",
                            "block_index": 174,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "NEW_FAIRMINTER",
                        "event_index": 390,
                        "params": {
                            "asset": "FAIRMINTD",
                            "asset_longname": "",
                            "asset_parent": "",
                            "block_index": 174,
                            "burn_payment": False,
                            "description": "",
                            "divisible": True,
                            "end_block": 0,
                            "hard_cap": 0,
                            "lock_description": False,
                            "lock_quantity": False,
                            "max_mint_per_tx": 0,
                            "minted_asset_commission_int": 0,
                            "pre_minted": False,
                            "premint_quantity": 0,
                            "price": 50,
                            "quantity_by_price": 60,
                            "soft_cap": 0,
                            "soft_cap_deadline_block": 0,
                            "source": "$ADDRESS_1",
                            "start_block": 0,
                            "status": "open",
                            "tx_hash": "$TX_HASH",
                            "tx_index": 40,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            }
        ],
    },
    {
        "title": "Mint FAIRMINTD",
        "transaction": "fairmint",
        "source": "$ADDRESS_2",
        "params": {
            "asset": "FAIRMINTD",
            "quantity": 40,
        },
        "controls": [
            {
                "url": "blocks/175/events?event_name=DEBIT,CREDIT,NEW_FAIRMINT,ASSET_ISSUANCE",
                "result": [
                    {
                        "event": "ASSET_ISSUANCE",
                        "event_index": 402,
                        "params": {
                            "asset": "FAIRMINTD",
                            "asset_longname": "",
                            "block_index": 175,
                            "call_date": 0,
                            "call_price": 0.0,
                            "callable": False,
                            "description": "",
                            "description_locked": False,
                            "divisible": True,
                            "fair_minting": True,
                            "fee_paid": 0,
                            "issuer": "$ADDRESS_1",
                            "locked": False,
                            "msg_index": 0,
                            "quantity": 40,
                            "reset": False,
                            "source": "$ADDRESS_2",
                            "status": "valid",
                            "transfer": False,
                            "tx_hash": "$TX_HASH",
                            "tx_index": 41,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "NEW_FAIRMINT",
                        "event_index": 401,
                        "params": {
                            "asset": "FAIRMINTD",
                            "block_index": 175,
                            "commission": 0,
                            "earn_quantity": 40,
                            "fairminter_tx_hash": "$FAIRMINTD_TX_HASH",
                            "paid_quantity": 34,
                            "source": "$ADDRESS_2",
                            "status": "valid",
                            "tx_hash": "$TX_HASH",
                            "tx_index": 41,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": 400,
                        "params": {
                            "address": "$ADDRESS_2",
                            "asset": "FAIRMINTD",
                            "block_index": 175,
                            "calling_function": "fairmint",
                            "event": "$TX_HASH",
                            "quantity": 40,
                            "tx_index": 41,
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": 399,
                        "params": {
                            "address": "$ADDRESS_1",
                            "asset": "XCP",
                            "block_index": 175,
                            "calling_function": "fairmint payment",
                            "event": "$TX_HASH",
                            "quantity": 34,
                            "tx_index": 41,
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": 398,
                        "params": {
                            "action": "fairmint payment",
                            "address": "$ADDRESS_2",
                            "asset": "XCP",
                            "block_index": 175,
                            "event": "$TX_HASH",
                            "quantity": 34,
                            "tx_index": 41,
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            }
        ],
    },
]
