version: '3' 

services:
  bitcoind:
    image: kylemanna/bitcoind
    ports: 
      - "8332:8332" 
    command: 
      -  "-rpcallowip=0.0.0.0/0"
      -  "-rpcbind=0.0.0.0"
      -  "-rpcport=8332"
      -  "-rpcuser=bitcoinrpc"
      -  "-rpcpassword=rpc"
      -  "-listen=1"
      -  "-server=1"
      -  "-printtoconsole=1"
      -  "-addresstype=legacy"
      -  "-txindex=1"
      -  "-prune=0"
      -  "-dbcache=4000"
      -  "-mempoolfullrbf=1"

    volumes:
      - backend-data:/bitcoin/.bitcoin

  addrindexrs:
    image: counterparty/addrindexrs
    links:
      - bitcoind
    volumes:
      - addrindexrs-data:/var/addrindexrs-data
    ports:
      - "8432:8432" 
    environment:
      - "ADDRINDEXRS_TXID_LIMIT=15000"
      - "ADDRINDEXRS_JSONRPC_IMPORT=1"
      - "ADDRINDEXRS_NETWORK=bitcoin"
      - "ADDRINDEXRS_INDEXER_RPC_ADDR=0.0.0.0:8432"
      - "ADDRINDEXRS_DAEMON_RPC_ADDR=bitcoind:8332"
      - "ADDRINDEXRS_COOKIE=bitcoinrpc:rpc"
      - "RUST_BACKTRACE=full"

  counterparty-server:
    image: counterparty/counterparty-server
    links:
      - bitcoind
      - addrindexrs
    volumes:
      - counterparty-data:/root/.local/share/counterparty/
    command:
      - "--backend-user=bitcoinrpc"
      - "--backend-password=rpc"
      - "--indexd-connect=addrindexrs"
      - "--indexd-port=8432"
      - "--rpc-user=rpc"
      - "--rpc-password=rpc"
      - "--rpc-host=0.0.0.0"
      - "--log-file=1"
      - "--api-log-file=1"

volumes:
  backend-data:
  addrindexrs-data:
  counterparty-data:
