"""TABLE_REWRITES used by the compact-hash storage migration.

Holds the CREATE TABLE statements (with new BLOB column types) and the
column lists used by the migration. Split out from ``compact_hash_schema``
to keep individual modules under pylint's per-module line cap.
"""

# ---------------------------------------------------------------------------
# Table rewrites. Each entry contains:
#   - new CREATE TABLE statement (column types reflect BLOB(32) for hashes)
#   - the INSERT ... SELECT clause that converts hex -> BLOB via __hex_to_blob
#
# Most rewrites only touch column *types* and indexes (hex -> binary). The
# few tables that also drop a legacy hash column or replace it with a
# ``*_tx_index`` foreign key use a CUSTOM_INSERT_SELECT clause below.
# ---------------------------------------------------------------------------

# (table_name, columns_to_recreate, full_create_sql_with_new_types,
#  hex_columns, original_create_for_rollback)
#
# ``hex_columns`` is the subset of columns that need ``__hex_to_blob`` in the
# INSERT SELECT; all other columns are copied verbatim.

TABLE_REWRITES = [
    # assets: the legacy ``asset_id`` TEXT remains (it is the protocol id,
    # exposed verbatim by the API). A compact sequential ``asset_index``
    # INTEGER PRIMARY KEY is added: it is auto-assigned in stable insertion
    # order (see CUSTOM_INSERT_SELECT, ``ORDER BY rowid``) and is the FK target
    # every other table's asset column now points at. Must be FIRST in this
    # list so the new ``assets`` table is fully populated before any other
    # rewrite resolves an asset name to its ``asset_index``.
    (
        "assets",
        ("asset_id", "asset_name", "block_index", "asset_longname"),
        """CREATE TABLE assets(
                          asset_index INTEGER PRIMARY KEY,
                          asset_id TEXT UNIQUE,
                          asset_name TEXT UNIQUE,
                          block_index INTEGER,
                          asset_longname TEXT)""",
        (),
    ),
    # balances/credits/debits: high-volume tables whose ``asset`` name TEXT is
    # replaced by the compact ``asset_index`` INTEGER. They have no hash
    # columns, so the original hex->BLOB pass skipped them; they are added here
    # purely for the asset normalization (see ASSET_NAME_COLUMNS).
    (
        "balances",
        ("address", "asset", "quantity", "block_index", "tx_index", "utxo", "utxo_address"),
        """CREATE TABLE balances(
                          address TEXT,
                          asset INTEGER,
                          quantity INTEGER,
                          block_index INTEGER,
                          tx_index INTEGER,
                          utxo TEXT,
                          utxo_address TEXT)""",
        (),
    ),
    (
        "credits",
        (
            "block_index",
            "address",
            "asset",
            "quantity",
            "calling_function",
            "event",
            "tx_index",
            "utxo",
            "utxo_address",
        ),
        """CREATE TABLE credits(
                          block_index INTEGER,
                          address TEXT,
                          asset INTEGER,
                          quantity INTEGER,
                          calling_function TEXT,
                          event TEXT,
                          tx_index INTEGER,
                          utxo TEXT,
                          utxo_address TEXT)""",
        (),
    ),
    (
        "debits",
        (
            "block_index",
            "address",
            "asset",
            "quantity",
            "action",
            "event",
            "tx_index",
            "utxo",
            "utxo_address",
        ),
        """CREATE TABLE debits(
                          block_index INTEGER,
                          address TEXT,
                          asset INTEGER,
                          quantity INTEGER,
                          action TEXT,
                          event TEXT,
                          tx_index INTEGER,
                          utxo TEXT,
                          utxo_address TEXT)""",
        (),
    ),
    # blocks: 5 hash columns
    (
        "blocks",
        (
            "block_index",
            "block_hash",
            "block_time",
            "ledger_hash",
            "txlist_hash",
            "messages_hash",
            "previous_block_hash",
            "difficulty",
            "transaction_count",
        ),
        """CREATE TABLE blocks(
                          block_index INTEGER UNIQUE,
                          block_hash BLOB UNIQUE,
                          block_time INTEGER,
                          ledger_hash BLOB,
                          txlist_hash BLOB,
                          messages_hash BLOB,
                          previous_block_hash BLOB UNIQUE,
                          difficulty INTEGER,
                          transaction_count INTEGER,
                          PRIMARY KEY (block_index, block_hash))""",
        ("block_hash", "ledger_hash", "txlist_hash", "messages_hash", "previous_block_hash"),
    ),
    # transactions: tx_hash BLOB; block_hash dropped. Doing the column drop
    # in the same pass avoids a second table-rewrite of the largest table
    # in the schema.
    (
        "transactions",
        (
            "tx_index",
            "tx_hash",
            "block_index",
            "block_time",
            "source",
            "destination",
            "btc_amount",
            "fee",
            "data",
            "supported",
            "utxos_info",
            "transaction_type",
        ),
        """CREATE TABLE transactions(
                          tx_index INTEGER UNIQUE,
                          tx_hash BLOB UNIQUE,
                          block_index INTEGER,
                          block_time INTEGER,
                          source TEXT,
                          destination TEXT,
                          btc_amount INTEGER,
                          fee INTEGER,
                          data BLOB,
                          supported BOOL DEFAULT 1,
                          utxos_info TEXT,
                          transaction_type TEXT,
                          FOREIGN KEY (block_index) REFERENCES blocks(block_index),
                          PRIMARY KEY (tx_index))""",
        ("tx_hash",),
    ),
    # mempool_transactions: tx_hash BLOB; block_hash stays TEXT because it
    # stores the literal sentinel "mempool" (not a real 32-byte hash).
    # Converting it with __hex_to_blob would fail (not valid hex).
    (
        "mempool_transactions",
        (
            "tx_index",
            "tx_hash",
            "block_index",
            "block_hash",
            "block_time",
            "source",
            "destination",
            "btc_amount",
            "fee",
            "data",
            "supported",
            "utxos_info",
            "transaction_type",
        ),
        """CREATE TABLE mempool_transactions(
                          tx_index INTEGER UNIQUE,
                          tx_hash BLOB UNIQUE,
                          block_index INTEGER,
                          block_hash TEXT,
                          block_time INTEGER,
                          source TEXT,
                          destination TEXT,
                          btc_amount INTEGER,
                          fee INTEGER,
                          data BLOB,
                          supported BOOL DEFAULT 1,
                          utxos_info TEXT, transaction_type TEXT)""",
        ("tx_hash",),
    ),
    # mempool: tx_hash BLOB.
    (
        "mempool",
        ("tx_hash", "command", "category", "bindings", "timestamp", "event", "addresses"),
        """CREATE TABLE mempool(
                          tx_hash BLOB,
                          command TEXT,
                          category TEXT,
                          bindings TEXT,
                          timestamp INTEGER,
                          event TEXT, addresses TEXT)""",
        ("tx_hash",),
    ),
    # messages: tx_hash dropped (replaced by tx_index FK), event_hash BLOB.
    # Insert from the old row picking tx_index via JOIN on transactions.tx_hash.
    # The messages table requires the BLOB conversion for event_hash in any
    # case, so doing the column drop at the same time avoids two separate
    # full-table rewrites on heavy installs.
    (
        "messages",
        (
            "message_index",
            "block_index",
            "command",
            "category",
            "bindings",
            "timestamp",
            "event",
            "tx_index",
            "event_hash",
        ),
        """CREATE TABLE messages(
                          message_index INTEGER PRIMARY KEY,
                          block_index INTEGER,
                          command TEXT,
                          category TEXT,
                          bindings TEXT,
                          timestamp INTEGER,
                          event TEXT,
                          tx_index INTEGER,
                          event_hash BLOB)""",
        ("event_hash",),
        # custom insert: ``tx_index`` is resolved from the old hex
        # ``tx_hash`` via a join below.
    ),
    # orders
    (
        "orders",
        (
            "tx_index",
            "tx_hash",
            "block_index",
            "source",
            "give_asset",
            "give_quantity",
            "give_remaining",
            "get_asset",
            "get_quantity",
            "get_remaining",
            "expiration",
            "expire_index",
            "fee_required",
            "fee_required_remaining",
            "fee_provided",
            "fee_provided_remaining",
            "status",
        ),
        """CREATE TABLE orders(
                            tx_index INTEGER,
                            tx_hash BLOB,
                            block_index INTEGER,
                            source TEXT,
                            give_asset INTEGER,
                            give_quantity INTEGER,
                            give_remaining INTEGER,
                            get_asset INTEGER,
                            get_quantity INTEGER,
                            get_remaining INTEGER,
                            expiration INTEGER,
                            expire_index INTEGER,
                            fee_required INTEGER,
                            fee_required_remaining INTEGER,
                            fee_provided INTEGER,
                            fee_provided_remaining INTEGER,
                            status TEXT)""",
        ("tx_hash",),
    ),
    # order_matches: tx0_hash, tx1_hash BLOB; the composite TEXT ``id`` is
    # dropped -- the match is keyed by the existing ``(tx0_index, tx1_index)``
    # pair. The text id is reconstructed on read via
    # ``hex_lower(tx0_hash) || '_' || hex_lower(tx1_hash)``.
    (
        "order_matches",
        (
            "tx0_index",
            "tx0_hash",
            "tx0_address",
            "tx1_index",
            "tx1_hash",
            "tx1_address",
            "forward_asset",
            "forward_quantity",
            "backward_asset",
            "backward_quantity",
            "tx0_block_index",
            "tx1_block_index",
            "block_index",
            "tx0_expiration",
            "tx1_expiration",
            "match_expire_index",
            "fee_paid",
            "status",
        ),
        """CREATE TABLE order_matches(
                                    tx0_index INTEGER,
                                    tx0_hash BLOB,
                                    tx0_address TEXT,
                                    tx1_index INTEGER,
                                    tx1_hash BLOB,
                                    tx1_address TEXT,
                                    forward_asset INTEGER,
                                    forward_quantity INTEGER,
                                    backward_asset INTEGER,
                                    backward_quantity INTEGER,
                                    tx0_block_index INTEGER,
                                    tx1_block_index INTEGER,
                                    block_index INTEGER,
                                    tx0_expiration INTEGER,
                                    tx1_expiration INTEGER,
                                    match_expire_index INTEGER,
                                    fee_paid INTEGER,
                                    status TEXT)""",
        ("tx0_hash", "tx1_hash"),
    ),
    (
        "order_expirations",
        ("order_hash", "source", "block_index"),
        """CREATE TABLE order_expirations(
                                        order_hash BLOB PRIMARY KEY,
                                        source TEXT,
                                        block_index INTEGER,
                                        FOREIGN KEY (block_index) REFERENCES blocks(block_index))""",
        ("order_hash",),
    ),
    (
        "btcpays",
        (
            "tx_index",
            "tx_hash",
            "block_index",
            "source",
            "destination",
            "btc_amount",
            "order_match_tx0_index",
            "order_match_tx1_index",
            "status",
        ),
        """CREATE TABLE btcpays(
                          tx_index INTEGER PRIMARY KEY,
                          tx_hash BLOB UNIQUE,
                          block_index INTEGER,
                          source TEXT,
                          destination TEXT,
                          btc_amount INTEGER,
                          order_match_tx0_index INTEGER,
                          order_match_tx1_index INTEGER,
                          status TEXT,
                          FOREIGN KEY (tx_index) REFERENCES transactions(tx_index))""",
        ("tx_hash",),
    ),
    (
        "issuances",
        (
            "tx_index",
            "tx_hash",
            "msg_index",
            "block_index",
            "asset",
            "quantity",
            "divisible",
            "source",
            "issuer",
            "transfer",
            "callable",
            "call_date",
            "call_price",
            "description",
            "fee_paid",
            "status",
            "asset_longname",
            "description_locked",
            "fair_minting",
            "asset_events",
            "locked",
            "reset",
            "mime_type",
        ),
        """CREATE TABLE issuances(
                tx_index INTEGER,
                tx_hash BLOB,
                msg_index INTEGER DEFAULT 0,
                block_index INTEGER,
                asset INTEGER,
                quantity INTEGER,
                divisible BOOL,
                source TEXT,
                issuer TEXT,
                transfer BOOL,
                callable BOOL,
                call_date INTEGER,
                call_price REAL,
                description TEXT,
                fee_paid INTEGER,
                status TEXT,
                asset_longname TEXT,
                description_locked BOOL,
                fair_minting BOOL DEFAULT 0,
                asset_events TEXT,
                locked BOOL DEFAULT FALSE,
                reset BOOL DEFAULT FALSE,
                mime_type TEXT DEFAULT "text/plain",
                PRIMARY KEY (tx_index, msg_index),
                UNIQUE (tx_hash, msg_index)
            )""",
        ("tx_hash",),
    ),
    (
        "broadcasts",
        (
            "tx_index",
            "tx_hash",
            "block_index",
            "source",
            "timestamp",
            "value",
            "fee_fraction_int",
            "text",
            "locked",
            "status",
            "mime_type",
        ),
        """CREATE TABLE broadcasts(
                          tx_index INTEGER PRIMARY KEY,
                          tx_hash BLOB UNIQUE,
                          block_index INTEGER,
                          source TEXT,
                          timestamp INTEGER,
                          value REAL,
                          fee_fraction_int INTEGER,
                          text TEXT,
                          locked BOOL,
                          status TEXT,
                          mime_type TEXT DEFAULT "text/plain",
                          FOREIGN KEY (tx_index) REFERENCES transactions(tx_index))""",
        ("tx_hash",),
    ),
    (
        "bets",
        (
            "tx_index",
            "tx_hash",
            "block_index",
            "source",
            "feed_address",
            "bet_type",
            "deadline",
            "wager_quantity",
            "wager_remaining",
            "counterwager_quantity",
            "counterwager_remaining",
            "target_value",
            "leverage",
            "expiration",
            "expire_index",
            "fee_fraction_int",
            "status",
        ),
        """CREATE TABLE bets(
                            tx_index INTEGER,
                            tx_hash BLOB,
                            block_index INTEGER,
                            source TEXT,
                            feed_address TEXT,
                            bet_type INTEGER,
                            deadline INTEGER,
                            wager_quantity INTEGER,
                            wager_remaining INTEGER,
                            counterwager_quantity INTEGER,
                            counterwager_remaining INTEGER,
                            target_value REAL,
                            leverage INTEGER,
                            expiration INTEGER,
                            expire_index INTEGER,
                            fee_fraction_int INTEGER,
                            status TEXT)""",
        ("tx_hash",),
    ),
    (
        "bet_matches",
        (
            "tx0_index",
            "tx0_hash",
            "tx0_address",
            "tx1_index",
            "tx1_hash",
            "tx1_address",
            "tx0_bet_type",
            "tx1_bet_type",
            "feed_address",
            "initial_value",
            "deadline",
            "target_value",
            "leverage",
            "forward_quantity",
            "backward_quantity",
            "tx0_block_index",
            "tx1_block_index",
            "block_index",
            "tx0_expiration",
            "tx1_expiration",
            "match_expire_index",
            "fee_fraction_int",
            "status",
        ),
        """CREATE TABLE bet_matches(
                                tx0_index INTEGER,
                                tx0_hash BLOB,
                                tx0_address TEXT,
                                tx1_index INTEGER,
                                tx1_hash BLOB,
                                tx1_address TEXT,
                                tx0_bet_type INTEGER,
                                tx1_bet_type INTEGER,
                                feed_address TEXT,
                                initial_value INTEGER,
                                deadline INTEGER,
                                target_value REAL,
                                leverage INTEGER,
                                forward_quantity INTEGER,
                                backward_quantity INTEGER,
                                tx0_block_index INTEGER,
                                tx1_block_index INTEGER,
                                block_index INTEGER,
                                tx0_expiration INTEGER,
                                tx1_expiration INTEGER,
                                match_expire_index INTEGER,
                                fee_fraction_int INTEGER,
                                status TEXT)""",
        ("tx0_hash", "tx1_hash"),
    ),
    (
        "bet_expirations",
        ("bet_index", "bet_hash", "source", "block_index"),
        """CREATE TABLE bet_expirations(
                                    bet_index INTEGER PRIMARY KEY,
                                    bet_hash BLOB UNIQUE,
                                    source TEXT,
                                    block_index INTEGER,
                                    FOREIGN KEY (block_index) REFERENCES blocks(block_index))""",
        ("bet_hash",),
    ),
    (
        "dividends",
        (
            "tx_index",
            "tx_hash",
            "block_index",
            "source",
            "asset",
            "dividend_asset",
            "quantity_per_unit",
            "fee_paid",
            "status",
        ),
        """CREATE TABLE dividends(
                          tx_index INTEGER PRIMARY KEY,
                          tx_hash BLOB UNIQUE,
                          block_index INTEGER,
                          source TEXT,
                          asset INTEGER,
                          dividend_asset INTEGER,
                          quantity_per_unit INTEGER,
                          fee_paid INTEGER,
                          status TEXT,
                          FOREIGN KEY (tx_index) REFERENCES transactions(tx_index))""",
        ("tx_hash",),
    ),
    (
        "burns",
        ("tx_index", "tx_hash", "block_index", "source", "burned", "earned", "status"),
        """CREATE TABLE burns(
                          tx_index INTEGER PRIMARY KEY,
                          tx_hash BLOB UNIQUE,
                          block_index INTEGER,
                          source TEXT,
                          burned INTEGER,
                          earned INTEGER,
                          status TEXT,
                          FOREIGN KEY (tx_index) REFERENCES transactions(tx_index))""",
        ("tx_hash",),
    ),
    # cancels: ``offer_hash`` becomes ``offer_tx_index``; resolved from the
    # old hex offer_hash via a JOIN below.
    (
        "cancels",
        (
            "tx_index",
            "tx_hash",
            "block_index",
            "source",
            "offer_tx_index",
            "status",
        ),
        """CREATE TABLE cancels(
                          tx_index INTEGER PRIMARY KEY,
                          tx_hash BLOB UNIQUE,
                          block_index INTEGER,
                          source TEXT,
                          offer_tx_index INTEGER,
                          status TEXT,
                          FOREIGN KEY (tx_index) REFERENCES transactions(tx_index))""",
        ("tx_hash",),
    ),
    (
        "rps",
        (
            "tx_index",
            "tx_hash",
            "block_index",
            "source",
            "possible_moves",
            "wager",
            "move_random_hash",
            "expiration",
            "expire_index",
            "status",
        ),
        """CREATE TABLE rps(
                            tx_index INTEGER,
                            tx_hash BLOB,
                            block_index INTEGER,
                            source TEXT,
                            possible_moves INTEGER,
                            wager INTEGER,
                            move_random_hash BLOB,
                            expiration INTEGER,
                            expire_index INTEGER,
                            status TEXT)""",
        ("tx_hash", "move_random_hash"),
    ),
    (
        "rps_matches",
        (
            "tx0_index",
            "tx0_hash",
            "tx0_address",
            "tx1_index",
            "tx1_hash",
            "tx1_address",
            "tx0_move_random_hash",
            "tx1_move_random_hash",
            "wager",
            "possible_moves",
            "tx0_block_index",
            "tx1_block_index",
            "block_index",
            "tx0_expiration",
            "tx1_expiration",
            "match_expire_index",
            "status",
        ),
        """CREATE TABLE rps_matches(
                                tx0_index INTEGER,
                                tx0_hash BLOB,
                                tx0_address TEXT,
                                tx1_index INTEGER,
                                tx1_hash BLOB,
                                tx1_address TEXT,
                                tx0_move_random_hash BLOB,
                                tx1_move_random_hash BLOB,
                                wager INTEGER,
                                possible_moves INTEGER,
                                tx0_block_index INTEGER,
                                tx1_block_index INTEGER,
                                block_index INTEGER,
                                tx0_expiration INTEGER,
                                tx1_expiration INTEGER,
                                match_expire_index INTEGER,
                                status TEXT)""",
        ("tx0_hash", "tx1_hash", "tx0_move_random_hash", "tx1_move_random_hash"),
    ),
    (
        "rps_expirations",
        ("rps_index", "rps_hash", "source", "block_index"),
        """CREATE TABLE rps_expirations(
                                    rps_index INTEGER PRIMARY KEY,
                                    rps_hash BLOB UNIQUE,
                                    source TEXT,
                                    block_index INTEGER,
                                    FOREIGN KEY (block_index) REFERENCES blocks(block_index))""",
        ("rps_hash",),
    ),
    (
        "rpsresolves",
        (
            "tx_index",
            "tx_hash",
            "block_index",
            "source",
            "move",
            "random",
            "rps_match_tx0_index",
            "rps_match_tx1_index",
            "status",
        ),
        """CREATE TABLE rpsresolves(
                          tx_index INTEGER PRIMARY KEY,
                          tx_hash BLOB UNIQUE,
                          block_index INTEGER,
                          source TEXT,
                          move INTEGER,
                          random TEXT,
                          rps_match_tx0_index INTEGER,
                          rps_match_tx1_index INTEGER,
                          status TEXT,
                          FOREIGN KEY (tx_index) REFERENCES transactions(tx_index))""",
        ("tx_hash",),
    ),
    (
        "sweeps",
        (
            "tx_index",
            "tx_hash",
            "block_index",
            "source",
            "destination",
            "flags",
            "status",
            "memo",
            "fee_paid",
        ),
        """CREATE TABLE sweeps(
                          tx_index INTEGER PRIMARY KEY,
                          tx_hash BLOB UNIQUE,
                          block_index INTEGER,
                          source TEXT,
                          destination TEXT,
                          flags INTEGER,
                          status TEXT,
                          memo BLOB,
                          fee_paid INTEGER,
                          FOREIGN KEY (tx_index) REFERENCES transactions(tx_index))""",
        ("tx_hash",),
    ),
    (
        "dispensers",
        (
            "tx_index",
            "tx_hash",
            "block_index",
            "source",
            "asset",
            "give_quantity",
            "escrow_quantity",
            "satoshirate",
            "status",
            "give_remaining",
            "oracle_address",
            "last_status_tx_hash",
            "origin",
            "dispense_count",
            "last_status_tx_source",
            "close_block_index",
        ),
        """CREATE TABLE dispensers(
                                tx_index INTEGER,
                                tx_hash BLOB,
                                block_index INTEGER,
                                source TEXT,
                                asset INTEGER,
                                give_quantity INTEGER,
                                escrow_quantity INTEGER,
                                satoshirate INTEGER,
                                status INTEGER,
                                give_remaining INTEGER,
                                oracle_address TEXT,
                                last_status_tx_hash BLOB,
                                origin TEXT,
                                dispense_count INTEGER DEFAULT 0,
                                last_status_tx_source TEXT,
                                close_block_index INTEGER)""",
        ("tx_hash", "last_status_tx_hash"),
    ),
    (
        "dispenses",
        (
            "tx_index",
            "dispense_index",
            "tx_hash",
            "block_index",
            "source",
            "destination",
            "asset",
            "dispense_quantity",
            "dispenser_tx_index",
            "btc_amount",
        ),
        """CREATE TABLE dispenses (
                                tx_index INTEGER,
                                dispense_index INTEGER,
                                tx_hash BLOB,
                                block_index INTEGER,
                                source TEXT,
                                destination TEXT,
                                asset INTEGER,
                                dispense_quantity INTEGER,
                                dispenser_tx_index INTEGER,
                                btc_amount INTEGER,
                                PRIMARY KEY (tx_index, dispense_index, source, destination),
                                FOREIGN KEY (tx_index) REFERENCES transactions(tx_index))""",
        ("tx_hash",),
    ),
    (
        "dispenser_refills",
        (
            "tx_index",
            "tx_hash",
            "block_index",
            "source",
            "destination",
            "asset",
            "dispense_quantity",
            "dispenser_tx_index",
        ),
        """CREATE TABLE dispenser_refills(
                                        tx_index INTEGER,
                                        tx_hash BLOB,
                                        block_index INTEGER,
                                        source TEXT,
                                        destination TEXT,
                                        asset INTEGER,
                                        dispense_quantity INTEGER,
                                        dispenser_tx_index INTEGER,
                                        PRIMARY KEY (tx_index, source, destination),
                                        FOREIGN KEY (tx_index)
                                            REFERENCES transactions(tx_index))""",
        ("tx_hash",),
    ),
    (
        "fairminters",
        (
            "tx_hash",
            "tx_index",
            "block_index",
            "source",
            "asset",
            "asset_parent",
            "asset_longname",
            "description",
            "price",
            "quantity_by_price",
            "hard_cap",
            "burn_payment",
            "max_mint_per_tx",
            "premint_quantity",
            "start_block",
            "end_block",
            "minted_asset_commission_int",
            "soft_cap",
            "soft_cap_deadline_block",
            "lock_description",
            "lock_quantity",
            "divisible",
            "pre_minted",
            "status",
            "max_mint_per_address",
            "mime_type",
        ),
        """CREATE TABLE fairminters (
            tx_hash BLOB,
            tx_index INTEGER,
            block_index INTEGER,
            source TEXT,
            asset INTEGER,
            asset_parent INTEGER,
            asset_longname TEXT,
            description TEXT,
            price INTEGER,
            quantity_by_price INTEGER,
            hard_cap INTEGER,
            burn_payment BOOL,
            max_mint_per_tx INTEGER,
            premint_quantity INTEGER,
            start_block INTEGER,
            end_block INTEGER,
            minted_asset_commission_int INTEGER,
            soft_cap INTEGER,
            soft_cap_deadline_block INTEGER,
            lock_description BOOL,
            lock_quantity BOOL,
            divisible BOOL,
            pre_minted BOOL DEFAULT 0,
            status TEXT,
            max_mint_per_address INTEGER,
            mime_type TEXT DEFAULT "text/plain"
        )""",
        ("tx_hash",),
    ),
    (
        "fairmints",
        (
            "tx_hash",
            "tx_index",
            "block_index",
            "source",
            "fairminter_tx_index",
            "asset",
            "earn_quantity",
            "paid_quantity",
            "commission",
            "status",
        ),
        """CREATE TABLE fairmints (
            tx_hash BLOB PRIMARY KEY,
            tx_index INTEGER,
            block_index INTEGER,
            source TEXT,
            fairminter_tx_index INTEGER,
            asset INTEGER,
            earn_quantity INTEGER,
            paid_quantity INTEGER,
            commission INTEGER,
            status TEXT
        )""",
        ("tx_hash",),
    ),
    (
        "sends",
        (
            "tx_index",
            "tx_hash",
            "block_index",
            "source",
            "destination",
            "asset",
            "quantity",
            "status",
            "msg_index",
            "memo",
            "fee_paid",
            "send_type",
            "source_address",
            "destination_address",
        ),
        """CREATE TABLE "sends"(
                              tx_index INTEGER,
                              tx_hash BLOB,
                              block_index INTEGER,
                              source TEXT,
                              destination TEXT,
                              asset INTEGER,
                              quantity INTEGER,
                              status TEXT,
                              msg_index INTEGER DEFAULT 0,
                              memo BLOB,
                              fee_paid INTEGER DEFAULT 0,
                              send_type TEXT,
                              source_address TEXT,
                              destination_address TEXT,
                              PRIMARY KEY (tx_index, msg_index),
                              FOREIGN KEY (tx_index) REFERENCES transactions(tx_index),
                              UNIQUE (tx_hash, msg_index) ON CONFLICT FAIL)""",
        ("tx_hash",),
    ),
    (
        "destructions",
        (
            "tx_index",
            "tx_hash",
            "block_index",
            "source",
            "asset",
            "quantity",
            "tag",
            "status",
        ),
        """CREATE TABLE destructions(
            tx_index INTEGER,
            tx_hash BLOB,
            block_index INTEGER,
            source TEXT,
            asset INTEGER,
            quantity INTEGER,
            tag TEXT,
            status TEXT
        )""",
        ("tx_hash",),
    ),
    (
        "transaction_outputs",
        ("tx_index", "block_index", "out_index", "destination", "btc_amount"),
        """CREATE TABLE transaction_outputs(
                        tx_index INTEGER,
                        block_index INTEGER,
                        out_index INTEGER,
                        destination TEXT,
                        btc_amount INTEGER,
                        PRIMARY KEY (tx_index, out_index),
                        FOREIGN KEY (tx_index) REFERENCES transactions(tx_index))""",
        (),
    ),
    (
        "pools",
        (
            "tx_index",
            "tx_hash",
            "block_index",
            "source",
            "asset_a",
            "asset_b",
            "reserve_a",
            "reserve_b",
            "lp_asset",
        ),
        """CREATE TABLE pools(
    tx_index INTEGER,
    tx_hash BLOB,
    block_index INTEGER,
    source TEXT,
    asset_a INTEGER,
    asset_b INTEGER,
    reserve_a INTEGER,
    reserve_b INTEGER,
    lp_asset TEXT
)""",
        ("tx_hash",),
    ),
    (
        "pool_deposits",
        (
            "tx_index",
            "tx_hash",
            "block_index",
            "source",
            "asset_a",
            "asset_b",
            "quantity_a",
            "quantity_b",
            "quantity_minted",
            "status",
        ),
        """CREATE TABLE pool_deposits(
    tx_index INTEGER,
    tx_hash BLOB,
    block_index INTEGER,
    source TEXT,
    asset_a INTEGER,
    asset_b INTEGER,
    quantity_a INTEGER,
    quantity_b INTEGER,
    quantity_minted INTEGER,
    status TEXT
)""",
        ("tx_hash",),
    ),
    (
        "pool_withdrawals",
        (
            "tx_index",
            "tx_hash",
            "block_index",
            "source",
            "asset_a",
            "asset_b",
            "quantity_destroyed",
            "quantity_a",
            "quantity_b",
            "status",
        ),
        """CREATE TABLE pool_withdrawals(
    tx_index INTEGER,
    tx_hash BLOB,
    block_index INTEGER,
    source TEXT,
    asset_a INTEGER,
    asset_b INTEGER,
    quantity_destroyed INTEGER,
    quantity_a INTEGER,
    quantity_b INTEGER,
    status TEXT
)""",
        ("tx_hash",),
    ),
    (
        "pool_matches",
        (
            "tx_index",
            "tx_hash",
            "block_index",
            "source",
            "asset_a",
            "asset_b",
            "forward_asset",
            "forward_quantity",
            "backward_asset",
            "backward_quantity",
            "fee_quantity",
            "fee_bps",
            "order_tx_index",
            "status",
        ),
        """CREATE TABLE pool_matches(
    tx_index INTEGER,
    tx_hash BLOB,
    block_index INTEGER,
    source TEXT,
    asset_a INTEGER,
    asset_b INTEGER,
    forward_asset INTEGER,
    forward_quantity INTEGER,
    backward_asset INTEGER,
    backward_quantity INTEGER,
    fee_quantity INTEGER,
    fee_bps INTEGER,
    order_tx_index INTEGER,
    status TEXT
)""",
        ("tx_hash",),
    ),
    # ------------------------------------------------------------------
    # Composite match-id normalization: the four tables below referenced a
    # match through a single TEXT ``*_match_id`` (``tx0hash_tx1hash``). They
    # are rewritten to a ``(*_tx0_index, *_tx1_index)`` integer pair resolved
    # via JOIN on ``transactions`` (see CUSTOM_INSERT_SELECT). They have no
    # hash columns of their own, which is why they were skipped by the
    # original hex->BLOB pass.
    # ------------------------------------------------------------------
    (
        "order_match_expirations",
        (
            "order_match_tx0_index",
            "order_match_tx1_index",
            "tx0_address",
            "tx1_address",
            "block_index",
        ),
        """CREATE TABLE order_match_expirations(
                                          order_match_tx0_index INTEGER,
                                          order_match_tx1_index INTEGER,
                                          tx0_address TEXT,
                                          tx1_address TEXT,
                                          block_index INTEGER,
                                          PRIMARY KEY (order_match_tx0_index, order_match_tx1_index),
                                          FOREIGN KEY (block_index) REFERENCES blocks(block_index))""",
        (),
    ),
    (
        "bet_match_expirations",
        (
            "bet_match_tx0_index",
            "bet_match_tx1_index",
            "tx0_address",
            "tx1_address",
            "block_index",
        ),
        """CREATE TABLE bet_match_expirations(
                                          bet_match_tx0_index INTEGER,
                                          bet_match_tx1_index INTEGER,
                                          tx0_address TEXT,
                                          tx1_address TEXT,
                                          block_index INTEGER,
                                          PRIMARY KEY (bet_match_tx0_index, bet_match_tx1_index),
                                          FOREIGN KEY (block_index) REFERENCES blocks(block_index))""",
        (),
    ),
    (
        "rps_match_expirations",
        (
            "rps_match_tx0_index",
            "rps_match_tx1_index",
            "tx0_address",
            "tx1_address",
            "block_index",
        ),
        """CREATE TABLE rps_match_expirations(
                                          rps_match_tx0_index INTEGER,
                                          rps_match_tx1_index INTEGER,
                                          tx0_address TEXT,
                                          tx1_address TEXT,
                                          block_index INTEGER,
                                          PRIMARY KEY (rps_match_tx0_index, rps_match_tx1_index),
                                          FOREIGN KEY (block_index) REFERENCES blocks(block_index))""",
        (),
    ),
    (
        "bet_match_resolutions",
        (
            "bet_match_tx0_index",
            "bet_match_tx1_index",
            "bet_match_type_id",
            "block_index",
            "winner",
            "settled",
            "bull_credit",
            "bear_credit",
            "escrow_less_fee",
            "fee",
        ),
        """CREATE TABLE bet_match_resolutions(
                                          bet_match_tx0_index INTEGER,
                                          bet_match_tx1_index INTEGER,
                                          bet_match_type_id INTEGER,
                                          block_index INTEGER,
                                          winner TEXT,
                                          settled BOOL,
                                          bull_credit INTEGER,
                                          bear_credit INTEGER,
                                          escrow_less_fee INTEGER,
                                          fee INTEGER,
                                          PRIMARY KEY (bet_match_tx0_index, bet_match_tx1_index),
                                          FOREIGN KEY (block_index) REFERENCES blocks(block_index))""",
        (),
    ),
]


# ---------------------------------------------------------------------------
# Asset normalization: columns that store an asset *name* (TEXT) and are
# rewritten to the compact integer ``asset_index`` foreign key on ``assets``.
#
# Single source of truth shared by:
#   * the migration (``0010``): the auto INSERT/SELECT path resolves each of
#     these columns to its ``asset_index`` via a subquery on the new ``assets``
#     table (only for columns also present in the table's column list, so the
#     not-yet-added ``fairminters.lp_asset`` is naturally skipped at migration
#     time and handled at runtime once ``0011`` adds it).
#   * the write path (``ledger.events._prepare_record_for_insert``): converts
#     the in-memory asset name to its ``asset_index`` just before INSERT.
#
# ``assets``/``assets_info`` are intentionally absent: ``asset_id``/``asset_name``
# there are the source-of-truth values, not foreign keys.
# ---------------------------------------------------------------------------
ASSET_NAME_COLUMNS = {
    "balances": ("asset",),
    "credits": ("asset",),
    "debits": ("asset",),
    "sends": ("asset",),
    "orders": ("give_asset", "get_asset"),
    "order_matches": ("forward_asset", "backward_asset"),
    "issuances": ("asset",),
    "dividends": ("asset", "dividend_asset"),
    "dispensers": ("asset",),
    "dispenses": ("asset",),
    "dispenser_refills": ("asset",),
    # NB: ``lp_asset`` (on ``fairminters``/``pools``) is intentionally NOT
    # normalized: an LP token is referenced (earmarked on the fairminter)
    # before it is created when the pool opens, so it cannot resolve to an
    # ``asset_index`` at write time. LP names are numeric (``A...``) anyway, so
    # the saving would be marginal. It stays a TEXT asset name.
    "fairminters": ("asset", "asset_parent"),
    "fairmints": ("asset",),
    "destructions": ("asset",),
    "pools": ("asset_a", "asset_b"),
    "pool_deposits": ("asset_a", "asset_b"),
    "pool_withdrawals": ("asset_a", "asset_b"),
    "pool_matches": ("asset_a", "asset_b", "forward_asset", "backward_asset"),
}
