SCENARIO = [
    {
        "title": "Open Sell XCP for BTC order 2",
        "transaction": "order",
        "source": "$ADDRESS_1",
        "params": {
            "give_asset": "XCP",
            "give_quantity": 10000,
            "get_asset": "BTC",
            "get_quantity": 10000,
            "expiration": 21,
            "fee_required": 0,
        },
        "set_variables": {
            "ORDER_3_HASH": "$TX_HASH",
            "ORDER_3_TX_INDEX": "$TX_INDEX",
            "ORDER_3_BLOCK_INDEX": "$BLOCK_INDEX",
            "ORDER_3_EXPIRATION_BLOCK_INDEX": "$BLOCK_INDEX + 21",
        },
        "controls": [
            {
                "url": "blocks/$BLOCK_INDEX/events?event_name=OPEN_ORDER,DEBIT,CREDIT",
                "result": [
                    {
                        "event": "OPEN_ORDER",
                        "event_index": "$EVENT_INDEX_4",
                        "params": {
                            "block_index": "$BLOCK_INDEX",
                            "expiration": 21,
                            "expire_index": "$ORDER_3_EXPIRATION_BLOCK_INDEX",
                            "fee_provided": 10000,
                            "fee_provided_remaining": 10000,
                            "fee_required": 0,
                            "fee_required_remaining": 0,
                            "get_asset": "BTC",
                            "get_quantity": 10000,
                            "get_remaining": 10000,
                            "give_asset": "XCP",
                            "give_quantity": 10000,
                            "give_remaining": 10000,
                            "source": "$ADDRESS_1",
                            "status": "open",
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": "$EVENT_INDEX_3",
                        "params": {
                            "action": "open order",
                            "address": "$ADDRESS_1",
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "event": "$TX_HASH",
                            "quantity": 10000,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            },
        ],
    },
    {
        "title": "Open Buy XCP for BTC order 2",
        "transaction": "order",
        "source": "$ADDRESS_2",
        "params": {
            "give_asset": "BTC",
            "give_quantity": 2000,
            "get_asset": "XCP",
            "get_quantity": 2000,
            "expiration": 21,
            "fee_required": 0,
        },
        "set_variables": {
            "ORDER_4_HASH": "$TX_HASH",
            "ORDER_4_TX_INDEX": "$TX_INDEX",
            "ORDER_4_BLOCK_INDEX": "$BLOCK_INDEX",
            "ORDER_4_EXPIRATION_BLOCK_INDEX": "$BLOCK_INDEX + 21",
            "ORDER_MATCH_1_EXPIRATION_BLOCK_INDEX": "$BLOCK_INDEX + 20",
        },
        "controls": [
            {
                "url": "blocks/$BLOCK_INDEX/events?event_name=OPEN_ORDER,DEBIT,CREDIT,ORDER_MATCH,ORDER_UPDATE",
                "result": [
                    {
                        "event": "ORDER_MATCH",
                        "event_index": "$EVENT_INDEX_6",
                        "params": {
                            "backward_asset": "BTC",
                            "backward_quantity": 2000,
                            "block_index": "$BLOCK_INDEX",
                            "fee_paid": 0,
                            "forward_asset": "XCP",
                            "forward_quantity": 2000,
                            "id": "$ORDER_3_HASH_$TX_HASH",
                            "match_expire_index": "$ORDER_MATCH_1_EXPIRATION_BLOCK_INDEX",
                            "status": "pending",
                            "tx0_address": "$ADDRESS_1",
                            "tx0_block_index": "$ORDER_3_BLOCK_INDEX",
                            "tx0_expiration": 21,
                            "tx0_hash": "$ORDER_3_HASH",
                            "tx0_index": "$ORDER_3_TX_INDEX",
                            "tx1_address": "$ADDRESS_2",
                            "tx1_block_index": "$BLOCK_INDEX",
                            "tx1_expiration": 21,
                            "tx1_hash": "$TX_HASH",
                            "tx1_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "ORDER_UPDATE",
                        "event_index": "$EVENT_INDEX_5",
                        "params": {
                            "fee_provided_remaining": 10000,
                            "fee_required_remaining": 0,
                            "get_remaining": 0,
                            "give_remaining": 0,
                            "status": "open",
                            "tx_hash": "$TX_HASH",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "ORDER_UPDATE",
                        "event_index": "$EVENT_INDEX_4",
                        "params": {
                            "fee_provided_remaining": 10000,
                            "fee_required_remaining": 0,
                            "get_remaining": 8000,
                            "give_remaining": 8000,
                            "status": "open",
                            "tx_hash": "$ORDER_3_HASH",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "OPEN_ORDER",
                        "event_index": "$EVENT_INDEX_3",
                        "params": {
                            "block_index": "$BLOCK_INDEX",
                            "expiration": 21,
                            "expire_index": "$ORDER_4_EXPIRATION_BLOCK_INDEX",
                            "fee_provided": 10000,
                            "fee_provided_remaining": 10000,
                            "fee_required": 0,
                            "fee_required_remaining": 0,
                            "get_asset": "XCP",
                            "get_quantity": 2000,
                            "get_remaining": 2000,
                            "give_asset": "BTC",
                            "give_quantity": 2000,
                            "give_remaining": 2000,
                            "source": "$ADDRESS_2",
                            "status": "open",
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            },
        ],
    },
    {
        "title": "BTC pay for XCP order 2",
        "transaction": "btcpay",
        "source": "$ADDRESS_2",
        "params": {
            "order_match_id": "$ORDER_3_HASH_$ORDER_4_HASH",
        },
        "set_variables": {
            "BTCPAY_1_HASH": "$TX_HASH",
            "BTCPAY_1_TX_INDEX": "$TX_INDEX",
            "BTCPAY_1_BLOCK_INDEX": "$BLOCK_INDEX",
        },
        "controls": [
            {
                "url": "blocks/$BLOCK_INDEX/events?event_name=ORDER_MATCH_UPDATE,ORDER_FILLED,CREDIT,BTC_PAY,DEBIT",
                "result": [
                    {
                        "event": "BTC_PAY",
                        "event_index": "$EVENT_INDEX_6",
                        "params": {
                            "block_index": "$BLOCK_INDEX",
                            "btc_amount": 2000,
                            "destination": "$ADDRESS_1",
                            "order_match_id": "$ORDER_3_HASH_$ORDER_4_HASH",
                            "source": "$ADDRESS_2",
                            "status": "valid",
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "ORDER_FILLED",
                        "event_index": "$EVENT_INDEX_5",
                        "params": {"status": "filled", "tx_hash": "$ORDER_4_HASH"},
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "ORDER_MATCH_UPDATE",
                        "event_index": "$EVENT_INDEX_4",
                        "params": {
                            "id": "$ORDER_3_HASH_$ORDER_4_HASH",
                            "order_match_id": "$ORDER_3_HASH_$ORDER_4_HASH",
                            "status": "completed",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": "$EVENT_INDEX_3",
                        "params": {
                            "address": "$ADDRESS_2",
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "calling_function": "btcpay",
                            "event": "$TX_HASH",
                            "quantity": 2000,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            },
        ],
    },
    {
        "title": "Open Buy XCP for BTC order 2",
        "transaction": "order",
        "source": "$ADDRESS_3",
        "params": {
            "give_asset": "BTC",
            "give_quantity": 3000,
            "get_asset": "XCP",
            "get_quantity": 3000,
            "expiration": 21,
            "fee_required": 0,
        },
        "set_variables": {
            "ORDER_5_HASH": "$TX_HASH",
            "ORDER_5_TX_INDEX": "$TX_INDEX",
            "ORDER_5_BLOCK_INDEX": "$BLOCK_INDEX",
            "ORDER_5_EXPIRATION_BLOCK_INDEX": "$BLOCK_INDEX + 21",
            "ORDER_MATCH_2_EXPIRATION_BLOCK_INDEX": "$BLOCK_INDEX + 20",
        },
        "controls": [
            {
                "url": "blocks/$BLOCK_INDEX/events?event_name=OPEN_ORDER,ORDER_MATCH,ORDER_UPDATE",
                "result": [
                    {
                        "event": "ORDER_MATCH",
                        "event_index": "$EVENT_INDEX_6",
                        "params": {
                            "backward_asset": "BTC",
                            "backward_quantity": 3000,
                            "block_index": "$BLOCK_INDEX",
                            "fee_paid": 0,
                            "forward_asset": "XCP",
                            "forward_quantity": 3000,
                            "id": "$ORDER_3_HASH_$TX_HASH",
                            "match_expire_index": "$ORDER_MATCH_2_EXPIRATION_BLOCK_INDEX",
                            "status": "pending",
                            "tx0_address": "$ADDRESS_1",
                            "tx0_block_index": "$ORDER_4_BLOCK_INDEX",
                            "tx0_expiration": 21,
                            "tx0_hash": "$ORDER_3_HASH",
                            "tx0_index": "$ORDER_3_TX_INDEX",
                            "tx1_address": "$ADDRESS_3",
                            "tx1_block_index": "$BLOCK_INDEX",
                            "tx1_expiration": 21,
                            "tx1_hash": "$TX_HASH",
                            "tx1_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "ORDER_UPDATE",
                        "event_index": "$EVENT_INDEX_5",
                        "params": {
                            "fee_provided_remaining": 10000,
                            "fee_required_remaining": 0,
                            "get_remaining": 0,
                            "give_remaining": 0,
                            "status": "open",
                            "tx_hash": "$TX_HASH",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "ORDER_UPDATE",
                        "event_index": "$EVENT_INDEX_4",
                        "params": {
                            "fee_provided_remaining": 10000,
                            "fee_required_remaining": 0,
                            "get_remaining": 5000,
                            "give_remaining": 5000,
                            "status": "open",
                            "tx_hash": "$ORDER_3_HASH",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "OPEN_ORDER",
                        "event_index": "$EVENT_INDEX_3",
                        "params": {
                            "block_index": "$BLOCK_INDEX",
                            "expiration": 21,
                            "expire_index": "$ORDER_5_EXPIRATION_BLOCK_INDEX",
                            "fee_provided": 10000,
                            "fee_provided_remaining": 10000,
                            "fee_required": 0,
                            "fee_required_remaining": 0,
                            "get_asset": "XCP",
                            "get_quantity": 3000,
                            "get_remaining": 3000,
                            "give_asset": "BTC",
                            "give_quantity": 3000,
                            "give_remaining": 3000,
                            "source": "$ADDRESS_3",
                            "status": "open",
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            },
        ],
    },
]
