import json
import logging
import time

from counterpartycore.lib import backend, config, exceptions, ledger
from counterpartycore.lib.api.apiwatcher import EVENTS_ADDRESS_FIELDS
from counterpartycore.lib.ledger.currentstate import CurrentState
from counterpartycore.lib.parser import blocks, deserialize
from counterpartycore.lib.utils import database, hashcodec

logger = logging.getLogger(config.LOGGER_NAME)


def parse_mempool_transactions(db, raw_tx_list, timestamps=None):
    CurrentState().set_parsing_mempool(True)

    logger.trace(f"Parsing {len(raw_tx_list)} raw transaction(s) from the mempool...")
    now = time.time()
    transaction_events = []
    mempool_transactions = []
    cursor = db.cursor()
    not_supported_txs = []
    try:
        with db:
            # insert fake block (block_hash stored as BLOB after the size
            # optimization migration; convert from the hex MEMPOOL_BLOCK_HASH
            # constant inline since this path bypasses ``insert_record``).
            cursor.execute(
                """INSERT INTO blocks(
                                block_index,
                                block_hash,
                                block_time) VALUES(?,?,?)""",
                (
                    config.MEMPOOL_BLOCK_INDEX,
                    hashcodec.hash_to_db(config.MEMPOOL_BLOCK_HASH),
                    now,
                ),
            )
            # get the last tx_index
            cursor.execute(
                "SELECT tx_index FROM mempool_transactions ORDER BY tx_index DESC LIMIT 1"
            )
            last_mempool_tx = cursor.fetchone()
            if last_mempool_tx:
                last_mempool_tx_index = last_mempool_tx["tx_index"] + 1
            else:
                last_mempool_tx_index = 1

            cursor.execute("SELECT tx_index FROM transactions ORDER BY tx_index DESC LIMIT 1")
            last_tx = cursor.fetchone()
            if last_tx:
                last_tx_index = last_tx["tx_index"] + 1
            else:
                last_tx_index = 1

            mempool_tx_index = max(last_mempool_tx_index, last_tx_index)

            # get message index before parsing the block
            cursor.execute("SELECT MAX(message_index) as message_index FROM messages")
            last_message = cursor.fetchone()
            if last_message:
                message_index_before = last_message["message_index"]
            else:
                message_index_before = -1

            # list_tx
            decoded_tx_count = 0
            for raw_tx in raw_tx_list:
                decoded_tx = deserialize.deserialize_tx(raw_tx, parse_vouts=True)
                existing_tx = ledger.blocks.get_transaction(db, decoded_tx["tx_hash"])
                not_supported_txs.append(decoded_tx["tx_hash"])
                if existing_tx:
                    logger.trace(f"Transaction {decoded_tx['tx_hash']} already in the database")
                    continue
                existing_tx_in_mempool = cursor.execute(
                    "SELECT * FROM mempool WHERE tx_hash = ? LIMIT 1",
                    (hashcodec.hash_to_db(decoded_tx["tx_hash"]),),
                ).fetchone()
                if existing_tx_in_mempool:
                    logger.trace(f"Transaction {decoded_tx['tx_hash']} already in the mempool")
                    continue
                mempool_tx_index = blocks.list_tx(
                    db,
                    config.MEMPOOL_BLOCK_HASH,
                    config.MEMPOOL_BLOCK_INDEX,
                    now,
                    decoded_tx["tx_hash"],
                    tx_index=mempool_tx_index,
                    decoded_tx=decoded_tx,
                )
                decoded_tx_count += 1
            logger.trace(f"{decoded_tx_count} transactions inserted from the mempool")

            # parse fake block
            blocks.parse_block(db, config.MEMPOOL_BLOCK_INDEX, now)

            # get messages generated by the transaction. ``messages`` stores
            # ``tx_index`` rather than ``tx_hash``; expose the legacy hex
            # ``tx_hash`` for consumers via a subquery JOIN on
            # ``transactions``.
            cursor.execute(
                """SELECT m.*, t.tx_hash AS tx_hash
                   FROM messages m
                   LEFT JOIN transactions t ON t.tx_index = m.tx_index
                   WHERE m.message_index > ?""",
                (message_index_before,),
            )
            # save the events in memory
            transaction_events = cursor.fetchall()

            # get the mempool transactions. ``transactions.block_hash`` was
            # dropped in the compact-hash migration, so we synthesize it for
            # the legacy ``mempool_transactions`` schema by joining
            # ``blocks`` (always the MEMPOOL_BLOCK_HASH for mempool rows).
            cursor.execute(
                """SELECT t.*, b.block_hash AS block_hash
                   FROM transactions t
                   LEFT JOIN blocks b ON b.block_index = t.block_index
                   WHERE t.block_index = ?""",
                (config.MEMPOOL_BLOCK_INDEX,),
            )
            # save the mempool transactions in memory
            mempool_transactions = cursor.fetchall()
            # we raise an exception to rollback the transaction
            raise exceptions.MempoolError("Mempool transaction parsed successfully.")
    except exceptions.MempoolError:
        # save events in the mempool table
        for event in transaction_events:
            if event["tx_hash"] in not_supported_txs:
                not_supported_txs.remove(event["tx_hash"])

            if timestamps:
                event["timestamp"] = timestamps.get(event["tx_hash"], now)
            else:
                event["timestamp"] = now

            # collect addresses
            addresses = []
            event_bindings = json.loads(event["bindings"])
            if event["event"] in EVENTS_ADDRESS_FIELDS:
                for field in EVENTS_ADDRESS_FIELDS[event["event"]]:
                    if field in event_bindings and event_bindings[field] is not None:
                        addresses.append(event_bindings[field])
            addresses = list(set(addresses))
            event["addresses"] = " ".join(addresses)

            event_for_insert = dict(event)
            event_for_insert["tx_hash"] = hashcodec.hash_to_db(event.get("tx_hash"))
            cursor.execute(
                """INSERT INTO mempool VALUES(
                    :tx_hash, :command, :category, :bindings, :timestamp, :event, :addresses
                )""",
                event_for_insert,
            )

        for tx in mempool_transactions:
            tx_for_insert = dict(tx)
            tx_for_insert["tx_hash"] = hashcodec.hash_to_db(tx.get("tx_hash"))
            # block_hash is always the "mempool" sentinel TEXT value; do not
            # call hash_to_db which would encode it as a 7-byte BLOB and then
            # have the rowtracer decode it back as "6d656d706f6f6c".
            tx_for_insert["block_hash"] = config.MEMPOOL_BLOCK_HASH
            cursor.execute(
                """INSERT INTO mempool_transactions VALUES(
                    :tx_index, :tx_hash, :block_index, :block_hash, :block_time, :source, :destination, :btc_amount, :fee,
                    :data, :supported, :utxos_info, :transaction_type
                )""",
                tx_for_insert,
            )
    except exceptions.ParseTransactionError as e:
        # A mempool tx that would halt the chain on confirmation must NOT
        # halt the watcher pre-confirmation -- the `with db:` context already
        # rolled back the speculative inserts. Log and drop this batch; the
        # tx will halt the chain only if/when it actually confirms.
        logger.warning("mempool parse skipped on halt-class tx: %s", e)
    finally:
        # Set unconditionally so a non-MempoolError exit doesn't leave the
        # singleton stuck in mempool mode (which would silently disable UTXO
        # cache eviction in subsequent block parsing).
        CurrentState().set_parsing_mempool(False)
        # The mempool parse above always rolls back its DB mutations (the
        # `with db:` block exits via MempoolError, or a real error). That
        # rollback discards any ``assets`` rows it created, but NOT the
        # per-connection asset_index<->name caches populated while resolving
        # them. Since ``db`` is the SAME connection used for block parsing,
        # those stale mappings would otherwise make the next block's
        # ``asset_index_from_name`` resolve a freshly-issued asset to a reused
        # index -- e.g. mis-detecting a first issuance as a reissuance and
        # skipping its XCP fee. Drop them so block parsing re-resolves against
        # the committed table.
        database.reset_asset_caches(db)

    logger.trace("Mempool transaction parsed successfully.")
    return not_supported_txs


def clean_transaction_from_mempool(db, tx_hash):
    cursor = db.cursor()
    tx_hash_blob = hashcodec.hash_to_db(tx_hash)
    cursor.execute("DELETE FROM mempool WHERE tx_hash = ?", (tx_hash_blob,))
    cursor.execute("DELETE FROM mempool_transactions WHERE tx_hash = ?", (tx_hash_blob,))


def clean_mempool(db):
    logger.debug("Remove validated transactions from mempool...")
    cursor = db.cursor()
    # Iterate both mempool (events) AND mempool_transactions: an unsupported
    # tx (or one whose handler raised before emitting events) has a row in
    # mempool_transactions but none in mempool, so the events-only sweep
    # never cleaned it -- ghost rows accumulated indefinitely.
    # rowtracer converts BLOB tx_hash back to hex.
    cursor.execute(
        "SELECT DISTINCT tx_hash FROM mempool "
        "UNION SELECT DISTINCT tx_hash FROM mempool_transactions"
    )
    candidate_hashes = [row["tx_hash"] for row in cursor.fetchall()]
    raw_mempool = backend.bitcoind.getrawmempool(verbose=False)
    for tx_hash in candidate_hashes:
        tx = ledger.blocks.get_transaction(db, tx_hash)
        if tx or tx_hash not in raw_mempool:
            clean_transaction_from_mempool(db, tx_hash)
