SCENARIO = [
    {
        "title": "Issue POOLTEST asset for AMM testing",
        "transaction": "issuance",
        "source": "$ADDRESS_1",
        "params": {
            "asset": "POOLTEST",
            "quantity": 1000000000,
            "divisible": True,
            "description": "Pool test asset",
        },
        "set_variables": {
            "POOL_ASSET_HASH": "$TX_HASH",
        },
        "controls": [
            {
                "url": "blocks/$BLOCK_INDEX/events?event_name=ASSET_ISSUANCE,CREDIT,DEBIT,ASSET_CREATION",
                "result": [
                    {
                        "event": "CREDIT",
                        "event_index": "$EVENT_INDEX_6",
                        "params": {
                            "address": "$ADDRESS_1",
                            "asset": "POOLTEST",
                            "block_index": "$BLOCK_INDEX",
                            "calling_function": "issuance",
                            "event": "$TX_HASH",
                            "quantity": 1000000000,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "ASSET_ISSUANCE",
                        "event_index": "$EVENT_INDEX_5",
                        "params": {
                            "asset": "POOLTEST",
                            "asset_events": "creation",
                            "asset_longname": None,
                            "block_index": "$BLOCK_INDEX",
                            "call_date": 0,
                            "call_price": 0.0,
                            "callable": False,
                            "description": "Pool test asset",
                            "description_locked": False,
                            "divisible": True,
                            "fee_paid": 50000000,
                            "issuer": "$ADDRESS_1",
                            "locked": False,
                            "mime_type": "text/plain",
                            "msg_index": 0,
                            "quantity": 1000000000,
                            "reset": False,
                            "source": "$ADDRESS_1",
                            "status": "valid",
                            "transfer": False,
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "ASSET_CREATION",
                        "event_index": "$EVENT_INDEX_4",
                        "params": {
                            "asset_id": "124973676639",
                            "asset_longname": None,
                            "asset_name": "POOLTEST",
                            "block_index": "$BLOCK_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": "$EVENT_INDEX_3",
                        "params": {
                            "action": "issuance fee",
                            "address": "$ADDRESS_1",
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "event": "$TX_HASH",
                            "quantity": 50000000,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            },
        ],
    },
    {
        "title": "Create AMM pool with first deposit",
        "transaction": "pooldeposit",
        "source": "$ADDRESS_1",
        "params": {
            "asset_a": "XCP",
            "asset_b": "POOLTEST",
            "quantity_a": 100000000,
            "quantity_b": 100000000,
        },
        "set_variables": {
            "POOL_DEPOSIT_1_HASH": "$TX_HASH",
            "POOL_DEPOSIT_1_TX_INDEX": "$TX_INDEX",
            "POOL_DEPOSIT_1_BLOCK_INDEX": "$BLOCK_INDEX",
        },
        "controls": [
            {
                "url": "blocks/$BLOCK_INDEX/events?event_name=OPEN_POOL,NEW_POOL_DEPOSIT,ASSET_ISSUANCE,ASSET_CREATION,DEBIT,CREDIT",
                "result": [
                    {
                        "event": "NEW_POOL_DEPOSIT",
                        "event_index": "$EVENT_INDEX_10",
                        "params": {
                            "asset_a": "POOLTEST",
                            "asset_b": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "quantity_a": 100000000,
                            "quantity_b": 100000000,
                            "quantity_minted": 100000000,
                            "source": "$ADDRESS_1",
                            "status": "valid",
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "OPEN_POOL",
                        "event_index": "$EVENT_INDEX_9",
                        "params": {
                            "asset_a": "POOLTEST",
                            "asset_b": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "lp_asset": "A95428956689590706",
                            "reserve_a": 100000000,
                            "reserve_b": 100000000,
                            "source": "$ADDRESS_1",
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": "$EVENT_INDEX_8",
                        "params": {
                            "address": "$ADDRESS_1",
                            "asset": "A95428956689590706",
                            "block_index": "$BLOCK_INDEX",
                            "calling_function": "pool deposit",
                            "event": "$TX_HASH",
                            "quantity": 100000000,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "ASSET_ISSUANCE",
                        "event_index": "$EVENT_INDEX_7",
                        "params": {
                            "asset": "A95428956689590706",
                            "asset_events": "creation",
                            "asset_longname": None,
                            "block_index": "$BLOCK_INDEX",
                            "call_date": 0,
                            "call_price": 0,
                            "callable": False,
                            "description": "LP token for POOLTEST/XCP pool",
                            "description_locked": True,
                            "divisible": True,
                            "fee_paid": 0,
                            "issuer": "mvCounterpartyXXXXXXXXXXXXXXW24Hef",
                            "locked": False,
                            "mime_type": "text/plain",
                            "msg_index": 0,
                            "quantity": 100000000,
                            "reset": False,
                            "source": "mvCounterpartyXXXXXXXXXXXXXXW24Hef",
                            "status": "valid",
                            "transfer": False,
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                            "fair_minting": False,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "ASSET_CREATION",
                        "event_index": "$EVENT_INDEX_6",
                        "params": {
                            "asset_id": "95428956689590706",
                            "asset_longname": None,
                            "asset_name": "A95428956689590706",
                            "block_index": "$BLOCK_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": "$EVENT_INDEX_5",
                        "params": {
                            "action": "pool deposit",
                            "address": "$ADDRESS_1",
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "event": "$TX_HASH",
                            "quantity": 100000000,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": "$EVENT_INDEX_4",
                        "params": {
                            "action": "pool deposit",
                            "address": "$ADDRESS_1",
                            "asset": "POOLTEST",
                            "block_index": "$BLOCK_INDEX",
                            "event": "$TX_HASH",
                            "quantity": 100000000,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            },
            {
                "url": "pools/POOLTEST/XCP",
                "result": {
                    "asset_a": "POOLTEST",
                    "asset_b": "XCP",
                    "block_index": "$BLOCK_INDEX",
                    "lp_asset": "A95428956689590706",
                    "reserve_a": 100000000,
                    "reserve_b": 100000000,
                    "source": "$ADDRESS_1",
                    "tx_hash": "$TX_HASH",
                    "tx_index": "$TX_INDEX",
                },
            },
            {
                "url": "pools/XCP/POOLTEST/quote?quantity=10000000",
                "result": {
                    "pool_exists": True,
                    "estimated_output": 9049567,
                    "pool_output": 9049567,
                    "book_output": 0,
                    "book_orders_matched": 0,
                    "give_remaining": 0,
                    "fee_bps": 50,
                    "fee_amount": 50000,
                    "effective_price": 0.9049567,
                    "price_impact": 9.5043,
                },
            },
        ],
    },
    {
        "title": "Place order that fills against pool",
        "transaction": "order",
        "source": "$ADDRESS_2",
        "params": {
            "give_asset": "XCP",
            "give_quantity": 10000000,
            "get_asset": "POOLTEST",
            "get_quantity": 1,
            "expiration": 21,
            "fee_required": 0,
        },
        "set_variables": {
            "POOL_ORDER_HASH": "$TX_HASH",
            "POOL_ORDER_TX_INDEX": "$TX_INDEX",
            "POOL_ORDER_BLOCK_INDEX": "$BLOCK_INDEX",
            "POOL_ORDER_EXPIRATION_BLOCK_INDEX": "$BLOCK_INDEX + 21",
        },
        "controls": [
            {
                "url": "blocks/$BLOCK_INDEX/events?event_name=OPEN_ORDER,DEBIT,CREDIT,POOL_MATCH,ORDER_UPDATE",
                "result": [
                    {
                        "event": "ORDER_UPDATE",
                        "event_index": "$EVENT_INDEX_8",
                        "params": {
                            "fee_provided_remaining": 10000,
                            "fee_required_remaining": 0,
                            "get_remaining": -9049566,
                            "give_remaining": 0,
                            "status": "filled",
                            "tx_hash": "$TX_HASH",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "POOL_MATCH",
                        "event_index": "$EVENT_INDEX_7",
                        "params": {
                            "asset_a": "POOLTEST",
                            "asset_b": "XCP",
                            "backward_asset": "XCP",
                            "backward_quantity": 10000000,
                            "block_index": "$BLOCK_INDEX",
                            "fee_bps": 50,
                            "fee_quantity": 50000,
                            "forward_asset": "POOLTEST",
                            "forward_quantity": 9049567,
                            "order_tx_hash": "$TX_HASH",
                            "source": "$ADDRESS_2",
                            "status": "valid",
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": "$EVENT_INDEX_5",
                        "params": {
                            "address": "$ADDRESS_2",
                            "asset": "POOLTEST",
                            "block_index": "$BLOCK_INDEX",
                            "calling_function": "pool match",
                            "event": "$TX_HASH",
                            "quantity": 9049567,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "OPEN_ORDER",
                        "event_index": "$EVENT_INDEX_4",
                        "params": {
                            "block_index": "$BLOCK_INDEX",
                            "expiration": 21,
                            "expire_index": "$POOL_ORDER_EXPIRATION_BLOCK_INDEX",
                            "fee_provided": 10000,
                            "fee_provided_remaining": 10000,
                            "fee_required": 0,
                            "fee_required_remaining": 0,
                            "get_asset": "POOLTEST",
                            "get_quantity": 1,
                            "get_remaining": 1,
                            "give_asset": "XCP",
                            "give_quantity": 10000000,
                            "give_remaining": 10000000,
                            "source": "$ADDRESS_2",
                            "status": "open",
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": "$EVENT_INDEX_3",
                        "params": {
                            "action": "open order",
                            "address": "$ADDRESS_2",
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "event": "$TX_HASH",
                            "quantity": 10000000,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            },
            {
                "url": "orders/$TX_HASH/pool_matches",
                "result": [
                    {
                        "asset_a": "POOLTEST",
                        "asset_b": "XCP",
                        "backward_asset": "XCP",
                        "backward_quantity": 10000000,
                        "block_index": "$BLOCK_INDEX",
                        "fee_bps": 50,
                        "fee_quantity": 50000,
                        "forward_asset": "POOLTEST",
                        "forward_quantity": 9049567,
                        "order_tx_hash": "$TX_HASH",
                        "source": "$ADDRESS_2",
                        "status": "valid",
                        "tx_hash": "$TX_HASH",
                        "tx_index": "$TX_INDEX",
                    },
                ],
            },
            {
                "url": "pools/POOLTEST/XCP/deposits",
                "result": [
                    {
                        "asset_a": "POOLTEST",
                        "asset_b": "XCP",
                        "block_index": "$POOL_DEPOSIT_1_BLOCK_INDEX",
                        "quantity_a": 100000000,
                        "quantity_b": 100000000,
                        "quantity_minted": 100000000,
                        "source": "$ADDRESS_1",
                        "status": "valid",
                        "tx_hash": "$POOL_DEPOSIT_1_HASH",
                        "tx_index": "$POOL_DEPOSIT_1_TX_INDEX",
                    },
                ],
            },
            {
                "url": "pools/POOLTEST/XCP/matches",
                "result": [
                    {
                        "asset_a": "POOLTEST",
                        "asset_b": "XCP",
                        "backward_asset": "XCP",
                        "backward_quantity": 10000000,
                        "block_index": "$BLOCK_INDEX",
                        "fee_bps": 50,
                        "fee_quantity": 50000,
                        "forward_asset": "POOLTEST",
                        "forward_quantity": 9049567,
                        "order_tx_hash": "$TX_HASH",
                        "source": "$ADDRESS_2",
                        "status": "valid",
                        "tx_hash": "$TX_HASH",
                        "tx_index": "$TX_INDEX",
                    },
                ],
            },
        ],
    },
    {
        "title": "Second deposit to existing pool",
        "transaction": "pooldeposit",
        "source": "$ADDRESS_1",
        "params": {
            "asset_a": "XCP",
            "asset_b": "POOLTEST",
            "quantity_a": 50000000,
            "quantity_b": 50000000,
        },
        "set_variables": {
            "POOL_DEPOSIT_2_HASH": "$TX_HASH",
            "POOL_DEPOSIT_2_TX_INDEX": "$TX_INDEX",
            "POOL_DEPOSIT_2_BLOCK_INDEX": "$BLOCK_INDEX",
        },
        "controls": [
            {
                "url": "blocks/$BLOCK_INDEX/events?event_name=NEW_POOL_DEPOSIT,ASSET_ISSUANCE,DEBIT,CREDIT",
                "result": [
                    {
                        "event": "NEW_POOL_DEPOSIT",
                        "event_index": "$EVENT_INDEX_9",
                        "params": {
                            "asset_a": "POOLTEST",
                            "asset_b": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "quantity_a": 41341105,
                            "quantity_b": 50000000,
                            "quantity_minted": 45454544,
                            "source": "$ADDRESS_1",
                            "status": "valid",
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": "$EVENT_INDEX_7",
                        "params": {
                            "address": "$ADDRESS_1",
                            "asset": "A95428956689590706",
                            "block_index": "$BLOCK_INDEX",
                            "calling_function": "pool deposit",
                            "event": "$TX_HASH",
                            "quantity": 45454544,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "ASSET_ISSUANCE",
                        "event_index": "$EVENT_INDEX_6",
                        "params": {
                            "asset": "A95428956689590706",
                            "asset_events": "pool_deposit_mint",
                            "asset_longname": None,
                            "block_index": "$BLOCK_INDEX",
                            "call_date": 0,
                            "call_price": 0,
                            "callable": False,
                            "description": "LP token for POOLTEST/XCP pool",
                            "description_locked": True,
                            "divisible": True,
                            "fee_paid": 0,
                            "issuer": "mvCounterpartyXXXXXXXXXXXXXXW24Hef",
                            "locked": False,
                            "mime_type": "text/plain",
                            "msg_index": 0,
                            "quantity": 45454544,
                            "reset": False,
                            "source": "mvCounterpartyXXXXXXXXXXXXXXW24Hef",
                            "status": "valid",
                            "transfer": False,
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                            "fair_minting": False,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": "$EVENT_INDEX_5",
                        "params": {
                            "action": "pool deposit",
                            "address": "$ADDRESS_1",
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "event": "$TX_HASH",
                            "quantity": 50000000,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": "$EVENT_INDEX_4",
                        "params": {
                            "action": "pool deposit",
                            "address": "$ADDRESS_1",
                            "asset": "POOLTEST",
                            "block_index": "$BLOCK_INDEX",
                            "event": "$TX_HASH",
                            "quantity": 41341105,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            },
        ],
    },
    {
        "title": "Withdraw half of LP position",
        "transaction": "poolwithdraw",
        "source": "$ADDRESS_1",
        "params": {
            "asset_a": "XCP",
            "asset_b": "POOLTEST",
            "quantity": 25000000,
        },
        "set_variables": {
            "POOL_WITHDRAW_HASH": "$TX_HASH",
        },
        "controls": [
            {
                "url": "blocks/$BLOCK_INDEX/events?event_name=NEW_POOL_WITHDRAWAL,ASSET_DESTRUCTION,DEBIT,CREDIT",
                "result": [
                    {
                        "event": "NEW_POOL_WITHDRAWAL",
                        "event_index": "$EVENT_INDEX_9",
                        "params": {
                            "asset_a": "POOLTEST",
                            "asset_b": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "quantity_a": 22737608,
                            "quantity_b": 27500000,
                            "quantity_destroyed": 25000000,
                            "source": "$ADDRESS_1",
                            "status": "valid",
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": "$EVENT_INDEX_7",
                        "params": {
                            "address": "$ADDRESS_1",
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "calling_function": "pool withdraw",
                            "event": "$TX_HASH",
                            "quantity": 27500000,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": "$EVENT_INDEX_6",
                        "params": {
                            "address": "$ADDRESS_1",
                            "asset": "POOLTEST",
                            "block_index": "$BLOCK_INDEX",
                            "calling_function": "pool withdraw",
                            "event": "$TX_HASH",
                            "quantity": 22737608,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "ASSET_DESTRUCTION",
                        "event_index": "$EVENT_INDEX_5",
                        "params": {
                            "asset": "A95428956689590706",
                            "block_index": "$BLOCK_INDEX",
                            "quantity": 25000000,
                            "source": "$ADDRESS_1",
                            "status": "valid",
                            "tag": "pool_withdraw",
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": "$EVENT_INDEX_4",
                        "params": {
                            "action": "pool withdraw",
                            "address": "$ADDRESS_1",
                            "asset": "A95428956689590706",
                            "block_index": "$BLOCK_INDEX",
                            "event": "$TX_HASH",
                            "quantity": 25000000,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            },
            {
                "url": "pools/POOLTEST/XCP/withdrawals",
                "result": [
                    {
                        "asset_a": "POOLTEST",
                        "asset_b": "XCP",
                        "block_index": "$BLOCK_INDEX",
                        "quantity_a": 22737608,
                        "quantity_b": 27500000,
                        "quantity_destroyed": 25000000,
                        "source": "$ADDRESS_1",
                        "status": "valid",
                        "tx_hash": "$TX_HASH",
                        "tx_index": "$TX_INDEX",
                    },
                ],
            },
            {
                "url": "pools/POOLTEST/XCP",
                "result": {
                    "asset_a": "POOLTEST",
                    "asset_b": "XCP",
                    "block_index": "$BLOCK_INDEX",
                    "lp_asset": "A95428956689590706",
                    "reserve_a": 109553930,
                    "reserve_b": 132500000,
                    "source": "$ADDRESS_1",
                    "tx_hash": "$POOL_DEPOSIT_1_HASH",
                    "tx_index": "$POOL_DEPOSIT_1_TX_INDEX",
                },
            },
            {
                "url": "pools",
                "result": [
                    {
                        "asset_a": "POOLTEST",
                        "asset_b": "XCP",
                        "block_index": "$BLOCK_INDEX",
                        "lp_asset": "A95428956689590706",
                        "reserve_a": 109553930,
                        "reserve_b": 132500000,
                        "source": "$ADDRESS_1",
                        "tx_hash": "$POOL_DEPOSIT_1_HASH",
                        "tx_index": "$POOL_DEPOSIT_1_TX_INDEX",
                    },
                ],
            },
            {
                "url": "pools/POOLTEST/XCP/quote/deposit?quantity=10000000",
                "result": {
                    "first_deposit": False,
                    "asset_a": "POOLTEST",
                    "asset_b": "XCP",
                    "quantity_a_required": 10000000,
                    "quantity_b_required": 12094500,
                    "quantity_minted_estimate": 10994999,
                },
            },
            {
                "url": "pools/POOLTEST/XCP/quote/withdraw?quantity=10000000",
                "result": {
                    "pool_exists": True,
                    "asset_a": "POOLTEST",
                    "asset_b": "XCP",
                    "quantity": 10000000,
                    "supply": 120454544,
                    "quantity_a_estimate": 9095043,
                    "quantity_b_estimate": 11000000,
                    "reserve_a": 109553930,
                    "reserve_b": 132500000,
                },
            },
            {
                "url": "addresses/$ADDRESS_1/pool_deposits",
                "result": [
                    {
                        "asset_a": "POOLTEST",
                        "asset_b": "XCP",
                        "block_index": "$POOL_DEPOSIT_2_BLOCK_INDEX",
                        "quantity_a": 41341105,
                        "quantity_b": 50000000,
                        "quantity_minted": 45454544,
                        "source": "$ADDRESS_1",
                        "status": "valid",
                        "tx_hash": "$POOL_DEPOSIT_2_HASH",
                        "tx_index": "$POOL_DEPOSIT_2_TX_INDEX",
                    },
                    {
                        "asset_a": "POOLTEST",
                        "asset_b": "XCP",
                        "block_index": "$POOL_DEPOSIT_1_BLOCK_INDEX",
                        "quantity_a": 100000000,
                        "quantity_b": 100000000,
                        "quantity_minted": 100000000,
                        "source": "$ADDRESS_1",
                        "status": "valid",
                        "tx_hash": "$POOL_DEPOSIT_1_HASH",
                        "tx_index": "$POOL_DEPOSIT_1_TX_INDEX",
                    },
                ],
            },
            {
                "url": "addresses/$ADDRESS_1/pool_withdrawals",
                "result": [
                    {
                        "asset_a": "POOLTEST",
                        "asset_b": "XCP",
                        "block_index": "$BLOCK_INDEX",
                        "quantity_a": 22737608,
                        "quantity_b": 27500000,
                        "quantity_destroyed": 25000000,
                        "source": "$ADDRESS_1",
                        "status": "valid",
                        "tx_hash": "$TX_HASH",
                        "tx_index": "$TX_INDEX",
                    },
                ],
            },
            {
                "url": "pool_matches",
                "result": [
                    {
                        "asset_a": "POOLTEST",
                        "asset_b": "XCP",
                        "backward_asset": "XCP",
                        "backward_quantity": 10000000,
                        "block_index": "$POOL_ORDER_BLOCK_INDEX",
                        "fee_bps": 50,
                        "fee_quantity": 50000,
                        "forward_asset": "POOLTEST",
                        "forward_quantity": 9049567,
                        "order_tx_hash": "$POOL_ORDER_HASH",
                        "source": "$ADDRESS_2",
                        "status": "valid",
                        "tx_hash": "$POOL_ORDER_HASH",
                        "tx_index": "$POOL_ORDER_TX_INDEX",
                    },
                ],
            },
        ],
    },
    {
        "title": "Order with tight price stays open (no pool fill)",
        "transaction": "order",
        "source": "$ADDRESS_2",
        "params": {
            "give_asset": "XCP",
            "give_quantity": 1000000,
            "get_asset": "POOLTEST",
            "get_quantity": 2000000,
            "expiration": 21,
            "fee_required": 0,
        },
        "set_variables": {
            "POOL_NOFILL_ORDER_HASH": "$TX_HASH",
            "POOL_NOFILL_EXPIRATION_BLOCK_INDEX": "$BLOCK_INDEX + 21",
        },
        "controls": [
            {
                "url": "blocks/$BLOCK_INDEX/events?event_name=OPEN_ORDER,DEBIT,POOL_MATCH",
                "result": [
                    {
                        "event": "OPEN_ORDER",
                        "event_index": "$EVENT_INDEX_4",
                        "params": {
                            "block_index": "$BLOCK_INDEX",
                            "expiration": 21,
                            "expire_index": "$POOL_NOFILL_EXPIRATION_BLOCK_INDEX",
                            "fee_provided": 10000,
                            "fee_provided_remaining": 10000,
                            "fee_required": 0,
                            "fee_required_remaining": 0,
                            "get_asset": "POOLTEST",
                            "get_quantity": 2000000,
                            "get_remaining": 2000000,
                            "give_asset": "XCP",
                            "give_quantity": 1000000,
                            "give_remaining": 1000000,
                            "source": "$ADDRESS_2",
                            "status": "open",
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": "$EVENT_INDEX_3",
                        "params": {
                            "action": "open order",
                            "address": "$ADDRESS_2",
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "event": "$TX_HASH",
                            "quantity": 1000000,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            },
            {
                "url": "orders/$TX_HASH/pool_matches",
                "result": [],
            },
        ],
    },
    {
        "title": "Reject deposit with BTC pair",
        "transaction": "pooldeposit",
        "source": "$ADDRESS_1",
        "params": {
            "asset_a": "BTC",
            "asset_b": "XCP",
            "quantity_a": 100000000,
            "quantity_b": 100000000,
        },
        "expected_error": ["BTC pairs are not supported for AMM pools"],
    },
    {
        "title": "Reject deposit with same asset",
        "transaction": "pooldeposit",
        "source": "$ADDRESS_1",
        "params": {
            "asset_a": "XCP",
            "asset_b": "XCP",
            "quantity_a": 100000000,
            "quantity_b": 100000000,
        },
        "expected_error": ["assets must be different"],
    },
    {
        "title": "Reject deposit with LP token",
        "transaction": "pooldeposit",
        "source": "$ADDRESS_1",
        "params": {
            "asset_a": "XCP",
            "asset_b": "A95428956689590706",
            "quantity_a": 100000000,
            "quantity_b": 100000000,
        },
        "expected_error": ["A95428956689590706 is an LP token; LP tokens cannot be pooled"],
    },
    {
        "title": "Reject withdrawal from non-existent pool",
        "transaction": "poolwithdraw",
        "source": "$ADDRESS_1",
        "params": {
            "asset_a": "XCP",
            "asset_b": "NONEXISTENT",
            "quantity": 1000,
        },
        "expected_error": ["asset NONEXISTENT does not exist"],
    },
    {
        "title": "Reject withdrawal with insufficient LP balance",
        "transaction": "poolwithdraw",
        "source": "$ADDRESS_2",
        "params": {
            "asset_a": "XCP",
            "asset_b": "POOLTEST",
            "quantity": 1,
        },
        "expected_error": ["insufficient LP token balance (0 < 1)"],
    },
]
