SCENARIO = [
    {
        "title": "Create FAIRMINTC fairminter",
        "transaction": "fairminter",
        "source": "$ADDRESS_1",
        "params": {
            "asset": "FAIRMINTC",
            "price": 1,
            "quantity_by_price": 5,
        },
        "set_variables": {
            "FAIRMINTC_TX_HASH": "$TX_HASH",
        },
        "controls": [
            {
                "url": "blocks/$BLOCK_INDEX/events?event_name=DEBIT,ASSET_ISSUANCE,ASSET_CREATION,NEW_FAIRMINTER,CREDIT",
                "result": [
                    {
                        "event": "DEBIT",
                        "event_index": "$EVENT_INDEX_6",
                        "params": {
                            "action": "fairminter fee",
                            "address": "$ADDRESS_1",
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "event": "$TX_HASH",
                            "quantity": 50000000,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "ASSET_ISSUANCE",
                        "event_index": "$EVENT_INDEX_5",
                        "params": {
                            "asset": "FAIRMINTC",
                            "asset_longname": None,
                            "asset_events": "open_fairminter",
                            "block_index": "$BLOCK_INDEX",
                            "call_date": 0,
                            "call_price": 0,
                            "callable": False,
                            "description": "",
                            "divisible": True,
                            "fair_minting": True,
                            "fee_paid": 50000000.0,
                            "issuer": "$ADDRESS_1",
                            "locked": False,
                            "quantity": 0,
                            "reset": False,
                            "source": "$ADDRESS_1",
                            "status": "valid",
                            "transfer": False,
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "ASSET_CREATION",
                        "event_index": "$EVENT_INDEX_4",
                        "params": {
                            "asset_id": "1046814266084",
                            "asset_longname": None,
                            "asset_name": "FAIRMINTC",
                            "block_index": "$BLOCK_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "NEW_FAIRMINTER",
                        "event_index": "$EVENT_INDEX_3",
                        "params": {
                            "asset": "FAIRMINTC",
                            "asset_longname": None,
                            "asset_parent": None,
                            "block_index": "$BLOCK_INDEX",
                            "burn_payment": False,
                            "description": "",
                            "divisible": True,
                            "end_block": 0,
                            "hard_cap": 0,
                            "lock_description": False,
                            "lock_quantity": False,
                            "max_mint_per_tx": 0,
                            "max_mint_per_address": 0,
                            "minted_asset_commission_int": 0,
                            "pre_minted": False,
                            "premint_quantity": 0,
                            "price": 1,
                            "quantity_by_price": 5,
                            "soft_cap": 0,
                            "soft_cap_deadline_block": 0,
                            "source": "$ADDRESS_1",
                            "start_block": 0,
                            "status": "open",
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            }
        ],
    },
    {
        "title": "Mint FAIRMINTC",
        "transaction": "fairmint",
        "source": "$ADDRESS_2",
        "params": {
            "asset": "FAIRMINTC",
            "quantity": 5,
        },
        "controls": [
            {
                "url": "blocks/$BLOCK_INDEX/events?event_name=DEBIT,CREDIT,NEW_FAIRMINT,ASSET_ISSUANCE",
                "result": [
                    {
                        "event": "ASSET_ISSUANCE",
                        "event_index": "$EVENT_INDEX_7",
                        "params": {
                            "asset": "FAIRMINTC",
                            "asset_longname": None,
                            "asset_events": "fairmint",
                            "block_index": "$BLOCK_INDEX",
                            "call_date": 0,
                            "call_price": 0.0,
                            "callable": False,
                            "description": "",
                            "description_locked": False,
                            "divisible": True,
                            "fair_minting": True,
                            "fee_paid": 0,
                            "issuer": "$ADDRESS_1",
                            "locked": False,
                            "msg_index": 0,
                            "quantity": 5,
                            "reset": False,
                            "source": "$ADDRESS_2",
                            "status": "valid",
                            "transfer": False,
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "NEW_FAIRMINT",
                        "event_index": "$EVENT_INDEX_6",
                        "params": {
                            "asset": "FAIRMINTC",
                            "block_index": "$BLOCK_INDEX",
                            "commission": 0,
                            "earn_quantity": 5,
                            "fairminter_tx_hash": "$FAIRMINTC_TX_HASH",
                            "paid_quantity": 1,
                            "source": "$ADDRESS_2",
                            "status": "valid",
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": "$EVENT_INDEX_5",
                        "params": {
                            "address": "$ADDRESS_2",
                            "asset": "FAIRMINTC",
                            "block_index": "$BLOCK_INDEX",
                            "calling_function": "fairmint",
                            "event": "$TX_HASH",
                            "quantity": 5,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": "$EVENT_INDEX_4",
                        "params": {
                            "address": "$ADDRESS_1",
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "calling_function": "fairmint payment",
                            "event": "$TX_HASH",
                            "quantity": 1,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": "$EVENT_INDEX_3",
                        "params": {
                            "action": "fairmint payment",
                            "address": "$ADDRESS_2",
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "event": "$TX_HASH",
                            "quantity": 1,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            }
        ],
    },
    {
        "title": "Mint FAIRMINTC",
        "transaction": "fairmint",
        "source": "$ADDRESS_2",
        "params": {
            "asset": "FAIRMINTC",
            "quantity": 3,
        },
        "controls": [
            {
                "url": "blocks/$BLOCK_INDEX/events?event_name=DEBIT,CREDIT,NEW_FAIRMINT,ASSET_ISSUANCE",
                "result": [
                    {
                        "event": "ASSET_ISSUANCE",
                        "event_index": "$EVENT_INDEX_7",
                        "params": {
                            "asset": "FAIRMINTC",
                            "asset_longname": None,
                            "asset_events": "fairmint",
                            "block_index": "$BLOCK_INDEX",
                            "call_date": 0,
                            "call_price": 0.0,
                            "callable": False,
                            "description": "",
                            "description_locked": False,
                            "divisible": True,
                            "fair_minting": True,
                            "fee_paid": 0,
                            "issuer": "$ADDRESS_1",
                            "locked": False,
                            "msg_index": 0,
                            "quantity": 3,
                            "reset": False,
                            "source": "$ADDRESS_2",
                            "status": "valid",
                            "transfer": False,
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "NEW_FAIRMINT",
                        "event_index": "$EVENT_INDEX_6",
                        "params": {
                            "asset": "FAIRMINTC",
                            "block_index": "$BLOCK_INDEX",
                            "commission": 0,
                            "earn_quantity": 3,
                            "fairminter_tx_hash": "$FAIRMINTC_TX_HASH",
                            "paid_quantity": 1,
                            "source": "$ADDRESS_2",
                            "status": "valid",
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": "$EVENT_INDEX_5",
                        "params": {
                            "address": "$ADDRESS_2",
                            "asset": "FAIRMINTC",
                            "block_index": "$BLOCK_INDEX",
                            "calling_function": "fairmint",
                            "event": "$TX_HASH",
                            "quantity": 3,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": "$EVENT_INDEX_4",
                        "params": {
                            "address": "$ADDRESS_1",
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "calling_function": "fairmint payment",
                            "event": "$TX_HASH",
                            "quantity": 1,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": "$EVENT_INDEX_3",
                        "params": {
                            "action": "fairmint payment",
                            "address": "$ADDRESS_2",
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "event": "$TX_HASH",
                            "quantity": 1,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            }
        ],
    },
    {
        "title": "Mint FAIRMINTC",
        "transaction": "fairmint",
        "source": "$ADDRESS_2",
        "params": {
            "asset": "FAIRMINTC",
            "quantity": 11,
        },
        "controls": [
            {
                "url": "blocks/$BLOCK_INDEX/events?event_name=DEBIT,CREDIT,NEW_FAIRMINT,ASSET_ISSUANCE",
                "result": [
                    {
                        "event": "ASSET_ISSUANCE",
                        "event_index": "$EVENT_INDEX_7",
                        "params": {
                            "asset": "FAIRMINTC",
                            "asset_longname": None,
                            "asset_events": "fairmint",
                            "block_index": "$BLOCK_INDEX",
                            "call_date": 0,
                            "call_price": 0.0,
                            "callable": False,
                            "description": "",
                            "description_locked": False,
                            "divisible": True,
                            "fair_minting": True,
                            "fee_paid": 0,
                            "issuer": "$ADDRESS_1",
                            "locked": False,
                            "msg_index": 0,
                            "quantity": 11,
                            "reset": False,
                            "source": "$ADDRESS_2",
                            "status": "valid",
                            "transfer": False,
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "NEW_FAIRMINT",
                        "event_index": "$EVENT_INDEX_6",
                        "params": {
                            "asset": "FAIRMINTC",
                            "block_index": "$BLOCK_INDEX",
                            "commission": 0,
                            "earn_quantity": 11,
                            "fairminter_tx_hash": "$FAIRMINTC_TX_HASH",
                            "paid_quantity": 3,
                            "source": "$ADDRESS_2",
                            "status": "valid",
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": "$EVENT_INDEX_5",
                        "params": {
                            "address": "$ADDRESS_2",
                            "asset": "FAIRMINTC",
                            "block_index": "$BLOCK_INDEX",
                            "calling_function": "fairmint",
                            "event": "$TX_HASH",
                            "quantity": 11,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": "$EVENT_INDEX_4",
                        "params": {
                            "address": "$ADDRESS_1",
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "calling_function": "fairmint payment",
                            "event": "$TX_HASH",
                            "quantity": 3,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": "$EVENT_INDEX_3",
                        "params": {
                            "action": "fairmint payment",
                            "address": "$ADDRESS_2",
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "event": "$TX_HASH",
                            "quantity": 3,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            }
        ],
    },
    {
        "title": "Create FAIRMINTD fairminter",
        "transaction": "fairminter",
        "source": "$ADDRESS_1",
        "params": {
            "asset": "FAIRMINTD",
            "price": 50,
            "quantity_by_price": 60,
        },
        "set_variables": {
            "FAIRMINTD_TX_HASH": "$TX_HASH",
        },
        "controls": [
            {
                "url": "blocks/$BLOCK_INDEX/events?event_name=DEBIT,ASSET_ISSUANCE,ASSET_CREATION,NEW_FAIRMINTER",
                "result": [
                    {
                        "event": "DEBIT",
                        "event_index": "$EVENT_INDEX_6",
                        "params": {
                            "action": "fairminter fee",
                            "address": "$ADDRESS_1",
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "event": "$TX_HASH",
                            "quantity": 50000000,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "ASSET_ISSUANCE",
                        "event_index": "$EVENT_INDEX_5",
                        "params": {
                            "asset": "FAIRMINTD",
                            "asset_longname": None,
                            "asset_events": "open_fairminter",
                            "block_index": "$BLOCK_INDEX",
                            "call_date": 0,
                            "call_price": 0,
                            "callable": False,
                            "description": "",
                            "divisible": True,
                            "fair_minting": True,
                            "fee_paid": 50000000.0,
                            "issuer": "$ADDRESS_1",
                            "locked": False,
                            "quantity": 0,
                            "reset": False,
                            "source": "$ADDRESS_1",
                            "status": "valid",
                            "transfer": False,
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "ASSET_CREATION",
                        "event_index": "$EVENT_INDEX_4",
                        "params": {
                            "asset_id": "1046814266085",
                            "asset_longname": None,
                            "asset_name": "FAIRMINTD",
                            "block_index": "$BLOCK_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "NEW_FAIRMINTER",
                        "event_index": "$EVENT_INDEX_3",
                        "params": {
                            "asset": "FAIRMINTD",
                            "asset_longname": None,
                            "asset_parent": None,
                            "block_index": "$BLOCK_INDEX",
                            "burn_payment": False,
                            "description": "",
                            "divisible": True,
                            "end_block": 0,
                            "hard_cap": 0,
                            "lock_description": False,
                            "lock_quantity": False,
                            "max_mint_per_tx": 0,
                            "max_mint_per_address": 0,
                            "minted_asset_commission_int": 0,
                            "pre_minted": False,
                            "premint_quantity": 0,
                            "price": 50,
                            "quantity_by_price": 60,
                            "soft_cap": 0,
                            "soft_cap_deadline_block": 0,
                            "source": "$ADDRESS_1",
                            "start_block": 0,
                            "status": "open",
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            }
        ],
    },
    {
        "title": "Mint FAIRMINTD",
        "transaction": "fairmint",
        "source": "$ADDRESS_2",
        "params": {
            "asset": "FAIRMINTD",
            "quantity": 40,
        },
        "controls": [
            {
                "url": "blocks/$BLOCK_INDEX/events?event_name=DEBIT,CREDIT,NEW_FAIRMINT,ASSET_ISSUANCE",
                "result": [
                    {
                        "event": "ASSET_ISSUANCE",
                        "event_index": "$EVENT_INDEX_7",
                        "params": {
                            "asset": "FAIRMINTD",
                            "asset_longname": None,
                            "asset_events": "fairmint",
                            "block_index": "$BLOCK_INDEX",
                            "call_date": 0,
                            "call_price": 0.0,
                            "callable": False,
                            "description": "",
                            "description_locked": False,
                            "divisible": True,
                            "fair_minting": True,
                            "fee_paid": 0,
                            "issuer": "$ADDRESS_1",
                            "locked": False,
                            "msg_index": 0,
                            "quantity": 40,
                            "reset": False,
                            "source": "$ADDRESS_2",
                            "status": "valid",
                            "transfer": False,
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "NEW_FAIRMINT",
                        "event_index": "$EVENT_INDEX_6",
                        "params": {
                            "asset": "FAIRMINTD",
                            "block_index": "$BLOCK_INDEX",
                            "commission": 0,
                            "earn_quantity": 40,
                            "fairminter_tx_hash": "$FAIRMINTD_TX_HASH",
                            "paid_quantity": 34,
                            "source": "$ADDRESS_2",
                            "status": "valid",
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": "$EVENT_INDEX_5",
                        "params": {
                            "address": "$ADDRESS_2",
                            "asset": "FAIRMINTD",
                            "block_index": "$BLOCK_INDEX",
                            "calling_function": "fairmint",
                            "event": "$TX_HASH",
                            "quantity": 40,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": "$EVENT_INDEX_4",
                        "params": {
                            "address": "$ADDRESS_1",
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "calling_function": "fairmint payment",
                            "event": "$TX_HASH",
                            "quantity": 34,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": "$EVENT_INDEX_3",
                        "params": {
                            "action": "fairmint payment",
                            "address": "$ADDRESS_2",
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "event": "$TX_HASH",
                            "quantity": 34,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            }
        ],
    },
]
