SCENARIO = [
    {
        "title": "Open order A for cancel-all test",
        "transaction": "order",
        "source": "$ADDRESS_2",
        "params": {
            "give_asset": "XCP",
            "give_quantity": 2000,
            "get_asset": "BTC",
            "get_quantity": 2000,
            "expiration": 21,
            "fee_required": 0,
        },
        "set_variables": {
            "CANCEL_ALL_ORDER_A_HASH": "$TX_HASH",
            "CANCEL_ALL_ORDER_A_EXPIRATION": "$BLOCK_INDEX + 21",
        },
        "controls": [
            {
                "url": "blocks/$BLOCK_INDEX/events?event_name=OPEN_ORDER,DEBIT",
                "result": [
                    {
                        "event": "OPEN_ORDER",
                        "event_index": "$EVENT_INDEX_4",
                        "params": {
                            "block_index": "$BLOCK_INDEX",
                            "expiration": 21,
                            "expire_index": "$CANCEL_ALL_ORDER_A_EXPIRATION",
                            "fee_provided": 10000,
                            "fee_provided_remaining": 10000,
                            "fee_required": 0,
                            "fee_required_remaining": 0,
                            "get_asset": "BTC",
                            "get_quantity": 2000,
                            "get_remaining": 2000,
                            "give_asset": "XCP",
                            "give_quantity": 2000,
                            "give_remaining": 2000,
                            "source": "$ADDRESS_2",
                            "status": "open",
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": "$EVENT_INDEX_3",
                        "params": {
                            "action": "open order",
                            "address": "$ADDRESS_2",
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "event": "$TX_HASH",
                            "quantity": 2000,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            },
        ],
    },
    {
        "title": "Open order B for cancel-all test",
        "transaction": "order",
        "source": "$ADDRESS_2",
        "params": {
            "give_asset": "XCP",
            "give_quantity": 3000,
            "get_asset": "BTC",
            "get_quantity": 3000,
            "expiration": 21,
            "fee_required": 0,
        },
        "set_variables": {
            "CANCEL_ALL_ORDER_B_HASH": "$TX_HASH",
            "CANCEL_ALL_ORDER_B_EXPIRATION": "$BLOCK_INDEX + 21",
        },
        "controls": [
            {
                "url": "blocks/$BLOCK_INDEX/events?event_name=OPEN_ORDER,DEBIT",
                "result": [
                    {
                        "event": "OPEN_ORDER",
                        "event_index": "$EVENT_INDEX_4",
                        "params": {
                            "block_index": "$BLOCK_INDEX",
                            "expiration": 21,
                            "expire_index": "$CANCEL_ALL_ORDER_B_EXPIRATION",
                            "fee_provided": 10000,
                            "fee_provided_remaining": 10000,
                            "fee_required": 0,
                            "fee_required_remaining": 0,
                            "get_asset": "BTC",
                            "get_quantity": 3000,
                            "get_remaining": 3000,
                            "give_asset": "XCP",
                            "give_quantity": 3000,
                            "give_remaining": 3000,
                            "source": "$ADDRESS_2",
                            "status": "open",
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "DEBIT",
                        "event_index": "$EVENT_INDEX_3",
                        "params": {
                            "action": "open order",
                            "address": "$ADDRESS_2",
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "event": "$TX_HASH",
                            "quantity": 3000,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            },
        ],
    },
    {
        "title": "Cancel all open offers for ADDRESS_2",
        "transaction": "cancel",
        "source": "$ADDRESS_2",
        "params": {},
        "controls": [
            {
                "url": "blocks/$BLOCK_INDEX/events?event_name=CANCEL_ALL,ORDER_UPDATE,CREDIT,INCREMENT_TRANSACTION_COUNT",
                "result": [
                    {
                        "event": "CANCEL_ALL",
                        "event_index": "$EVENT_INDEX_8",
                        "params": {
                            "block_index": "$BLOCK_INDEX",
                            "offer_hash": "cancel_all",
                            "source": "$ADDRESS_2",
                            "status": "valid",
                            "tx_hash": "$TX_HASH",
                            "tx_index": "$TX_INDEX",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": "$EVENT_INDEX_7",
                        "params": {
                            "address": "$ADDRESS_2",
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "calling_function": "cancel order",
                            "event": "$CANCEL_ALL_ORDER_B_HASH",
                            "quantity": 3000,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "ORDER_UPDATE",
                        "event_index": "$EVENT_INDEX_6",
                        "params": {
                            "status": "cancelled",
                            "tx_hash": "$CANCEL_ALL_ORDER_B_HASH",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "CREDIT",
                        "event_index": "$EVENT_INDEX_5",
                        "params": {
                            "address": "$ADDRESS_2",
                            "asset": "XCP",
                            "block_index": "$BLOCK_INDEX",
                            "calling_function": "cancel order",
                            "event": "$CANCEL_ALL_ORDER_A_HASH",
                            "quantity": 2000,
                            "tx_index": "$TX_INDEX",
                            "utxo": None,
                            "utxo_address": None,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "ORDER_UPDATE",
                        "event_index": "$EVENT_INDEX_4",
                        "params": {
                            "status": "cancelled",
                            "tx_hash": "$CANCEL_ALL_ORDER_A_HASH",
                        },
                        "tx_hash": "$TX_HASH",
                    },
                    {
                        "event": "INCREMENT_TRANSACTION_COUNT",
                        "event_index": "$EVENT_INDEX_3",
                        "params": {
                            "block_index": "$BLOCK_INDEX",
                            "count": 2,
                            "transaction_id": 70,
                        },
                        "tx_hash": "$TX_HASH",
                    },
                ],
            },
            {
                "url": "orders/$CANCEL_ALL_ORDER_A_HASH",
                "result": {
                    "status": "cancelled",
                    "tx_hash": "$CANCEL_ALL_ORDER_A_HASH",
                },
            },
            {
                "url": "orders/$CANCEL_ALL_ORDER_B_HASH",
                "result": {
                    "status": "cancelled",
                    "tx_hash": "$CANCEL_ALL_ORDER_B_HASH",
                },
            },
        ],
    },
    {
        "title": "Cancel all with no open offers (should fail)",
        "transaction": "cancel",
        "source": "$ADDRESS_2",
        "params": {},
        "expected_error": "ComposeError",
        "error_message": "no open offers for this address",
    },
]
