on: workflow_call

jobs:
  mainnet_test:
    runs-on: Linux-Large
    #runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        default: true
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libgirepository1.0-dev libleveldb-dev
        python -m pip install --upgrade pip
        pip install pylint maturin pytest pytest-cov coveralls
        cd counterparty-rs && pip install -e . && cd ..
        cd counterparty-core && pip install -e . && cd ..
    - name: Run tests
      run: |
        cd counterparty-core
        hatch run pytest counterpartycore/test/integrations/mainnet_test.py -s -vv
