name: Base Test Configuration

on:
  workflow_call:
    inputs:
      python-version:
        type: string
        default: "3.11"
      os:
        type: string
        default: "ubuntu-22.04"
      test-path:
        type: string
        required: true

jobs:
  test:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          default: true

      - name: Install dependencies
        run: |
          pip install pytest hatchling==1.25.0 hatch==1.13.0 pytest-cov coveralls
          python -m pip install --upgrade build

      - name: Run tests
        run: |
          cd counterparty-core
          hatch run pytest ${{ inputs.test-path }} --cov=counterpartycore/lib/ --cov-report=lcov:coverage.lcov

      - name: Upload coverage
        run: |
          cd counterparty-core
          export COVERALLS_FORCE_BRANCH="${GITHUB_REF_NAME}"
          coveralls --submit=./coverage.lcov
        env:
          GITHUB_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          COVERALLS_PARALLEL: true