on: workflow_call

jobs:
  comparehashes_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest hatchling==1.25.0 hatch==1.13.0 requests pytest-cov coveralls
    - name: Run compare hashes tests
      run: |
        cd counterparty-core
        pytest counterpartycore/test/integrations/comparehashes_test.py -s -vv \
            --cov=counterpartycore/lib/ --cov-report=lcov:coverage.lcov
    # upload coverage to coveralls
    - name: Coveralls
      run: |
          cd counterparty-core
          export COVERALLS_FORCE_BRANCH="$GITHUB_REF_NAME"
          coveralls --submit=./coverage.lcov 
      env:
        COVERALLS_PARALLEL: true
