name: Docker

on:
  push:
    branches: "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Docker
      run: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh
    - name: Build image
      run: |
        docker build -t counterparty .
    - name: Test image
      run: |
        docker run --rm counterparty -h
