name: Docker Compose Test

on:
  push:
    branches: "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Docker
      run: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y docker-compose-plugin
        python -m pip install --upgrade pip
        pip install pytest hatchling==1.25.0 hatch==1.13.0
        cd counterparty-rs && pip install -e . && cd ..
        cd counterparty-core && pip install -e . && cd ..
    - name: Run regtest tests
      run: |
        cd counterparty-core
        hatch run pytest counterpartycore/test/integrations/dockercompose_test.py
