name: Integrations Test

on:
  push:
    branches: "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Integrations:
    strategy:
      fail-fast: false
      # define the matrix
      matrix:

        # Units tests
        include:
          # Mainnet tests

          # bootstrap, run the server with --api-only and run
          # the locust tests
          - name: Mainnet API Load
            test-path: integrations/load_test.py
            os: Linux-Large-1
            only_on_develop: true
            no_cov_report: true

          # bootstrap, reparse 1000 blocks,
          # rollback 3 checkpoints and catchup
          #- name: Mainnet Bootstrap And Catchup
          #  test-path: integrations/mainnet_test.py
          #  os: Linux-Large-2
          #  only_on_develop: true

          # Regtest tests

          # run scenarios on regtest
          # testing rollback, reparse, reorg, etc
          - name: Regtest Scenarios
            test-path: integrations/regtest/scenarios_test.py
            install_bitcoin: true
          
          - name: Taproot Data Envelope Test
            test-path: integrations/regtest/taprootdata_test.py
            install_bitcoin: true

          # Testnet4 tests

          # bootstrap, reparse 1000 blocks,
          # rollback 3 checkpoints and catchup
          - name: Testnet4 Bootstrap And Catchup
            test-path: integrations/testnet4_test.py

          - name: Testnet4 Start and Shutdown
            test-path: integrations/shutdown_test.py

          - name: Testnet4 Rebuild
            test-path: integrations/rebuild_test.py

          # Other tests

          # run the docker-compose tests
          - name: Docker Compose
            test-path: integrations/dockercompose_test.py

          # compare hashes between several servers
          - name: Compare Hashes
            test-path: integrations/comparehashes_test.py

          - name: RSFetcher Test
            test-path: integrations/rsfetcher_test.py

    # run pytest_action.yml for the matrix
    uses: ./.github/workflows/pytest_action.yml
    with:
      name: ${{ matrix.name }}
      test-path: ${{ matrix.test-path }}
      install_bitcoin: ${{ matrix.install_bitcoin || false }}
      only_on_develop:  ${{ matrix.only_on_develop || false }}
      os: ${{ matrix.os || 'ubuntu-22.04' }}
      no_cov_report: ${{ matrix.no_cov_report || false }}
    secrets: inherit
