name: Property Test

on:
  push:
    branches: "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Property:
    uses: ./.github/workflows/pytest_action.yml
    with:
      name: Property Test
      test-path: integrations/regtest/property_test.py
      install_bitcoin: true
    secrets: inherit
