name: Pylint

on:
  push:
    branches: "**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        default: true
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libgirepository1.0-dev libleveldb-dev
        python -m pip install --upgrade pip
        pip install pylint maturin
        pip install pylint-sarif-unofficial
        pip install -e counterparty-rs
        pip install -e counterparty-lib
        pip install -e counterparty-cli
        pip install evdev
    - name: Analysing the code with pylint
      run: |
        pylint2sarif $(git ls-files '*.py' | grep -v counterparty-rs/tests/ | grep -v counterparty-lib/counterpartylib/test/ | grep -v counterparty-lib/tools/) || true
    - name: Upload SARIF
      uses: github/codeql-action/upload-sarif/@v2
      with:
        sarif_file: pylint.sarif
