name: Pytest Tests

on:
  push:
    branches: "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scenarios-test:
    uses: ./.github/workflows/_pytest_scenarios.yml
    secrets: inherit
  property-test:
    uses: ./.github/workflows/_pytest_property.yml
    secrets: inherit
  testnet4-test:
    uses: ./.github/workflows/_pytest_testnet4.yml
    secrets: inherit
  testnet4sync-test:
    uses: ./.github/workflows/_pytest_testnet4sync.yml
    secrets: inherit
  reparse-test:
    uses: ./.github/workflows/_pytest_reparse.yml
    secrets: inherit
  dockercompose-test:
    uses: ./.github/workflows/_pytest_dockercompose.yml
    secrets: inherit
  comparehashes-test:
    uses: ./.github/workflows/_base_test_config.yml
    with:
      test-path: counterpartycore/test/integrations/comparehashes_test.py
    secrets: inherit
  units-macos-m1:
    uses: ./.github/workflows/_pytest_units_macos.yml
    secrets: inherit
  units-ubuntu:
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    uses: ./.github/workflows/_base_test_config.yml
    with:
      python-version: ${{ matrix.python-version }}
      test-path: counterpartycore/test/units counterpartycore/test/functionals
    secrets: inherit
  coveralls:
    if: ${{ always() }}
    needs:
      - scenarios-test
      - property-test
      - testnet4-test
      - testnet4sync-test
      - reparse-test
      - dockercompose-test
      - comparehashes-test
      - units-ubuntu
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Install coveralls
      run: pip3 install --upgrade coveralls
    - name: Coveralls Finished
      run: |
          export COVERALLS_FORCE_BRANCH="$GITHUB_REF_NAME"
          coveralls --finish --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}