name: Pytest Tests

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scenarios-test:
    uses: ./.github/workflows/_pytest_scenarios.yml
  property-test:
    uses: ./.github/workflows/_pytest_property.yml
  testnet4-test:
    uses: ./.github/workflows/_pytest_testnet4.yml
  testnet4sync-test:
    uses: ./.github/workflows/_pytest_testnet4sync.yml
  reparse-test:
    uses: ./.github/workflows/_pytest_reparse.yml
  dockercompose-test:
    uses: ./.github/workflows/_pytest_dockercompose.yml
  comparehashes-test:
    uses: ./.github/workflows/_pytest_comparehashes.yml
  units-macos-m1:
    uses: ./.github/workflows/_pytest_units_macos.yml
  units-ubuntu:
    uses: ./.github/workflows/_pytest_units_ubuntu.yml
  coveralls:
    if: ${{ always() }}
    needs:
      - scenarios-test
      - property-test
      - testnet4-test
      - testnet4sync-test
      - reparse-test
      - dockercompose-test
      - comparehashes-test
      - units-ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@v2
      with:
        parallel-finished: true
        carryforward: "Scenarios,Property,Testnet4,Testnet4Sync,Reparse,DockerCompose,CompareHashes,Unit-3.10,Unit-3.11,Unit-3.12"