on: workflow_call

jobs:
  units_macos_m1:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      # Install dependencies
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Python 3.10 and leveldb
        run: |
          brew install rustup python@3.10
          brew reinstall rustup
          echo '/opt/homebrew/opt/python@3.10/libexec/bin' >> $GITHUB_PATH

      - name: Install pytest and build module
        run: |
          python3.10 -m pip install pytest hatchling==1.25.0 hatch==1.13.0
          python3.10 -m pip install --upgrade build

      # Run counterparty-rs tests
      - name: Test counterparty-rs
        run: |
          cd counterparty-rs
          cargo test

      # Run counterparty-core tests
      - name: Run counterparty-core tests
        run: |
          cd counterparty-core
          hatch run pytest counterpartycore/test/units counterpartycore/test/functionals -s -vv