name: Pytest Tests

on:
  push:
    branches: "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  mainnet-tests:
    if: github.ref == 'refs/heads/develop'
    strategy:
      fail-fast: false
      matrix:
        include:
          - test-path: integrations/load_test.py
            os: Linux-Large-1
          - test-path: integrations/main_test.py
            os: Linux-Large-2
    uses: ./.github/workflows/pytest_action.yml
    with:
      os: ${{ matrix.os }}
      test-path: ${{ matrix.test-path }}
      run_coveralls: false
    secrets: inherit

  ubuntu-test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - test-path: integrations/regtest/scenarios_test.py
            install_bitcoin: true
          - test-path: integrations/regtest/property_test.py
            install_bitcoin: true
          - test-path: integrations/testnet4_test.py
          - test-path: integrations/reparse_test.py
          - test-path: integrations/dockercompose_test.py
          - test-path: integrations/comparehashes_test.py
          - test-path: integrations/testnet4sync_test.py
    uses: ./.github/workflows/pytest_action.yml
    with:
      test-path: ${{ matrix.test-path }}
      install_bitcoin: ${{ matrix.install_bitcoin || false }}
    secrets: inherit

  multiplaform-test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        os: ["ubuntu-22.04", "macos-14"]
        test-path:
          - units counterpartycore/test/functionals
    uses: ./.github/workflows/pytest_action.yml
    with:
      python-version: ${{ matrix.python-version }}
      test-path: ${{ matrix.test-path }}
    secrets: inherit

  coveralls:
    if: ${{ always() }}
    needs:
      - ubuntu-test
      - multiplaform-test
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Install coveralls
      run: pip3 install --upgrade coveralls
    - name: Coveralls Finished
      run: |
          coveralls --finish --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}