on: workflow_call

jobs:
  ubuntu-22-04-python3-12:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      # Install dependencies

      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install Rust
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install leveldb
        run: |
          sudo apt-get install -y libleveldb-dev

      - name: Install pytest and build module
        run: |
          pip install pytest hatchling==1.25.0 hatch==1.13.0
          python -m pip install --upgrade build

      # Run counterparty-rs tests

      - name: Test counterparty-rs
        run: |
          cd counterparty-rs
          cargo test

      # Run counterparty-core tests

      - name: Run counterparty-core tests
        run: |
          cd counterparty-core
          hatch run pytest counterpartycore/test/units counterpartycore/test/functionals -s -vv