name: Pytest Tests

on:
  push:
    branches: "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scenarios-test:
    uses: ./.github/workflows/_pytest_scenarios.yml
    secrets: inherit
  property-test:
    uses: ./.github/workflows/_pytest_property.yml
    secrets: inherit
  testnet4-test:
    uses: ./.github/workflows/_pytest_testnet4.yml
    secrets: inherit
  testnet4sync-test:
    uses: ./.github/workflows/_pytest_testnet4sync.yml
    secrets: inherit
  reparse-test:
    uses: ./.github/workflows/_pytest_reparse.yml
    secrets: inherit
  dockercompose-test:
    uses: ./.github/workflows/_pytest_dockercompose.yml
    secrets: inherit
  comparehashes-test:
    uses: ./.github/workflows/_pytest_comparehashes.yml
    secrets: inherit
  units-macos-m1:
    uses: ./.github/workflows/_pytest_units_macos.yml
    secrets: inherit
  units-ubuntu:
    uses: ./.github/workflows/_pytest_units_ubuntu.yml
    secrets: inherit
  coveralls:
    if: ${{ always() }}
    needs:
      - scenarios-test
      - property-test
      - testnet4-test
      - testnet4sync-test
      - reparse-test
      - dockercompose-test
      - comparehashes-test
      - units-ubuntu
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Install coveralls
      run: pip3 install --upgrade coveralls
    - name: Coveralls Finished
      run: coveralls --finish
      env:
        GITHUB_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}