name: Pytest

on:
  push:
    branches: "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Test:
    strategy:
      fail-fast: false
      # define the matrix
      matrix:

        # Units tests

        name: ["Units And Functionals"]
        python-version: ["3.10", "3.11", "3.12"]
        os: ["ubuntu-22.04", "macos-14"]
        test-path: ["units counterpartycore/test/functionals"]
        include:

          - name: Units And Functionals
            test-path: units counterpartycore/test/functionals
            python-version: 3.13
            os: ubuntu-22.04

          - name: Units And Functionals
            test-path: units counterpartycore/test/functionals
            python-version: 3.13
            os: macos-14

          # Mainnet tests

          # bootstrap, run the server with --api-only and run
          # the locust tests
          - name: Mainnet API Load
            test-path: integrations/load_test.py
            os: Linux-Large-1
            only_on_develop: true

          # bootstrap, reparse 1000 blocks,
          # rollback 3 checkpoints and catchup
          - name: Mainnet Bootstrap And Catchup
            test-path: integrations/mainnet_test.py
            os: Linux-Large-2
            only_on_develop: true

          # Regtest tests

          # run scenarios on regtest
          # testing rollback, reparse, reorg, etc
          - name: Regtest Scenarios
            test-path: integrations/regtest/scenarios_test.py
            install_bitcoin: true

          # run property tests on regtest
          - name: Property Test
            test-path: integrations/regtest/property_test.py
            install_bitcoin: true

          # Testnet4 tests

          # bootstrap, reparse 1000 blocks,
          # rollback 3 checkpoints and catchup
          - name: Testnet4 Bootstrap And Catchup
            test-path: integrations/testnet4_test.py 

          # Other tests

          # run the docker-compose tests
          - name: Docker Compose
            test-path: integrations/dockercompose_test.py

          # compare hashes between several servers
          - name: Compare Hashes
            test-path: integrations/comparehashes_test.py

    # run pytest_action.yml for the matrix
    uses: ./.github/workflows/pytest_action.yml
    with:
      name: ${{ matrix.name }} (${{ matrix.os }} - Python ${{ matrix.python-version }})
      test-path: ${{ matrix.test-path }}
      os: ${{ matrix.os || 'ubuntu-22.04' }}
      python-version: ${{ matrix.python-version || '3.11' }}
      install_bitcoin: ${{ matrix.install_bitcoin || false }}
      only_on_develop:  ${{ matrix.only_on_develop || false }}
    secrets: inherit
