name: Regtest test

on:
  push:
    branches: "**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        default: true
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libgirepository1.0-dev libleveldb-dev nodejs npm
        python -m pip install --upgrade pip
        pip install maturin sh rich pyyaml
        cd counterparty-rs && pip install -e . && cd ..
        cd counterparty-core && pip install -e . && cd ..
        pip install evdev
        git clone https://github.com/CounterpartyXCP/addrindexrs.git
        cd addrindexrs
        cargo install --path=.
        wget https://bitcoincore.org/bin/bitcoin-core-27.1/bitcoin-27.1-x86_64-linux-gnu.tar.gz
        tar -xvf bitcoin-27.1-x86_64-linux-gnu.tar.gz
        sudo cp bitcoin-27.1/bin/bitcoin-cli /usr/local/bin/bitcoin-cli
        sudo cp bitcoin-27.1/bin/bitcoind /usr/local/bin/bitcoind
        sudo cp bitcoin-27.1/bin/bitcoin-wallet /usr/local/bin/bitcoin-wallet
        npm install dredd --global
    - name: Run regtest tests
      run: |
        cd counterparty-core
        python3 counterpartycore/test/regtest/testscenarios.py
