name: Code Scanners

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  bandit:
    uses: ./.github/workflows/_scanner_bandit.yml
  codeql:
    uses: ./.github/workflows/_scanner_codeql.yml
  licenses:
    uses: ./.github/workflows/_scanner_licenses.yml
  pylint:
    uses: ./.github/workflows/_scanner_pylint.yml
  ruff-check:
    uses: ./.github/workflows/_scanner_ruff_check.yml
  ruff-format:
    uses: ./.github/workflows/_scanner_ruff_format.yml