name: Test Docker Compose

on:
  push:
    branches: ['disbale-compose']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: alinz/ssh-scp-action@master
      with:
        key: ${{ secrets.TEST_SERVER_KEY }}
        host: 34.67.65.156 # temporary
        user: ouziel # temporary
        ssh_before: |
          rm -f test_compose.sh
        scp: |
          .github/workflows/test_compose.sh ouziel@34.67.65.156:~/test_compose.sh
        ssh_after: |
          sh test_compose.sh