name: Test Docker Compose

on:
  push:
    branches: ['compose']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: alinz/ssh-scp-action@master
      with:
        key: ${{ secrets.TEST_SERVER_KEY }}
        host: 35.202.104.199 # temporary
        user: ouziel # temporary
        ssh_before: |
          rm -f test_compose.sh
        scp: |
          .github/workflows/test_compose.sh ouziel@35.202.104.199:~/test_compose.sh
        ssh_after: |
          sh test_compose.sh